In [1064]:
import pandas as pd
import numpy as np
from standardize_country import name_to_alpha_2, alpha_2_to_name

In [1065]:
central_debt = pd.read_csv("Data/central_debt_as_gdp.csv")

In [1066]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,6.904479171,8.70029105,9.154082857,8.437266097,7.997660199,7.384412942,6.130409903,7.39749473,no data,no data
2,Albania,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,65.53000174,70.03000162,72.670076,72.38004424,70.11993217,67.61001652,65.72986791,74.45151697,73.16289694,66.46365803
3,Algeria,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,7.093511132,7.658320146,8.733313712,20.43828686,27.24198231,38.36645363,46.04638761,52.00931249,62.82192436,52.39688055
4,Angola,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,33.14910364,39.80985691,57.09304822,75.66263732,69.32286758,92.99500121,113.5541748,138.897101,86.86058241,67.04993961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,Yemen,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.43184261,48.94994435,57.05039413,75.3489169,83.99681875,89.53508505,94.60908113,98.46952434,85.08302326,73.53135942
172,Zambia,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,25.90872757,33.85676882,61.86889743,58.03461321,63.35777959,75.22947056,94.42606901,140.2106182,110.7897389,no data
173,Zimbabwe,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,37.04415889,42.30389623,48.0142633,49.89191183,74.07511039,51.00144461,82.33805679,84.44771597,59.80656696,92.8237321
174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,"©IMF, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1067]:
#removing blank rows
central_debt.drop([0,174,175], inplace = True)

In [1068]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Afghanistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,6.904479171,8.70029105,9.154082857,8.437266097,7.997660199,7.384412942,6.130409903,7.39749473,no data,no data
2,Albania,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,65.53000174,70.03000162,72.670076,72.38004424,70.11993217,67.61001652,65.72986791,74.45151697,73.16289694,66.46365803
3,Algeria,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,7.093511132,7.658320146,8.733313712,20.43828686,27.24198231,38.36645363,46.04638761,52.00931249,62.82192436,52.39688055
4,Angola,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,33.14910364,39.80985691,57.09304822,75.66263732,69.32286758,92.99500121,113.5541748,138.897101,86.86058241,67.04993961
5,Antigua and Barbuda,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,95.79104783,101.369132,99.07128775,86.12589358,92.19273211,87.69958735,81.25083661,101.4769561,102.3576292,90.56216559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Vietnam,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,34.15699322,36.98682186,39.77107072,42.08204151,41.1091641,39.48084603,37.59935732,39.01628958,38.72076655,no data
170,West Bank and Gaza,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,30.23138981,33.95213644,37.07095266,41.54982506,42.66073409,44.6100425,46.11133367,61.21666852,64.28908402,59.77614165
171,Yemen,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.43184261,48.94994435,57.05039413,75.3489169,83.99681875,89.53508505,94.60908113,98.46952434,85.08302326,73.53135942
172,Zambia,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,25.90872757,33.85676882,61.86889743,58.03461321,63.35777959,75.22947056,94.42606901,140.2106182,110.7897389,no data
173,Zimbabwe,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,37.04415889,42.30389623,48.0142633,49.89191183,74.07511039,51.00144461,82.33805679,84.44771597,59.80656696,92.8237321

In [1069]:
#standardizing country names
central_debt.replace(name_to_alpha_2, inplace = True)

In [1070]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,6.904479171,8.70029105,9.154082857,8.437266097,7.997660199,7.384412942,6.130409903,7.39749473,no data,no data
2,AL,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,65.53000174,70.03000162,72.670076,72.38004424,70.11993217,67.61001652,65.72986791,74.45151697,73.16289694,66.46365803
3,DZ,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,7.093511132,7.658320146,8.733313712,20.43828686,27.24198231,38.36645363,46.04638761,52.00931249,62.82192436,52.39688055
4,AO,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,33.14910364,39.80985691,57.09304822,75.66263732,69.32286758,92.99500121,113.5541748,138.897101,86.86058241,67.04993961
5,AG,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,95.79104783,101.369132,99.07128775,86.12589358,92.19273211,87.69958735,81.25083661,101.4769561,102.3576292,90.56216559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,34.15699322,36.98682186,39.77107072,42.08204151,41.1091641,39.48084603,37.59935732,39.01628958,38.72076655,no data
170,PS,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,30.23138981,33.95213644,37.07095266,41.54982506,42.66073409,44.6100425,46.11133367,61.21666852,64.28908402,59.77614165
171,YE,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.43184261,48.94994435,57.05039413,75.3489169,83.99681875,89.53508505,94.60908113,98.46952434,85.08302326,73.53135942
172,ZM,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,25.90872757,33.85676882,61.86889743,58.03461321,63.35777959,75.22947056,94.42606901,140.2106182,110.7897389,no data
173,ZW,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,37.04415889,42.30389623,48.0142633,49.89191183,74.07511039,51.00144461,82.33805679,84.44771597,59.80656696,92.8237321

In [1071]:
#replacing "no data" with np.nan for standardization
central_debt.replace({"no data": np.nan}, inplace = True)

In [1072]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479171,8.70029105,9.154082857,8.437266097,7.997660199,7.384412942,6.130409903,7.39749473,NaN,NaN
2,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.53000174,70.03000162,72.670076,72.38004424,70.11993217,67.61001652,65.72986791,74.45151697,73.16289694,66.46365803
3,DZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511132,7.658320146,8.733313712,20.43828686,27.24198231,38.36645363,46.04638761,52.00931249,62.82192436,52.39688055
4,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.14910364,39.80985691,57.09304822,75.66263732,69.32286758,92.99500121,113.5541748,138.897101,86.86058241,67.04993961
5,AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.79104783,101.369132,99.07128775,86.12589358,92.19273211,87.69958735,81.25083661,101.4769561,102.3576292,90.56216559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.15699322,36.98682186,39.77107072,42.08204151,41.1091641,39.48084603,37.59935732,39.01628958,38.72076655,NaN
170,PS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.23138981,33.95213644,37.07095266,41.54982506,42.66073409,44.6100425,46.11133367,61.21666852,64.28908402,59.77614165
171,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.43184261,48.94994435,57.05039413,75.3489169,83.99681875,89.53508505,94.60908113,98.46952434,85.08302326,73.53135942
172,ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.90872757,33.85676882,61.86889743,58.03461321,63.35777959,75.22947056,94.42606901,140.2106182,110.7897389,NaN
173,ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.04415889,42.30389623,48.0142633,49.89191183,74.07511039,51.00144461,82.33805679,84.44771597,59.80656696,92.8237321

In [1073]:
#rename col to country
central_debt.rename({"Central Government Debt (Percent of GDP)": "Country"}, axis = 1, inplace = True)

In [1074]:
central_debt

,Country,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479171,8.70029105,9.154082857,8.437266097,7.997660199,7.384412942,6.130409903,7.39749473,NaN,NaN
2,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.53000174,70.03000162,72.670076,72.38004424,70.11993217,67.61001652,65.72986791,74.45151697,73.16289694,66.46365803
3,DZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511132,7.658320146,8.733313712,20.43828686,27.24198231,38.36645363,46.04638761,52.00931249,62.82192436,52.39688055
4,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.14910364,39.80985691,57.09304822,75.66263732,69.32286758,92.99500121,113.5541748,138.897101,86.86058241,67.04993961
5,AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.79104783,101.369132,99.07128775,86.12589358,92.19273211,87.69958735,81.25083661,101.4769561,102.3576292,90.56216559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.15699322,36.98682186,39.77107072,42.08204151,41.1091641,39.48084603,37.59935732,39.01628958,38.72076655,NaN
170,PS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.23138981,33.95213644,37.07095266,41.54982506,42.66073409,44.6100425,46.11133367,61.21666852,64.28908402,59.77614165
171,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.43184261,48.94994435,57.05039413,75.3489169,83.99681875,89.53508505,94.60908113,98.46952434,85.08302326,73.53135942
172,ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.90872757,33.85676882,61.86889743,58.03461321,63.35777959,75.22947056,94.42606901,140.2106182,110.7897389,NaN
173,ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.04415889,42.30389623,48.0142633,49.89191183,74.07511039,51.00144461,82.33805679,84.44771597,59.80656696,92.8237321

In [1075]:
#converting to long format
central_debt = pd.melt(central_debt, id_vars = 'Country', var_name = 'Year', value_name = 'Central Govt Debt (Percentage of GDP)')

In [1076]:
central_debt

      Country  Year Central Govt Debt (Percentage of GDP)
0          AF  1950                                   NaN
1          AL  1950                                   NaN
2          DZ  1950                                   NaN
3          AO  1950                                   NaN
4          AG  1950                                   NaN
...       ...   ...                                   ...
12624      VN  2022                                   NaN
12625      PS  2022                           59.77614165
12626      YE  2022                           73.53135942
12627      ZM  2022                                   NaN
12628      ZW  2022                            92.8237321

[12629 rows x 3 columns]

In [1077]:
central_debt.set_index(['Country', 'Year'], inplace = True)

In [1078]:
central_debt

             Central Govt Debt (Percentage of GDP)
Country Year
AF      1950                                   NaN
AL      1950                                   NaN
DZ      1950                                   NaN
AO      1950                                   NaN
AG      1950                                   NaN
...                                            ...
VN      2022                                   NaN
PS      2022                           59.77614165
YE      2022                           73.53135942
ZM      2022                                   NaN
ZW      2022                            92.8237321

[12629 rows x 1 columns]

In [1079]:
#reading in general debt data
general_debt = pd.read_csv("Data/general_debt_as_gdp.csv")

In [1080]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,Australia,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,Austria,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,Belarus,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Venezuela,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,Vietnam,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,Yemen,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,"©IMF, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1081]:
#removing blank rows
general_debt.drop([0,88,89], inplace = True)

In [1082]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Albania,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,Australia,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,Austria,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,Belarus,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,Belgium,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,United States,83.12603738,72.9550324,72.52549155,71.75321864,73.56806647,68.49863345,64.72603348,62.32954603,64.92733248,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,Uzbekistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,Venezuela,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,Vietnam,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,Yemen,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [1083]:
#standardizing country names
general_debt.replace(name_to_alpha_2, inplace = True)

In [1084]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.12603738,72.9550324,72.52549155,71.75321864,73.56806647,68.49863345,64.72603348,62.32954603,64.92733248,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [1085]:
#replacing "no data" with np.nan for standardization
general_debt.replace({"no data": np.nan}, inplace = True)

In [1086]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.12603738,72.9550324,72.52549155,71.75321864,73.56806647,68.49863345,64.72603348,62.32954603,64.92733248,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [1087]:
#rename col to country
general_debt.rename({"General Government Debt (Percent of GDP)": "Country"}, axis = 1, inplace = True)

In [1088]:
general_debt

,Country,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.12603738,72.9550324,72.52549155,71.75321864,73.56806647,68.49863345,64.72603348,62.32954603,64.92733248,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [1089]:
#converting to long format
general_debt = pd.melt(general_debt, id_vars = 'Country', var_name = 'Year', value_name = 'General Govt Debt (Percentage of GDP)')

In [1090]:
general_debt

     Country  Year General Govt Debt (Percentage of GDP)
0         AL  1950                                   NaN
1         AU  1950                                   NaN
2         AT  1950                                   NaN
3         BY  1950                                   NaN
4         BE  1950                                   NaN
...      ...   ...                                   ...
6346      US  2022                            121.383217
6347      UZ  2022                             34.294587
6348      VE  2022                            157.809488
6349      VN  2022                             37.091308
6350      YE  2022                             73.531359

[6351 rows x 3 columns]

In [1091]:
#setting index to country and year for merging
general_debt.set_index(['Country', 'Year'], inplace = True)

In [1092]:
general_debt

             General Govt Debt (Percentage of GDP)
Country Year
AL      1950                                   NaN
AU      1950                                   NaN
AT      1950                                   NaN
BY      1950                                   NaN
BE      1950                                   NaN
...                                            ...
US      2022                            121.383217
UZ      2022                             34.294587
VE      2022                            157.809488
VN      2022                             37.091308
YE      2022                             73.531359

[6351 rows x 1 columns]

In [1093]:
loan_debt_data = pd.concat([central_debt, general_debt], axis = 1)

In [1094]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
Country,Year,,
AF,1950,NaN,NaN
AL,1950,NaN,NaN
DZ,1950,NaN,NaN
AO,1950,NaN,NaN
AG,1950,NaN,NaN
...,...,...,...
PH,2022,NaN,57.519704
TJ,2022,NaN,34.631164
TZ,2022,NaN,41.622404
AE,2022,NaN,29.95788
UZ,2022,NaN,34.294587

In [1095]:
chinese_loan = pd.read_csv("Data/chinese_loan_data.csv")

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\2323119892.py:1: DtypeWarning: Columns (23,45,46,86,87,88,89,91,92,94,95,97) have mixed types. Specify dtype option on import or set low_memory=False.
  chinese_loan = pd.read_csv("Data/chinese_loan_data.csv")

In [1096]:
chinese_loan

,AidData Record ID,Recommended For Aggregates,AidData Parent ID,Umbrella,Financier Country,Recipient,Recipient ISO-3,Recipient Region,Commitment Year,Implementation Start Year,...,Geographic Level of Precision Available,ADM1 Level Available,ADM2 Level Available,Geospatial Feature Available,Source Quality Score,Data Completeness Score,Implementation Detail Score,Loan Detail Score,Unnamed: 126,Unnamed: 127
0,94556,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
1,94564,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
2,94565,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,4,3,5.0,NaN,NaN,NaN
3,94567,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,4,3.0,NaN,NaN,NaN
4,94568,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,NaN,...,NaN,NaN,NaN,NaN,5,4,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20980,16239,No,NaN,Yes,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN
20981,16401,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,3,3.0,NaN,NaN,NaN
20982,63472,Yes,715,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,Precise,Yes,Yes,Yes,5,4,3.0,5.0,NaN,NaN
20983,72639,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,5,3,4.0,NaN,NaN,NaN
20984,73615,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,NaN,NaN,NaN,NaN,4,3,1.0,NaN,NaN,NaN

In [1097]:
chinese_loan = chinese_loan[chinese_loan["Recommended For Aggregates"] == "Yes"]

In [1098]:
chinese_loan

,AidData Record ID,Recommended For Aggregates,AidData Parent ID,Umbrella,Financier Country,Recipient,Recipient ISO-3,Recipient Region,Commitment Year,Implementation Start Year,...,Geographic Level of Precision Available,ADM1 Level Available,ADM2 Level Available,Geospatial Feature Available,Source Quality Score,Data Completeness Score,Implementation Detail Score,Loan Detail Score,Unnamed: 126,Unnamed: 127
0,94556,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
1,94564,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
2,94565,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,4,3,5.0,NaN,NaN,NaN
3,94567,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,4,3.0,NaN,NaN,NaN
4,94568,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,NaN,...,NaN,NaN,NaN,NaN,5,4,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20978,34717,Yes,NaN,No,China (People's Republic of),Zambia,ZMB,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,3,3,4.0,NaN,NaN,NaN
20981,16401,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,3,3.0,NaN,NaN,NaN
20982,63472,Yes,715,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,Precise,Yes,Yes,Yes,5,4,3.0,5.0,NaN,NaN
20983,72639,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,5,3,4.0,NaN,NaN,NaN
20984,73615,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,NaN,NaN,NaN,NaN,4,3,1.0,NaN,NaN,NaN

In [1099]:
chinese_loan.columns[45:60]

Index(['Security Agent/Collateral Agent',
       'Security Agent/Collateral Agent Type', 'Collateral',
       ' Amount (Original Currency) ', 'Original Currency', 'Amount Estimated',
       ' Amount (Constant USD 2021) ', ' Amount (Nominal USD) ',
       ' Adjusted Amount (Original Currency) ',
       ' Adjusted Amount (Constant USD 2021) ',
       ' Adjusted Amount (Nominal USD) ', 'Financial Distress',
       'Commitment Date (MM/DD/YYYY)', 'Commitment Date Estimated',
       'Planned Implementation Start Date (MM/DD/YYYY)'],
      dtype='object')

In [1100]:
#isolating for only the columns we want
chinese_loan = chinese_loan[["Recipient", "Implementation Start Year", "Intent", "Flow Type Simplified", "Sector Name", "COVID", ' Adjusted Amount (Nominal USD) ']]

In [1101]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,NaN,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,"13,000,000.00"
4,Afghanistan,NaN,Development,Grant,EMERGENCY RESPONSE,NaN,"7,500,000.00"
...,...,...,...,...,...,...,...
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,NaN,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,NaN,"603,974.73"
20982,Zimbabwe,NaN,Mixed,Loan,"INDUSTRY, MINING, CONSTRUCTION",NaN,"5,822,316.37"
20983,Zimbabwe,2000.0,Development,Grant,HEALTH,NaN,NaN
20984,Zimbabwe,NaN,Development,Grant,EMERGENCY RESPONSE,NaN,"19,931.00"

In [1102]:
#Adding nos to COVID column
chinese_loan['COVID'].fillna("No", inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3051015601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan['COVID'].fillna("No", inplace = True)

In [1103]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,No,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,"13,000,000.00"
4,Afghanistan,NaN,Development,Grant,EMERGENCY RESPONSE,No,"7,500,000.00"
...,...,...,...,...,...,...,...
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"603,974.73"
20982,Zimbabwe,NaN,Mixed,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,"5,822,316.37"
20983,Zimbabwe,2000.0,Development,Grant,HEALTH,No,NaN
20984,Zimbabwe,NaN,Development,Grant,EMERGENCY RESPONSE,No,"19,931.00"

In [1104]:
#Replacing not listed for the other categories
chinese_loan['Intent'].fillna("Not Listed", inplace = True)
chinese_loan['Flow Type Simplified'].fillna("Not Listed", inplace = True)
chinese_loan['Sector Name'].fillna("Not Listed", inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3911743959.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan['Intent'].fillna("Not Listed", inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3911743959.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan['Flow Type Simplified'].fillna("Not Listed", inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3911743959.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan['Sector Name'].fillna("Not Listed", inplace = True)

In [1105]:
#dropping years without implementation dates
chinese_loan.dropna(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\643575008.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.dropna(inplace = True)

In [1106]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,No,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,"13,000,000.00"
6,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,"3,600,000.00"
...,...,...,...,...,...,...,...
20971,Viet Nam,2000.0,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,"10,760,000.00"
20972,Viet Nam,2000.0,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,"15,316,000.00"
20974,Viet Nam,2000.0,Development,Grant,EMERGENCY RESPONSE,No,"20,000.00"
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"603,974.73"

In [1107]:
chinese_loan["Implementation Start Year"] = chinese_loan["Implementation Start Year"].astype('int32')

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\828448132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Implementation Start Year"] = chinese_loan["Implementation Start Year"].astype('int32')

In [1108]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,Afghanistan,2021,Development,Grant,EMERGENCY RESPONSE,No,"7,111,455.91"
1,Afghanistan,2021,Development,Grant,HEALTH,Yes,"12,600,000.00"
2,Afghanistan,2021,Development,Grant,HEALTH,Yes,"14,400,000.00"
3,Afghanistan,2021,Development,Grant,EMERGENCY RESPONSE,Yes,"13,000,000.00"
6,Afghanistan,2021,Development,Grant,HEALTH,Yes,"3,600,000.00"
...,...,...,...,...,...,...,...
20971,Viet Nam,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,"10,760,000.00"
20972,Viet Nam,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,"15,316,000.00"
20974,Viet Nam,2000,Development,Grant,EMERGENCY RESPONSE,No,"20,000.00"
20978,Zambia,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"120,794.95"
20981,Zimbabwe,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"603,974.73"

In [1109]:
chinese_loan.replace(name_to_alpha_2, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3419558913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.replace(name_to_alpha_2, inplace = True)

In [1110]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,"7,111,455.91"
1,AF,2021,Development,Grant,HEALTH,Yes,"12,600,000.00"
2,AF,2021,Development,Grant,HEALTH,Yes,"14,400,000.00"
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,"13,000,000.00"
6,AF,2021,Development,Grant,HEALTH,Yes,"3,600,000.00"
...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,"10,760,000.00"
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,"15,316,000.00"
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,"20,000.00"
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"120,794.95"
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,"603,974.73"

In [1111]:
#converted adjusted to float

def remove_space(x):
    one = x
    two = ""
    for s in one:
        if s.isdigit():
            two += s
    return two

chinese_loan["Adjusted Amount (Nominal USD)"] = chinese_loan[" Adjusted Amount (Nominal USD) "].apply(lambda x: remove_space(x))
    

chinese_loan["Adjusted Amount (Nominal USD)"] = pd.to_numeric(chinese_loan["Adjusted Amount (Nominal USD)"], downcast = 'float')

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3437805329.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"] = chinese_loan[" Adjusted Amount (Nominal USD) "].apply(lambda x: remove_space(x))
C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3437805329.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"] = pd.to_numeric(chinese_loan["Adjusted Amount (Nominal USD)"], downcast = 'float')

In [1112]:
chinese_loan.drop(" Adjusted Amount (Nominal USD) ", axis = 1, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3540160246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.drop(" Adjusted Amount (Nominal USD) ", axis = 1, inplace = True)

In [1113]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,7.111456e+08
1,AF,2021,Development,Grant,HEALTH,Yes,1.260000e+09
2,AF,2021,Development,Grant,HEALTH,Yes,1.440000e+09
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,1.300000e+09
6,AF,2021,Development,Grant,HEALTH,Yes,3.600000e+08
...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,1.076000e+09
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,1.531600e+09
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,2.000000e+06
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,1.207950e+07
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,6.039747e+07

In [1114]:
#categorizing loan amounts into 4 even blocks

#chinese_loan = chinese_loan[chinese_loan["Adjusted Amount (Nominal USD)"] > 0]
#["Adjusted Amount (Nominal USD)"], bins = pd.cut(chinese_loan["Adjusted Amount (Nominal USD)"].to_numpy(), bins = 4, retbins = True)
#bins

In [1115]:
#chinese_loan["Adjusted Amount (Nominal USD)"][0]

In [1116]:
#chinese_loan

In [1117]:
#chinese_loan.replace({pd.Interval(-1499998698.7, 375000000975.0, closed = "right"): "Grade One",
                      #pd.Interval(375000000975.0, 750000000650.0, closed = "right"): "Grade Two",
                      #pd.Interval(750000000650.0, 1125000000325.0, closed = "right"): "Grade Three",
                      #pd.Interval(1125000000325.0, 1500000000000.0, closed = "right"): "Grade Four"
                     #}, inplace = True)

In [1118]:
#chinese_loan

In [1119]:
#Limiting recipients to only countries

chinese_loan = chinese_loan[chinese_loan["Recipient"].isin(alpha_2_to_name.keys())]
np.unique(chinese_loan["Recipient"])

array(['AF', 'AG', 'AL', 'AM', 'AO', 'AR', 'AZ', 'BA', 'BB', 'BD', 'BF',
       'BG', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BW', 'BY', 'CD', 'CF',
       'CG', 'CI', 'CK', 'CL', 'CM', 'CO', 'CR', 'CU', 'CV', 'DJ', 'DM',
       'DO', 'DZ', 'EC', 'EG', 'ER', 'ET', 'FJ', 'FM', 'GA', 'GD', 'GE',
       'GH', 'GM', 'GN', 'GQ', 'GW', 'GY', 'HN', 'HT', 'ID', 'IL', 'IN',
       'IQ', 'IR', 'JM', 'JO', 'KE', 'KG', 'KH', 'KI', 'KM', 'KP', 'KZ',
       'LA', 'LB', 'LC', 'LK', 'LR', 'LS', 'LY', 'MA', 'MD', 'ME', 'MG',
       'MH', 'MK', 'ML', 'MM', 'MN', 'MR', 'MU', 'MV', 'MW', 'MX', 'MY',
       'MZ', 'NA', 'NE', 'NG', 'NI', 'NP', 'NR', 'NU', 'OM', 'PA', 'PE',
       'PG', 'PH', 'PK', 'PS', 'PY', 'RO', 'RS', 'RU', 'RW', 'SB', 'SC',
       'SD', 'SL', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SY', 'TD', 'TG',
       'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TZ', 'UA', 'UG',
       'UY', 'UZ', 'VE', 'VN', 'VU', 'WS', 'YE', 'ZA', 'ZM', 'ZW'],
      dtype=object)

In [1120]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,7.111456e+08
1,AF,2021,Development,Grant,HEALTH,Yes,1.260000e+09
2,AF,2021,Development,Grant,HEALTH,Yes,1.440000e+09
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,1.300000e+09
6,AF,2021,Development,Grant,HEALTH,Yes,3.600000e+08
...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,1.076000e+09
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,1.531600e+09
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,2.000000e+06
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,1.207950e+07
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,6.039747e+07

In [1121]:
chinese_loan["Adjusted Amount (Nominal USD)"] = pd.qcut(chinese_loan["Adjusted Amount (Nominal USD)"], q = 3, labels = ["Low", "Medium", "High"])

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\541604965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"] = pd.qcut(chinese_loan["Adjusted Amount (Nominal USD)"], q = 3, labels = ["Low", "Medium", "High"])

In [1122]:

chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Medium
1,AF,2021,Development,Grant,HEALTH,Yes,Medium
2,AF,2021,Development,Grant,HEALTH,Yes,Medium
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Medium
6,AF,2021,Development,Grant,HEALTH,Yes,Medium
...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Medium
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Medium
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Low
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Low
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Medium

In [1123]:
chinese_loan.dropna(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\1448102153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.dropna(inplace = True)

In [1124]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Medium
1,AF,2021,Development,Grant,HEALTH,Yes,Medium
2,AF,2021,Development,Grant,HEALTH,Yes,Medium
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Medium
6,AF,2021,Development,Grant,HEALTH,Yes,Medium
...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Medium
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Medium
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Low
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Low
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Medium

In [1125]:
sectors = np.unique(chinese_loan["Sector Name"])
intents = np.unique(chinese_loan["Intent"])
flows = np.unique(chinese_loan["Flow Type Simplified"])
covid = np.unique(chinese_loan["COVID"])
amounts = np.unique(chinese_loan["Adjusted Amount (Nominal USD)"])

In [1126]:
chinese_loan = chinese_loan.groupby(['Recipient', 'Implementation Start Year']).apply(lambda x: x.drop(['Recipient', 'Implementation Start Year'], axis = 1)
                                                                                                       .apply(pd.Series.value_counts))

In [1127]:
chinese_loan

                                                                              Intent  \
Recipient Implementation Start Year
AF        2000                      Development                                  1.0
                                    EMERGENCY RESPONSE                           NaN
                                    Grant                                        NaN
                                    High                                         NaN
                                    Low                                          NaN
...                                                                              ...
ZW        2021                      Medium                                       NaN
                                    No                                           NaN
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES     NaN
                                    WATER SUPPLY AND SANITATION                  NaN
                                    Yes                                          NaN

                                                                              Flow Type Simplified  \
Recipient Implementation Start Year
AF        2000                      Development                                                NaN
                                    EMERGENCY RESPONSE                                         NaN
                                    Grant                                                      1.0
                                    High                                                       NaN
                                    Low                                                        NaN
...                                                                                            ...
ZW        2021                      Medium                                                     NaN
                                    No                                                         NaN
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES                   NaN
                                    WATER SUPPLY AND SANITATION                                NaN
                                    Yes                                                        NaN

                                                                              Sector Name  \
Recipient Implementation Start Year
AF        2000                      Development                                       NaN
                                    EMERGENCY RESPONSE                                1.0
                                    Grant                                             NaN
                                    High                                              NaN
                                    Low                                               NaN
...                                                                                   ...
ZW        2021                      Medium                                            NaN
                                    No                                                NaN
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES          1.0
                                    WATER SUPPLY AND SANITATION                       1.0
                                    Yes                                               NaN

                                                                              COVID  \
Recipient Implementation Start Year
AF        2000                      Development                                 NaN
                                    EMERGENCY RESPONSE                          NaN
                                    Grant                                       NaN
                                    High                                        NaN
                                    Low                                         NaN
...                                                                             ...
ZW        2021                      Medium                                      NaN
                                    No                                          4.0
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES    NaN
                                    WATER SUPPLY AND SANITATION                 NaN
                                    Yes                                         6.0

                                                                              Adjusted Amount (Nominal USD)
Recipient Implementation Start Year
AF        2000                      Development                                                         NaN
                                    EMERGENCY RESPONSE                                                  NaN
                                    Grant                                                               NaN
                                    High                                                                0.0
                                    Low                                                                 1.0
...                                                                                                     ...
ZW        2021                      Medium                                                              5.0
                                    No                                                                  NaN
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES                            NaN
                                    WATER SUPPLY AND SANITATION                                         NaN
                                    Yes                                                                 NaN

[16735 rows x 5 columns]

In [1128]:
def return_not_na(x):
    for item in x:
        if pd.notna(item):
            return item


count = chinese_loan.apply(lambda x: return_not_na(x), axis = 1)
chinese_loan.drop(["Intent", "Flow Type Simplified", "Sector Name", "COVID", "Adjusted Amount (Nominal USD)"], axis = 1, inplace = True)
chinese_loan["Count"] = count

In [1129]:
chinese_loan

                                                                              Count
Recipient Implementation Start Year
AF        2000                      Development                                 1.0
                                    EMERGENCY RESPONSE                          1.0
                                    Grant                                       1.0
                                    High                                        0.0
                                    Low                                         1.0
...                                                                             ...
ZW        2021                      Medium                                      5.0
                                    No                                          4.0
                                    OTHER SOCIAL INFRASTRUCTURE AND SERVICES    1.0
                                    WATER SUPPLY AND SANITATION                 1.0
                                    Yes                                         6.0

[16735 rows x 1 columns]

In [1130]:
chinese_loan.reset_index(inplace = True)

In [1131]:
chinese_loan

,Recipient,Implementation Start Year,level_2,Count
0,AF,2000,Development,1.0
1,AF,2000,EMERGENCY RESPONSE,1.0
2,AF,2000,Grant,1.0
3,AF,2000,High,0.0
4,AF,2000,Low,1.0
...,...,...,...,...
16730,ZW,2021,Medium,5.0
16731,ZW,2021,No,4.0
16732,ZW,2021,OTHER SOCIAL INFRASTRUCTURE AND SERVICES,1.0
16733,ZW,2021,WATER SUPPLY AND SANITATION,1.0
16734,ZW,2021,Yes,6.0

In [1132]:
chinese_loan = chinese_loan.pivot(index = ['Recipient', 'Implementation Start Year'], columns = 'level_2')

In [1133]:
chinese_loan

                                                      Count  \
level_2                             ACTION RELATING TO DEBT
Recipient Implementation Start Year
AF        2000                                          NaN
          2001                                          NaN
          2002                                          NaN
          2003                                          NaN
          2004                                          1.0
...                                                     ...
ZW        2017                                          NaN
          2018                                          NaN
          2019                                          NaN
          2020                                          NaN
          2021                                          NaN

                                                                    \
level_2                             AGRICULTURE, FORESTRY, FISHING
Recipient Implementation Start Year
AF        2000                                                 NaN
          2001                                                 NaN
          2002                                                 NaN
          2003                                                 NaN
          2004                                                 NaN
...                                                            ...
ZW        2017                                                 1.0
          2018                                                 1.0
          2019                                                 1.0
          2020                                                 NaN
          2021                                                 NaN

                                                                    \
level_2                             BANKING AND FINANCIAL SERVICES
Recipient Implementation Start Year
AF        2000                                                 NaN
          2001                                                 NaN
          2002                                                 NaN
          2003                                                 NaN
          2004                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

                                                                 \
level_2                             BUSINESS AND OTHER SERVICES
Recipient Implementation Start Year
AF        2000                                              NaN
          2001                                              NaN
          2002                                              NaN
          2003                                              NaN
          2004                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

                                                               \
level_2                             COMMUNICATIONS Commercial
Recipient Implementation Start Year
AF        2000                                 NaN        NaN
          2001                                 NaN        NaN
          2002                                 NaN        NaN
          2003                                 NaN        NaN
          2004                                 NaN        NaN
...                                            ...        ...
ZW        2017                                 NaN        NaN
          2018                                 1.0        NaN
          2019                                 NaN        NaN
          2020                                 NaN        NaN
          2021                                 1.0        NaN

                                                                                     \
level_2                             DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE
Recipient Implementation Start Year
AF        2000                                                                  NaN
          2001                                                                  NaN
          2002                                                                  NaN
          2003                                                                  NaN
          2004                                                                  NaN
...                                                                             ...
ZW        2017                                                                  NaN
          2018                                                                  NaN
          2019                                                                  1.0
          2020                                                                  NaN
          2021                                                                  NaN

                                                                          \
level_2                             DISASTER PREVENTION AND PREPAREDNESS
Recipient Implementation Start Year
AF        2000                                                       NaN
          2001                                                       NaN
          2002                                                       NaN
          2003                                                       NaN
          2004                                                       NaN
...                                                                  ...
ZW        2017                                                       NaN
          2018                                                       NaN
          2019                                                       NaN
          2020                                                       NaN
          2021                                                       NaN

                                                           ...  \
level_2                             Development EDUCATION  ...
Recipient Implementation Start Year                        ...
AF        2000                              1.0       NaN  ...
          2001                              1.0       NaN  ...
          2002                              2.0       NaN  ...
          2003                              2.0       1.0  ...
          2004                              4.0       NaN  ...
...                                         ...       ...  ...
ZW        2017                              3.0       NaN  ...
          2018                              4.0       NaN  ...
          2019                              7.0       NaN  ...
          2020                             11.0       NaN  ...
          2021                             10.0       1.0  ...

                                                                              \
level_2                             OTHER SOCIAL INFRASTRUCTURE AND SERVICES
Recipient Implementation Start Year
AF        2000                                                           NaN
          2001                                                           NaN
          2002                                                           NaN
          2003                                                           NaN
          2004                                                           NaN
...                                                                      ...
ZW        2017                                                           NaN
          2018                                                           NaN
          2019                                                           1.0
          2020                                                           NaN
          2021                                                           1.0

                                                                                            \
level_2                             POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH
Recipient Implementation Start Year
AF        2000                                                                     NaN
          2001                                                                     NaN
          2002                                                                     NaN
          2003                                                                     NaN
          2004                                                                     NaN
...                                                                                ...
ZW        2017                                                                     NaN
          2018                                                                     NaN
          2019                                                                     NaN
          2020                                                                     NaN
          2021                                                                     NaN

                                                                              \
level_2                             RECONSTRUCTION RELIEF AND REHABILITATION
Recipient Implementation Start Year
AF        2000                                                           NaN
          2001                                                           NaN
          2002                                                           NaN
          2003                                                           NaN
          2004                                                           NaN
...                                                                      ...
ZW        2017                                                           NaN
          2018                                                           NaN
          2019                                                           NaN
          2020                                                           NaN
          2021                                                           NaN

                                                      \
level_2                             Representational
Recipient Implementation Start Year
AF        2000                                   NaN
          2001                                   NaN
          2002                                   NaN
          2003                                   NaN
          2004                                   NaN
...                                              ...
ZW        2017                                   NaN
          2018                                   NaN
          2019                                   NaN
          2020                                   NaN
          2021                                   NaN

                                                                    \
level_2                             TRADE POLICIES AND REGULATIONS
Recipient Implementation Start Year
AF        2000                                                 NaN
          2001                                                 NaN
          2002                                                 NaN
          2003                                                 NaN
          2004                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

                                                           \
level_2                             TRANSPORT AND STORAGE
Recipient Implementation Start Year
AF        2000                                        NaN
          2001                                        NaN
          2002                                        NaN
          2003                                        NaN
          2004                                        NaN
...                                                   ...
ZW        2017                                        NaN
          2018                                        1.0
          2019                                        NaN
          2020                                        NaN
          2021                                        NaN

                                                                   \
level_2                             UNALLOCATED/UNSPECIFIED Vague
Recipient Implementation Start Year
AF        2000                                          NaN   NaN
          2001                                          NaN   NaN
          2002                                          NaN   NaN
          2003                                          NaN   NaN
          2004                                          NaN   NaN
...                                                     ...   ...
ZW        2017                                          NaN   NaN
          2018                                          NaN   NaN
          2019                                          NaN   NaN
          2020                                          NaN   NaN
          2021                                          NaN   NaN


level_2                             WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2000                                              NaN   NaN
          2001                                              NaN   NaN
          2002                                              NaN   NaN
          2003                                              NaN   NaN
          2004                                              1.0   NaN
...                                                         ...   ...
ZW        2017                                              NaN   NaN
          2018                                              NaN   NaN
          2019                                              NaN   NaN
          2020                                              NaN  11.0
          2021                                              1.0   6.0

[1901 rows x 36 columns]

In [1134]:
chinese_loan.columns = chinese_loan.columns.droplevel(level = 0)

In [1135]:
chinese_loan

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2000                                           NaN
          2001                                           NaN
          2002                                           NaN
          2003                                           NaN
          2004                                           1.0
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

level_2                              BANKING AND FINANCIAL SERVICES  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              BUSINESS AND OTHER SERVICES  \
Recipient Implementation Start Year
AF        2000                                               NaN
          2001                                               NaN
          2002                                               NaN
          2003                                               NaN
          2004                                               NaN
...                                                          ...
ZW        2017                                               NaN
          2018                                               NaN
          2019                                               NaN
          2020                                               NaN
          2021                                               NaN

level_2                              COMMUNICATIONS  Commercial  \
Recipient Implementation Start Year
AF        2000                                  NaN         NaN
          2001                                  NaN         NaN
          2002                                  NaN         NaN
          2003                                  NaN         NaN
          2004                                  NaN         NaN
...                                             ...         ...
ZW        2017                                  NaN         NaN
          2018                                  1.0         NaN
          2019                                  NaN         NaN
          2020                                  NaN         NaN
          2021                                  1.0         NaN

level_2                              DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE  \
Recipient Implementation Start Year
AF        2000                                                                   NaN
          2001                                                                   NaN
          2002                                                                   NaN
          2003                                                                   NaN
          2004                                                                   NaN
...                                                                              ...
ZW        2017                                                                   NaN
          2018                                                                   NaN
          2019                                                                   1.0
          2020                                                                   NaN
          2021                                                                   NaN

level_2                              DISASTER PREVENTION AND PREPAREDNESS  \
Recipient Implementation Start Year
AF        2000                                                        NaN
          2001                                                        NaN
          2002                                                        NaN
          2003                                                        NaN
          2004                                                        NaN
...                                                                   ...
ZW        2017                                                        NaN
          2018                                                        NaN
          2019                                                        NaN
          2020                                                        NaN
          2021                                                        NaN

level_2                              Development  EDUCATION  ...  \
Recipient Implementation Start Year                          ...
AF        2000                               1.0        NaN  ...
          2001                               1.0        NaN  ...
          2002                               2.0        NaN  ...
          2003                               2.0        1.0  ...
          2004                               4.0        NaN  ...
...                                          ...        ...  ...
ZW        2017                               3.0        NaN  ...
          2018                               4.0        NaN  ...
          2019                               7.0        NaN  ...
          2020                              11.0        NaN  ...
          2021                              10.0        1.0  ...

level_2                              OTHER SOCIAL INFRASTRUCTURE AND SERVICES  \
Recipient Implementation Start Year
AF        2000                                                            NaN
          2001                                                            NaN
          2002                                                            NaN
          2003                                                            NaN
          2004                                                            NaN
...                                                                       ...
ZW        2017                                                            NaN
          2018                                                            NaN
          2019                                                            1.0
          2020                                                            NaN
          2021                                                            1.0

level_2                              POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH  \
Recipient Implementation Start Year
AF        2000                                                                     NaN
          2001                                                                     NaN
          2002                                                                     NaN
          2003                                                                     NaN
          2004                                                                     NaN
...                                                                                ...
ZW        2017                                                                     NaN
          2018                                                                     NaN
          2019                                                                     NaN
          2020                                                                     NaN
          2021                                                                     NaN

level_2                              RECONSTRUCTION RELIEF AND REHABILITATION  \
Recipient Implementation Start Year
AF        2000                                                            NaN
          2001                                                            NaN
          2002                                                            NaN
          2003                                                            NaN
          2004                                                            NaN
...                                                                       ...
ZW        2017                                                            NaN
          2018                                                            NaN
          2019                                                            NaN
          2020                                                            NaN
          2021                                                            NaN

level_2                              Representational  \
Recipient Implementation Start Year
AF        2000                                    NaN
          2001                                    NaN
          2002                                    NaN
          2003                                    NaN
          2004                                    NaN
...                                               ...
ZW        2017                                    NaN
          2018                                    NaN
          2019                                    NaN
          2020                                    NaN
          2021                                    NaN

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2000                                         NaN
          2001                                         NaN
          2002                                         NaN
          2003                                         NaN
          2004                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

level_2                              UNALLOCATED/UNSPECIFIED  Vague  \
Recipient Implementation Start Year
AF        2000                                           NaN    NaN
          2001                                           NaN    NaN
          2002                                           NaN    NaN
          2003                                           NaN    NaN
          2004                                           NaN    NaN
...                                                      ...    ...
ZW        2017                                           NaN    NaN
          2018                                           NaN    NaN
          2019                                           NaN    NaN
          2020                                           NaN    NaN
          2021                                           NaN    NaN

level_2                              WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2000                                               NaN   NaN
          2001                                               NaN   NaN
          2002                                               NaN   NaN
          2003                                               NaN   NaN
          2004                                               1.0   NaN
...                                                          ...   ...
ZW        2017                                               NaN   NaN
          2018                                               NaN   NaN
          2019                                               NaN   NaN
          2020                                               NaN  11.0
          2021                                               1.0   6.0

[1901 rows x 36 columns]

In [1136]:
chinese_loan

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2000                                           NaN
          2001                                           NaN
          2002                                           NaN
          2003                                           NaN
          2004                                           1.0
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

level_2                              BANKING AND FINANCIAL SERVICES  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              BUSINESS AND OTHER SERVICES  \
Recipient Implementation Start Year
AF        2000                                               NaN
          2001                                               NaN
          2002                                               NaN
          2003                                               NaN
          2004                                               NaN
...                                                          ...
ZW        2017                                               NaN
          2018                                               NaN
          2019                                               NaN
          2020                                               NaN
          2021                                               NaN

level_2                              COMMUNICATIONS  Commercial  \
Recipient Implementation Start Year
AF        2000                                  NaN         NaN
          2001                                  NaN         NaN
          2002                                  NaN         NaN
          2003                                  NaN         NaN
          2004                                  NaN         NaN
...                                             ...         ...
ZW        2017                                  NaN         NaN
          2018                                  1.0         NaN
          2019                                  NaN         NaN
          2020                                  NaN         NaN
          2021                                  1.0         NaN

level_2                              DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE  \
Recipient Implementation Start Year
AF        2000                                                                   NaN
          2001                                                                   NaN
          2002                                                                   NaN
          2003                                                                   NaN
          2004                                                                   NaN
...                                                                              ...
ZW        2017                                                                   NaN
          2018                                                                   NaN
          2019                                                                   1.0
          2020                                                                   NaN
          2021                                                                   NaN

level_2                              DISASTER PREVENTION AND PREPAREDNESS  \
Recipient Implementation Start Year
AF        2000                                                        NaN
          2001                                                        NaN
          2002                                                        NaN
          2003                                                        NaN
          2004                                                        NaN
...                                                                   ...
ZW        2017                                                        NaN
          2018                                                        NaN
          2019                                                        NaN
          2020                                                        NaN
          2021                                                        NaN

level_2                              Development  EDUCATION  ...  \
Recipient Implementation Start Year                          ...
AF        2000                               1.0        NaN  ...
          2001                               1.0        NaN  ...
          2002                               2.0        NaN  ...
          2003                               2.0        1.0  ...
          2004                               4.0        NaN  ...
...                                          ...        ...  ...
ZW        2017                               3.0        NaN  ...
          2018                               4.0        NaN  ...
          2019                               7.0        NaN  ...
          2020                              11.0        NaN  ...
          2021                              10.0        1.0  ...

level_2                              OTHER SOCIAL INFRASTRUCTURE AND SERVICES  \
Recipient Implementation Start Year
AF        2000                                                            NaN
          2001                                                            NaN
          2002                                                            NaN
          2003                                                            NaN
          2004                                                            NaN
...                                                                       ...
ZW        2017                                                            NaN
          2018                                                            NaN
          2019                                                            1.0
          2020                                                            NaN
          2021                                                            1.0

level_2                              POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH  \
Recipient Implementation Start Year
AF        2000                                                                     NaN
          2001                                                                     NaN
          2002                                                                     NaN
          2003                                                                     NaN
          2004                                                                     NaN
...                                                                                ...
ZW        2017                                                                     NaN
          2018                                                                     NaN
          2019                                                                     NaN
          2020                                                                     NaN
          2021                                                                     NaN

level_2                              RECONSTRUCTION RELIEF AND REHABILITATION  \
Recipient Implementation Start Year
AF        2000                                                            NaN
          2001                                                            NaN
          2002                                                            NaN
          2003                                                            NaN
          2004                                                            NaN
...                                                                       ...
ZW        2017                                                            NaN
          2018                                                            NaN
          2019                                                            NaN
          2020                                                            NaN
          2021                                                            NaN

level_2                              Representational  \
Recipient Implementation Start Year
AF        2000                                    NaN
          2001                                    NaN
          2002                                    NaN
          2003                                    NaN
          2004                                    NaN
...                                               ...
ZW        2017                                    NaN
          2018                                    NaN
          2019                                    NaN
          2020                                    NaN
          2021                                    NaN

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2000                                         NaN
          2001                                         NaN
          2002                                         NaN
          2003                                         NaN
          2004                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

level_2                              UNALLOCATED/UNSPECIFIED  Vague  \
Recipient Implementation Start Year
AF        2000                                           NaN    NaN
          2001                                           NaN    NaN
          2002                                           NaN    NaN
          2003                                           NaN    NaN
          2004                                           NaN    NaN
...                                                      ...    ...
ZW        2017                                           NaN    NaN
          2018                                           NaN    NaN
          2019                                           NaN    NaN
          2020                                           NaN    NaN
          2021                                           NaN    NaN

level_2                              WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2000                                               NaN   NaN
          2001                                               NaN   NaN
          2002                                               NaN   NaN
          2003                                               NaN   NaN
          2004                                               1.0   NaN
...                                                          ...   ...
ZW        2017                                               NaN   NaN
          2018                                               NaN   NaN
          2019                                               NaN   NaN
          2020                                               NaN  11.0
          2021                                               1.0   6.0

[1901 rows x 36 columns]

In [1137]:
new_order = np.concatenate((flows, intents, sectors, covid, amounts))

In [1138]:
new_order

array(['Grant', 'Loan', 'Vague', 'Commercial', 'Development', 'Mixed',
       'Representational', 'ACTION RELATING TO DEBT',
       'AGRICULTURE, FORESTRY, FISHING', 'BANKING AND FINANCIAL SERVICES',
       'BUSINESS AND OTHER SERVICES', 'COMMUNICATIONS',
       'DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE',
       'DISASTER PREVENTION AND PREPAREDNESS', 'EDUCATION',
       'EMERGENCY RESPONSE', 'ENERGY', 'GENERAL BUDGET SUPPORT',
       'GENERAL ENVIRONMENTAL PROTECTION', 'GOVERNMENT AND CIVIL SOCIETY',
       'HEALTH', 'INDUSTRY, MINING, CONSTRUCTION',
       'OTHER COMMODITY ASSISTANCE', 'OTHER MULTISECTOR',
       'OTHER SOCIAL INFRASTRUCTURE AND SERVICES',
       'POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH',
       'RECONSTRUCTION RELIEF AND REHABILITATION',
       'TRADE POLICIES AND REGULATIONS', 'TRANSPORT AND STORAGE',
       'UNALLOCATED/UNSPECIFIED', 'WATER SUPPLY AND SANITATION', 'No',
       'Yes', 'High', 'Low', 'Medium'], dtype=object)

In [1139]:
chinese_loan = chinese_loan[new_order]
chinese_loan

level_2                              Grant  Loan  Vague  Commercial  \
Recipient Implementation Start Year
AF        2000                         1.0   NaN    NaN         NaN
          2001                         1.0   NaN    NaN         NaN
          2002                         2.0   NaN    NaN         NaN
          2003                         2.0   NaN    NaN         NaN
          2004                         4.0   NaN    NaN         NaN
...                                    ...   ...    ...         ...
ZW        2017                         3.0   NaN    NaN         NaN
          2018                         3.0   2.0    NaN         NaN
          2019                         7.0   NaN    NaN         NaN
          2020                        11.0   NaN    NaN         NaN
          2021                         8.0   2.0    NaN         NaN

level_2                              Development  Mixed  Representational  \
Recipient Implementation Start Year
AF        2000                               1.0    NaN               NaN
          2001                               1.0    NaN               NaN
          2002                               2.0    NaN               NaN
          2003                               2.0    NaN               NaN
          2004                               4.0    NaN               NaN
...                                          ...    ...               ...
ZW        2017                               3.0    NaN               NaN
          2018                               4.0    1.0               NaN
          2019                               7.0    NaN               NaN
          2020                              11.0    NaN               NaN
          2021                              10.0    NaN               NaN

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2000                                           NaN
          2001                                           NaN
          2002                                           NaN
          2003                                           NaN
          2004                                           1.0
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

level_2                              BANKING AND FINANCIAL SERVICES  ...  \
Recipient Implementation Start Year                                  ...
AF        2000                                                  NaN  ...
          2001                                                  NaN  ...
          2002                                                  NaN  ...
          2003                                                  NaN  ...
          2004                                                  NaN  ...
...                                                             ...  ...
ZW        2017                                                  NaN  ...
          2018                                                  NaN  ...
          2019                                                  NaN  ...
          2020                                                  NaN  ...
          2021                                                  NaN  ...

level_2                              RECONSTRUCTION RELIEF AND REHABILITATION  \
Recipient Implementation Start Year
AF        2000                                                            NaN
          2001                                                            NaN
          2002                                                            NaN
          2003                                                            NaN
          2004                                                            NaN
...                                                                       ...
ZW        2017                                                            NaN
          2018                                                            NaN
          2019                                                            NaN
          2020                                                            NaN
          2021                                                            NaN

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2000                                                  NaN
          2001                                                  NaN
          2002                                                  NaN
          2003                                                  NaN
          2004                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2000                                         NaN
          2001                                         NaN
          2002                                         NaN
          2003                                         NaN
          2004                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

level_2                              UNALLOCATED/UNSPECIFIED  \
Recipient Implementation Start Year
AF        2000                                           NaN
          2001                                           NaN
          2002                                           NaN
          2003                                           NaN
          2004                                           NaN
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              WATER SUPPLY AND SANITATION   No   Yes  \
Recipient Implementation Start Year
AF        2000                                               NaN  1.0   NaN
          2001                                               NaN  1.0   NaN
          2002                                               NaN  2.0   NaN
          2003                                               NaN  2.0   NaN
          2004                                               1.0  4.0   NaN
...                                                          ...  ...   ...
ZW        2017                                               NaN  3.0   NaN
          2018                                               NaN  5.0   NaN
          2019                                               NaN  7.0   NaN
          2020                                               NaN  NaN  11.0
          2021                                               1.0  4.0   6.0

level_2                              High   Low  Medium
Recipient Implementation Start Year
AF        2000                        0.0   1.0     0.0
          2001                        0.0   1.0     0.0
          2002                        0.0   0.0     2.0
          2003                        0.0   1.0     1.0
          2004                        0.0   0.0     4.0
...                                   ...   ...     ...
ZW        2017                        0.0   2.0     1.0
          2018                        3.0   0.0     2.0
          2019                        1.0   3.0     3.0
          2020                        0.0  11.0     0.0
          2021                        2.0   3.0     5.0

[1901 rows x 36 columns]

In [1140]:
chinese_loan.fillna(0, inplace = True)
chinese_loan

level_2                              Grant  Loan  Vague  Commercial  \
Recipient Implementation Start Year
AF        2000                         1.0   0.0    0.0         0.0
          2001                         1.0   0.0    0.0         0.0
          2002                         2.0   0.0    0.0         0.0
          2003                         2.0   0.0    0.0         0.0
          2004                         4.0   0.0    0.0         0.0
...                                    ...   ...    ...         ...
ZW        2017                         3.0   0.0    0.0         0.0
          2018                         3.0   2.0    0.0         0.0
          2019                         7.0   0.0    0.0         0.0
          2020                        11.0   0.0    0.0         0.0
          2021                         8.0   2.0    0.0         0.0

level_2                              Development  Mixed  Representational  \
Recipient Implementation Start Year
AF        2000                               1.0    0.0               0.0
          2001                               1.0    0.0               0.0
          2002                               2.0    0.0               0.0
          2003                               2.0    0.0               0.0
          2004                               4.0    0.0               0.0
...                                          ...    ...               ...
ZW        2017                               3.0    0.0               0.0
          2018                               4.0    1.0               0.0
          2019                               7.0    0.0               0.0
          2020                              11.0    0.0               0.0
          2021                              10.0    0.0               0.0

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2000                                           0.0
          2001                                           0.0
          2002                                           0.0
          2003                                           0.0
          2004                                           1.0
...                                                      ...
ZW        2017                                           0.0
          2018                                           0.0
          2019                                           0.0
          2020                                           0.0
          2021                                           0.0

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2000                                                  0.0
          2001                                                  0.0
          2002                                                  0.0
          2003                                                  0.0
          2004                                                  0.0
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  0.0
          2021                                                  0.0

level_2                              BANKING AND FINANCIAL SERVICES  ...  \
Recipient Implementation Start Year                                  ...
AF        2000                                                  0.0  ...
          2001                                                  0.0  ...
          2002                                                  0.0  ...
          2003                                                  0.0  ...
          2004                                                  0.0  ...
...                                                             ...  ...
ZW        2017                                                  0.0  ...
          2018                                                  0.0  ...
          2019                                                  0.0  ...
          2020                                                  0.0  ...
          2021                                                  0.0  ...

level_2                              RECONSTRUCTION RELIEF AND REHABILITATION  \
Recipient Implementation Start Year
AF        2000                                                            0.0
          2001                                                            0.0
          2002                                                            0.0
          2003                                                            0.0
          2004                                                            0.0
...                                                                       ...
ZW        2017                                                            0.0
          2018                                                            0.0
          2019                                                            0.0
          2020                                                            0.0
          2021                                                            0.0

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2000                                                  0.0
          2001                                                  0.0
          2002                                                  0.0
          2003                                                  0.0
          2004                                                  0.0
...                                                             ...
ZW        2017                                                  0.0
          2018                                                  0.0
          2019                                                  0.0
          2020                                                  0.0
          2021                                                  0.0

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2000                                         0.0
          2001                                         0.0
          2002                                         0.0
          2003                                         0.0
          2004                                         0.0
...                                                    ...
ZW        2017                                         0.0
          2018                                         1.0
          2019                                         0.0
          2020                                         0.0
          2021                                         0.0

level_2                              UNALLOCATED/UNSPECIFIED  \
Recipient Implementation Start Year
AF        2000                                           0.0
          2001                                           0.0
          2002                                           0.0
          2003                                           0.0
          2004                                           0.0
...                                                      ...
ZW        2017                                           0.0
          2018                                           0.0
          2019                                           0.0
          2020                                           0.0
          2021                                           0.0

level_2                              WATER SUPPLY AND SANITATION   No   Yes  \
Recipient Implementation Start Year
AF        2000                                               0.0  1.0   0.0
          2001                                               0.0  1.0   0.0
          2002                                               0.0  2.0   0.0
          2003                                               0.0  2.0   0.0
          2004                                               1.0  4.0   0.0
...                                                          ...  ...   ...
ZW        2017                                               0.0  3.0   0.0
          2018                                               0.0  5.0   0.0
          2019                                               0.0  7.0   0.0
          2020                                               0.0  0.0  11.0
          2021                                               1.0  4.0   6.0

level_2                              High   Low  Medium
Recipient Implementation Start Year
AF        2000                        0.0   1.0     0.0
          2001                        0.0   1.0     0.0
          2002                        0.0   0.0     2.0
          2003                        0.0   1.0     1.0
          2004                        0.0   0.0     4.0
...                                   ...   ...     ...
ZW        2017                        0.0   2.0     1.0
          2018                        3.0   0.0     2.0
          2019                        1.0   3.0     3.0
          2020                        0.0  11.0     0.0
          2021                        2.0   3.0     5.0

[1901 rows x 36 columns]

In [1141]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
Country,Year,,
AF,1950,NaN,NaN
AL,1950,NaN,NaN
DZ,1950,NaN,NaN
AO,1950,NaN,NaN
AG,1950,NaN,NaN
...,...,...,...
PH,2022,NaN,57.519704
TJ,2022,NaN,34.631164
TZ,2022,NaN,41.622404
AE,2022,NaN,29.95788
UZ,2022,NaN,34.294587

In [1142]:
loan_debt_data.reset_index(inplace = True)

In [1143]:
loan_debt_data["Year"] = pd.to_numeric(loan_debt_data["Year"])

In [1144]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
0,AF,1950,NaN,NaN
1,AL,1950,NaN,NaN
2,DZ,1950,NaN,NaN
3,AO,1950,NaN,NaN
4,AG,1950,NaN,NaN
...,...,...,...,...
13792,PH,2022,NaN,57.519704
13793,TJ,2022,NaN,34.631164
13794,TZ,2022,NaN,41.622404
13795,AE,2022,NaN,29.95788
13796,UZ,2022,NaN,34.294587

In [1145]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] >= 2000]

In [1146]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [1147]:
chinese_loan.reset_index(inplace = True)
chinese_loan

level_2,Recipient,Implementation Start Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
0,AF,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,AF,2001,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,AF,2002,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0
3,AF,2003,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,1.0
4,AF,2004,4.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,ZW,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,1.0
1897,ZW,2018,3.0,2.0,0.0,0.0,4.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,5.0,0.0,3.0,0.0,2.0
1898,ZW,2019,7.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,3.0,3.0
1899,ZW,2020,11.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,11.0,0.0
1900,ZW,2021,8.0,2.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,4.0,6.0,2.0,3.0,5.0

In [1148]:
chinese_loan = chinese_loan.rename({"Implementation Start Year": "Year", "Recipient": "Country"}, axis = 1)

In [1149]:
chinese_loan

level_2,Country,Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
0,AF,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,AF,2001,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,AF,2002,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0
3,AF,2003,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,1.0
4,AF,2004,4.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,ZW,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,1.0
1897,ZW,2018,3.0,2.0,0.0,0.0,4.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,5.0,0.0,3.0,0.0,2.0
1898,ZW,2019,7.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,3.0,3.0
1899,ZW,2020,11.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,11.0,0.0
1900,ZW,2021,8.0,2.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,4.0,6.0,2.0,3.0,5.0

In [1150]:
chinese_loan.sort_values(["Year", "Country"], inplace = True)
chinese_loan

level_2,Country,Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
1757,UZ,1996,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
496,ET,1998,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1052,MM,1998,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,1.0
833,KM,1999,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
0,AF,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,TR,2022,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0
1820,VU,2022,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0
1878,ZM,2022,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
326,CI,2023,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
607,GH,2023,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1151]:
chinese_loan = chinese_loan[chinese_loan["Year"] >= 2000]

In [1152]:
chinese_loan.set_index(["Country", "Year"], inplace = True)

In [1153]:
chinese_loan

,level_2,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,"AGRICULTURE, FORESTRY, FISHING",BANKING AND FINANCIAL SERVICES,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
AL,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
BJ,2000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
CD,2000,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0
ER,2000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TR,2022,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0
VU,2022,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0
ZM,2022,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
CI,2023,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
GH,2023,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1154]:
loan_debt_data = pd.concat([loan_debt_data, chinese_loan], axis = 1, join = "outer")

In [1155]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
DZ,2000,57.96034348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,2000,133.9141396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,2000,105.1323732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,3.0
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,3.0
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1156]:
loan_debt_data[new_order] = loan_debt_data[new_order].fillna(0)

In [1157]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
DZ,2000,57.96034348,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AO,2000,133.9141396,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AG,2000,105.1323732,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,3.0
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,3.0
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1158]:
loan_debt_data.fillna("Not Available", inplace = True)

In [1159]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
DZ,2000,57.96034348,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AO,2000,133.9141396,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AG,2000,105.1323732,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
CU,2021,Not Available,Not Available,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,3.0
SO,2021,Not Available,Not Available,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,3.0
CI,2023,Not Available,Not Available,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
GH,2023,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1160]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,RECONSTRUCTION RELIEF AND REHABILITATION,TRADE POLICIES AND REGULATIONS,TRANSPORT AND STORAGE,UNALLOCATED/UNSPECIFIED,WATER SUPPLY AND SANITATION,No,Yes,High,Low,Medium
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
DZ,2000,57.96034348,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AO,2000,133.9141396,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AG,2000,105.1323732,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
CU,2021,Not Available,Not Available,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,3.0
SO,2021,Not Available,Not Available,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,3.0
CI,2023,Not Available,Not Available,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
GH,2023,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [1161]:
aei_data = pd.read_csv("Data/AEI-Data.csv", skiprows = 5)

In [1162]:
aei_data.columns

Index(['Year', 'Month', 'Investor', ' Quantity in Millions ', 'Share Size',
       'Transaction Party', 'Sector', 'Subsector', 'Country', 'Region', 'BRI',
       'Greenfield', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')

In [1163]:
aei_data = aei_data[["Country", "Year", "Investor","Sector", "Subsector", " Quantity in Millions "]]

In [1164]:
aei_data

,Country,Year,Investor,Sector,Subsector,Quantity in Millions
0,Cuba,2005,Minmetals,Metals,NaN,$500
1,USA,2005,Chinese Academy of Sciences,Technology,NaN,"$1,740"
2,Qatar,2005,Sinohydro,Transport,Aviation,$100
3,Oman,2005,Sinohydro,Utilities,NaN,$150
4,Ecuador,2005,Sinohydro,Transport,Autos,$370
...,...,...,...,...,...,...
4293,Guinea,2023,Power Construction Corp. (PowerChina),Metals,Aluminum,$110
4294,Saudi Arabia,2023,Power Construction Corp. (PowerChina),Energy,Alternative,$410
4295,Saudi Arabia,2023,China National Chemical Engineering,Chemicals,NaN,$270
4296,Nigeria,2023,China National Building Material,Real estate,Construction,$590
4297,Algeria,2023,China National Petroleum Corp. (CNPC),Chemicals,NaN,$440

In [1165]:
aei_data = aei_data.replace(name_to_alpha_2)

In [1166]:
aei_data[ " Quantity in Millions "] = aei_data[ " Quantity in Millions "].apply(lambda x: x[2:len(x)-1])
aei_data[ " Quantity in Millions "] = aei_data[ " Quantity in Millions "].apply(lambda x: x.replace(",", ""))

In [1167]:
aei_data = aei_data.rename({ " Quantity in Millions ": "Quantity in Millions"}, axis = 1)

In [1168]:
aei_data["Quantity in Millions"] = pd.to_numeric(aei_data["Quantity in Millions"], downcast = 'float')

In [1169]:
aei_data["Quantity in Millions"] = pd.qcut(aei_data["Quantity in Millions"], q = 3, labels = ["Low", "Medium", "High"])

In [1170]:
aei_data

,Country,Year,Investor,Sector,Subsector,Quantity in Millions
0,CU,2005,Minmetals,Metals,NaN,High
1,US,2005,Chinese Academy of Sciences,Technology,NaN,High
2,QA,2005,Sinohydro,Transport,Aviation,Low
3,OM,2005,Sinohydro,Utilities,NaN,Low
4,EC,2005,Sinohydro,Transport,Autos,Medium
...,...,...,...,...,...,...
4293,GN,2023,Power Construction Corp. (PowerChina),Metals,Aluminum,Low
4294,SA,2023,Power Construction Corp. (PowerChina),Energy,Alternative,Medium
4295,SA,2023,China National Chemical Engineering,Chemicals,NaN,Medium
4296,NG,2023,China National Building Material,Real estate,Construction,High
4297,DZ,2023,China National Petroleum Corp. (CNPC),Chemicals,NaN,High

In [1171]:
aei_data.set_index(["Country", "Year"], inplace = True)

In [1172]:
aei_data

                                           Investor       Sector  \
Country Year
CU      2005                              Minmetals       Metals
US      2005            Chinese Academy of Sciences   Technology
QA      2005                              Sinohydro    Transport
OM      2005                              Sinohydro    Utilities
EC      2005                              Sinohydro    Transport
...                                             ...          ...
GN      2023  Power Construction Corp. (PowerChina)       Metals
SA      2023  Power Construction Corp. (PowerChina)       Energy
        2023    China National Chemical Engineering    Chemicals
NG      2023       China National Building Material  Real estate
DZ      2023  China National Petroleum Corp. (CNPC)    Chemicals

                 Subsector Quantity in Millions
Country Year
CU      2005           NaN                 High
US      2005           NaN                 High
QA      2005      Aviation                  Low
OM      2005           NaN                  Low
EC      2005         Autos               Medium
...                    ...                  ...
GN      2023      Aluminum                  Low
SA      2023   Alternative               Medium
        2023           NaN               Medium
NG      2023  Construction                 High
DZ      2023           NaN                 High

[4298 rows x 4 columns]

In [1173]:
aei_data = aei_data.apply(lambda x: x.apply(lambda y: y + "-AEI" if isinstance(y, str) else None), axis = 1)

In [1174]:
aei_data

                                               Investor           Sector  \
Country Year
CU      2005                              Minmetals-AEI       Metals-AEI
US      2005            Chinese Academy of Sciences-AEI   Technology-AEI
QA      2005                              Sinohydro-AEI    Transport-AEI
OM      2005                              Sinohydro-AEI    Utilities-AEI
EC      2005                              Sinohydro-AEI    Transport-AEI
...                                                 ...              ...
GN      2023  Power Construction Corp. (PowerChina)-AEI       Metals-AEI
SA      2023  Power Construction Corp. (PowerChina)-AEI       Energy-AEI
        2023    China National Chemical Engineering-AEI    Chemicals-AEI
NG      2023       China National Building Material-AEI  Real estate-AEI
DZ      2023  China National Petroleum Corp. (CNPC)-AEI    Chemicals-AEI

                     Subsector Quantity in Millions
Country Year
CU      2005              None             High-AEI
US      2005              None             High-AEI
QA      2005      Aviation-AEI              Low-AEI
OM      2005              None              Low-AEI
EC      2005         Autos-AEI           Medium-AEI
...                        ...                  ...
GN      2023      Aluminum-AEI              Low-AEI
SA      2023   Alternative-AEI           Medium-AEI
        2023              None           Medium-AEI
NG      2023  Construction-AEI             High-AEI
DZ      2023              None             High-AEI

[4298 rows x 4 columns]

In [1175]:
investors = aei_data["Investor"].unique()
sectors = aei_data["Sector"].unique()
subsectors = aei_data["Subsector"].unique()[1:]
quantities = aei_data["Quantity in Millions"].unique() 

new_order = np.concatenate([investors, sectors, subsectors, quantities])

In [1176]:
aei_data.reset_index(inplace = True)

In [1177]:
aei_data = aei_data.groupby(['Country', 'Year']).apply(lambda x: x.drop(['Country', 'Year'], axis = 1)
                                                                                                       .apply(pd.Series.value_counts))

In [1178]:
aei_data

                                                 Investor  Sector  Subsector  \
Country Year
AE      2006 Construction-AEI                         NaN     NaN        1.0
             Medium-AEI                               NaN     NaN        NaN
             Real estate-AEI                          NaN     1.0        NaN
             State Construction Engineering-AEI       1.0     NaN        NaN
        2007 Autos-AEI                                NaN     NaN        1.0
...                                                   ...     ...        ...
ZW      2022 Tsingshan-AEI                            1.0     NaN        NaN
             Zhejiang Huayou Cobalt-AEI               1.0     NaN        NaN
        2023 Feishang Group-AEI                       1.0     NaN        NaN
             Low-AEI                                  NaN     NaN        NaN
             Metals-AEI                               NaN     1.0        NaN

                                                 Quantity in Millions
Country Year
AE      2006 Construction-AEI                                     NaN
             Medium-AEI                                           1.0
             Real estate-AEI                                      NaN
             State Construction Engineering-AEI                   NaN
        2007 Autos-AEI                                            NaN
...                                                               ...
ZW      2022 Tsingshan-AEI                                        NaN
             Zhejiang Huayou Cobalt-AEI                           NaN
        2023 Feishang Group-AEI                                   NaN
             Low-AEI                                              1.0
             Metals-AEI                                           NaN

[11194 rows x 4 columns]

In [1179]:
count = aei_data.apply(lambda x: return_not_na(x), axis = 1)

In [1180]:
aei_data = aei_data.drop(aei_data.columns, axis = 1)

In [1181]:
aei_data["Count"] = count

In [1182]:
aei_data

                                                 Count
Country Year
AE      2006 Construction-AEI                      1.0
             Medium-AEI                            1.0
             Real estate-AEI                       1.0
             State Construction Engineering-AEI    1.0
        2007 Autos-AEI                             1.0
...                                                ...
ZW      2022 Tsingshan-AEI                         1.0
             Zhejiang Huayou Cobalt-AEI            1.0
        2023 Feishang Group-AEI                    1.0
             Low-AEI                               1.0
             Metals-AEI                            1.0

[11194 rows x 1 columns]

In [1183]:
aei_data.reset_index(inplace = True)

In [1184]:
aei_data = aei_data.pivot(index = ['Country', 'Year'], columns = 'level_2')

In [1185]:
aei_data

                                                                   Count  \
level_2      3SBio, China International Trust and Investment (CITIC)-AEI
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

                                                                               \
level_2      AAC-AEI Agile Property-AEI Agriculture-AEI Aier Eye Hospital-AEI
Country Year
AE      2006     NaN                NaN             NaN                   NaN
        2007     NaN                NaN             NaN                   NaN
        2008     NaN                NaN             NaN                   NaN
        2009     NaN                NaN             NaN                   NaN
        2010     NaN                NaN             1.0                   NaN
...              ...                ...             ...                   ...
ZW      2019     NaN                NaN             NaN                   NaN
        2020     NaN                NaN             NaN                   NaN
        2021     NaN                NaN             NaN                   NaN
        2022     NaN                NaN             NaN                   NaN
        2023     NaN                NaN             NaN                   NaN

                                          \
level_2      Alibaba-AEI Alternative-AEI
Country Year
AE      2006         NaN             NaN
        2007         NaN             NaN
        2008         NaN             NaN
        2009         NaN             NaN
        2010         NaN             NaN
...                  ...             ...
ZW      2019         NaN             1.0
        2020         NaN             NaN
        2021         NaN             NaN
        2022         NaN             NaN
        2023         NaN             NaN

                                                                        \
level_2      Aluminum Corporation of China (Chinalco)-AEI Aluminum-AEI
Country Year
AE      2006                                          NaN          NaN
        2007                                          NaN          NaN
        2008                                          NaN          NaN
        2009                                          NaN          NaN
        2010                                          NaN          NaN
...                                                   ...          ...
ZW      2019                                          NaN          NaN
        2020                                          NaN          NaN
        2021                                          NaN          NaN
        2022                                          NaN          NaN
        2023                                          NaN          NaN

                         ...                   \
level_2      Anbang-AEI  ... Zhuhai Huafa-AEI
Country Year             ...
AE      2006        NaN  ...              NaN
        2007        NaN  ...              NaN
        2008        NaN  ...              NaN
        2009        NaN  ...              NaN
        2010        NaN  ...              NaN
...                 ...  ...              ...
ZW      2019        NaN  ...              NaN
        2020        NaN  ...              NaN
        2021        NaN  ...              NaN
        2022        NaN  ...              NaN
        2023        NaN  ...              NaN

                                                                       \
level_2      Zhuhai Port Holdings, State Construction Engineering-AEI
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

                                                     \
level_2      Zhuhai Zhenrong-AEI Zhuzhou Kibing-AEI
Country Year
AE      2006                 NaN                NaN
        2007                 NaN                NaN
        2008                 NaN                NaN
        2009                 NaN                NaN
        2010                 NaN                NaN
...                          ...                ...
ZW      2019                 NaN                NaN
        2020                 NaN                NaN
        2021                 NaN                NaN
        2022                 NaN                NaN
        2023                 NaN                NaN

                                                                              \
level_2      Zijin Mining, China Nonferrous, Xiamen C&D-AEI Zijin Mining-AEI
Country Year
AE      2006                                            NaN              NaN
        2007                                            NaN              NaN
        2008                                            NaN              NaN
        2009                                            NaN              NaN
        2010                                            NaN              NaN
...                                                     ...              ...
ZW      2019                                            NaN              NaN
        2020                                            NaN              NaN
        2021                                            NaN              NaN
        2022                                            NaN              NaN
        2023                                            NaN              NaN


level_2      Zongshen Industrial-AEI Zoomlion-AEI iCarbonX-AEI xFusion-AEI
Country Year
AE      2006                     NaN          NaN          NaN         NaN
        2007                     NaN          NaN          NaN         NaN
        2008                     NaN          NaN          NaN         NaN
        2009                     NaN          NaN          NaN         NaN
        2010                     NaN          NaN          NaN         NaN
...                              ...          ...          ...         ...
ZW      2019                     NaN          NaN          NaN         NaN
        2020                     NaN          NaN          NaN         NaN
        2021                     NaN          NaN          NaN         NaN
        2022                     NaN          NaN          NaN         NaN
        2023                     NaN          NaN          NaN         NaN

[1369 rows x 935 columns]

In [1186]:
aei_data.columns = aei_data.columns.droplevel(level = 0)

In [1187]:
new_order

array(['Minmetals-AEI', 'Chinese Academy of Sciences-AEI',
       'Sinohydro-AEI', 'MCC-AEI', 'Sinoma-AEI',
       'China National Off-shore Oil (CNOOC)-AEI',
       'China National Machinery Industry (Sinomach)-AEI',
       'Minmetals, MCC-AEI', 'China National Petroleum Corp. (CNPC)-AEI',
       'China Petroleum and Chemical (Sinopec)-AEI',
       'China National Machinery Industry (Sinomach), Sinohydro-AEI',
       'China Railway Construction, China General Technology (Genertec)-AEI',
       'Jiangsu Yuejin-AEI',
       'China International Trust and Investment (CITIC), Sinohydro-AEI',
       'China National Petroleum Corp. (CNPC), China Petroleum and Chemical (Sinopec)-AEI',
       'China Investment Corporation (CIC), Beijing Jingdeshun-AEI',
       'China National Chemical (ChemChina)-AEI', 'Sinosteel-AEI',
       'China Nonferrous-AEI', 'China Communications Construction-AEI',
       'China North Industries (Norinco)-AEI',
       'China International Trust and Investment (CITIC)-AEI',
       'Zhejiang Holley-AEI',
       'China International Trust and Investment (CITIC), Aluminum Corporation of China (Chinalco)-AEI',
       'China National Nuclear-AEI', 'State Construction Engineering-AEI',
       'Shanghai Municipal Government-AEI',
       'Shandong Electric Power Construction III-AEI',
       'China Power Engineering Consulting-AEI',
       'China International Trust and Investment (CITIC), China Railway Construction-AEI',
       'Tebian Electric Apparatus (TBEA)-AEI',
       'Weihai International Economic-AEI',
       'Jiangsu International Cooperation Corp-AEI',
       'Dongfang Electric-AEI', 'Wuxi Suntech-AEI',
       'ZTE (Zhongxing Telecommunications Equipment), Huawei, China Communications Construction-AEI',
       'Huawei-AEI', 'Jiangxi Copper-AEI', 'China Development Bank-AEI',
       'Ex-Im Bank-AEI', 'Three Gorges-AEI',
       'China National Chemical Engineering-AEI',
       'China General Technology (Genertec)-AEI', 'Sichuan Changhong-AEI',
       'Bank of China-AEI', 'Harbin Electric-AEI', 'Huadian-AEI',
       'Shanghai Electric-AEI', 'China Mobile-AEI',
       'Shandong Electric Power Construction-AEI',
       'Aluminum Corporation of China (Chinalco)-AEI',
       'China Railway Construction-AEI',
       'Zijin Mining, China Nonferrous, Xiamen C&D-AEI',
       'Shanghai Shengong, Shanghai Foreign Economic and Technological Cooperation-AEI',
       'Gezhouba-AEI', 'Sinohydro, China Communications Construction-AEI',
       'China National Machinery Industry (Sinomach), China Nonferrous-AEI',
       'China Investment Corporation (CIC)-AEI',
       'LinkGlobal Logistics-AEI', 'China National Building Material-AEI',
       'China Ocean Shipping (COSCO)-AEI', 'Golden Dragon-AEI',
       'Dongfang Electric, Shanghai Electric-AEI', 'Ansteel-AEI',
       'Sany Heavy Industry-AEI',
       'Industrial and Commercial Bank of China-AEI',
       'Southern Power Grid-AEI', 'China Electronics Corporation-AEI',
       'Ping An-AEI', 'MCC, Jiangxi Copper-AEI', 'Youngor-AEI',
       'Guizhou Hongfu-AEI', 'Minmetals, Jiangxi Copper-AEI',
       'Shenzhen Energy, China Development Bank-AEI',
       'State Administration of Foreign Exchange (SAFE)-AEI',
       'Jinchuan Group-AEI', 'WuXi Pharma-AEI', 'State Grid-AEI',
       'Sinochem-AEI', 'Minmetals, Xinxing Iron-AEI', 'Huaneng Power-AEI',
       'China Life-AEI', 'Mindray Medical-AEI',
       'China Railway Engineering-AEI', 'Hopu Investment-AEI',
       'Sinohydro, Three Gorges-AEI',
       'China National Chemical Engineering, China General Technology (Genertec)-AEI',
       'China National Cereal, Oil and Foodstuffs (COFCO)-AEI',
       'Zoomlion-AEI', 'MCC, Sinohydro-AEI',
       'Guangdong Overseas Construction-AEI',
       'Shanghai Tunnel Engineering-AEI',
       'Jiangsu Shagang, RGL Group-AEI', 'Datong-AEI', 'Shenhua-AEI',
       'Three Gorges-led consortium-AEI',
       'ZTE (Zhongxing Telecommunications Equipment)-AEI',
       'Zhongmei Engineering-AEI', 'Xinjiang Guanghui-AEI',
       'Wuhan Iron and Steel, China Development Bank-AEI', 'Datang-AEI',
       'Union Development-AEI', 'Hunan Valin-AEI', 'Shougang Group-AEI',
       'Wuhan Iron and Steel-AEI', 'Tianjin Pipe-AEI',
       'Jiangsu Taihu-AEI',
       'China National Off-shore Oil (CNOOC), China Petroleum and Chemical (Sinopec)-AEI',
       'HNA-AEI', 'Nanjinzhao-AEI',
       'Guangdong Rising Asset Management-AEI',
       'Haicheng Xiyang Group-AEI', 'Tianjin Development-AEI',
       'Taiyuan Iron, China Development Bank, Shanxi Coking Coal, and Tianli Enterprises-AEI',
       'Shandong Electric Power Construction III, Dongfang Electric-AEI',
       'Yankuang-AEI', 'MCC, China Architecture Design-AEI',
       'China United Network Communications (Unicom)-AEI',
       'BaoWu Steel (Baosteel)-AEI', 'Great Wall-AEI',
       'Jin Jiang International-AEI', 'Beijing Auto (BAIC)-AEI',
       'SAIC Motor (Shanghai Auto)-AEI',
       'Aviation Industry Corp. (AVIC)-AEI', 'China Poly-AEI',
       'China Railway Construction, Tongling Nonferrous-AEI',
       'Baiyin Non-Ferrous, China International Trust and Investment (CITIC), Chang Xin-AEI',
       'Shandong Sun Paper-AEI', 'Jinsheng Trading-AEI',
       'Shunde Rixin, Minmetals-AEI', 'Wuhan Kaidi Electric-AEI',
       'Wanhua Industrial-AEI',
       'Gezhouba, Xinjiang International Cooperation Corp-AEI',
       'East China Mineral Exploration and Development Bureau (Jiangsu)-AEI',
       'Geely-AEI', 'First Auto Works, China Development Bank-AEI',
       'Honbridge Capital-AEI',
       'China National Machinery Industry (Sinomach), Gezhouba-AEI',
       'Sichuan Hanlong-AEI', 'Tencent-AEI',
       'Guangdong Power Engineering-AEI', 'Jiangsu Zongyi-AEI',
       'Jinchuan Group, China Development Bank-AEI',
       'Tangshan Jidong Cement, China Development Bank-AEI',
       'Jiangsu Qiyuan-AEI', 'Tianyu Group-AEI',
       'Rongsheng Holding, China National Chemical Engineering-AEI',
       'Shaanxi Coal and Chemical-AEI', 'Yunnan Metallurgical-AEI',
       'Beijing Construction Engineering-AEI',
       'State Development and Investment Corp.-AEI',
       'Tempo Group, Beijing Municipal Government-AEI',
       'China Merchants-AEI', 'China Machine New Energy-AEI',
       'Inner Mongolia Hongjun-AEI', 'Bosai Minerals-AEI',
       'Shanda Group-AEI', 'Three Gorges, Sinohydro-AEI',
       'Guangxi Road and Bridge-AEI', 'Chongqing Chonggang-AEI',
       'China Merchants, China Development Bank-AEI', 'Taiyuan Heavy-AEI',
       'China Railway Construction, Nanjing Government, China Development Bank, Guangdong Xinguang-AEI',
       'Ashima Cultural Industry-AEI',
       'Xinjiang Hualing, Shanghai Boda-AEI', 'Reignwood-AEI',
       'China National Machinery Industry (Sinomach)-led consortium-AEI',
       'Hydrochina-AEI', 'China Electronics Technology-AEI',
       'Jiangsu Jinsheng-AEI', 'Lenovo-AEI',
       'Shangdi Guanqun Investment-AEI',
       'Guangdong Changda Highway Engineering-AEI',
       'China State Shipbuilding-AEI', 'Nanshan Group-AEI',
       'Fulida Group-AEI', 'Chongqing Grain-AEI',
       'Shengli Engineering-led consortium-AEI',
       'Anhui Foreign Economic Construction-AEI', 'Evergreen-AEI',
       'Datang Power, China South Industries-AEI', 'Ningbo Joyson-AEI',
       'Zhongding International Construction-AEI', 'Shandong Iron-AEI',
       'China International Trust and Investment (CITIC), China Development Bank, Long March Capital-AEI',
       'Zijin Mining-AEI', 'Fosun-AEI', 'China Chengtong-AEI',
       'Chery Auto-AEI', 'Dalian International Cooperation Corp-AEI',
       'Suning-AEI', 'Dreal-AEI', 'Fuyao Glass-AEI', 'Gold One-AEI',
       'Guodian-AEI', 'Jilin Nonferrous-AEI', 'Haier-AEI',
       'Beijing Enterprises (BEHL)-AEI', 'Bright Foods-AEI',
       'Taiyuan Iron, China International Trust and Investment (CITIC), BaoWu Steel (Baosteel)-AEI',
       'Midea-AEI', 'JAC Motors-AEI',
       'China National Chemical Engineering, Dongfang Electric, China Energy Engineering-AEI',
       'Xinjiang Goldwind-AEI', 'United Energy-AEI',
       'Qingdao Tianzhong-AEI',
       'Power Construction Corp. (PowerChina)-AEI', 'Henan Guoju-AEI',
       'Jiangxi International Cooperation Corp-AEI', 'Tsingtao Beer-AEI',
       'China Nickel Resources-AEI', 'Soho China-AEI', 'Wolong-AEI',
       'Beijing Urban Construction-AEI', 'Guangxi Nonferrous-AEI',
       'Zhouda Real Estate-AEI',
       'Sinosteel, Power Construction Corp. (PowerChina)-AEI',
       'Sany Heavy Industry, China International Trust and Investment (CITIC)-AEI',
       'Shanghai Wanfeng-AEI', 'Shandong Heavy-AEI',
       'China Energy Engineering-AEI',
       'China Investment Corporation (CIC), China Petroleum and Chemical (Sinopec)-AEI',
       'Guangxi Liugong Machinery-AEI', 'China Shipping-AEI',
       'Guangdong Nuclear Power, China Development Bank-AEI',
       'Dalian Shipbuilding-AEI', 'Shanghai Pengxin-AEI',
       'Hebei Steel-AEI', 'Xuzhou Construction Machinery-AEI',
       'Wanxiang-AEI', 'China Construction Bank-AEI', 'Dalian Wanda-AEI',
       'China Architecture Design and Research-AEI',
       'Shanghai Construction-AEI', 'Hanergy-AEI', 'Xinjiang Hualing-AEI',
       'Wison Engineering-AEI', 'China Electric Equipment-AEI',
       'China Copper Mines-AEI', 'Sichuan Bohong-AEI',
       'China South Locomotive-AEI', 'Jiangxi Zhongmei-AEI',
       'Beijing Shenwu-AEI', 'Wanbao Grain-AEI', 'Shandong Ruyi-AEI',
       'Synutra-AEI', 'Shandong Energy-AEI', 'China Power Investment-AEI',
       'Shandong Gold-AEI', 'BGI-AEI', 'Xinwei-AEI',
       'Beijing Jingmei-AEI', 'Shanghai Greenland-AEI',
       'Shandong Linglong Tire-AEI', 'Sailun Tire-AEI', 'Yuanda-AEI',
       'Shanghai Zhongfu-AEI', 'Yili Industrial-AEI',
       'Hebei Steel, General Development, Tewoo-AEI',
       'Chengdu Tianqi, China Investment Corporation (CIC)-AEI',
       'Country Garden-AEI',
       'China Shipping, China Ocean Shipping (COSCO), China Merchants-AEI',
       'Anhui Conch-AEI',
       'Tebian Electric Apparatus (TBEA), Power Construction Corp. (PowerChina)-AEI',
       'Xiamen University-AEI',
       'Henan International Cooperation Corp-AEI', 'Guangxi Beibu-AEI',
       'Vanke-AEI', 'Shandong Bright Ruby-AEI',
       'Shenyang International Cooperation Corp-AEI',
       'China National Aviation Fuel-AEI', 'Hongye Investment-AEI',
       'Shuanghui-AEI', 'Shandong Qixing-AEI', 'Keep Glory-AEI',
       'CDH-AEI', 'Comtec Solar-AEI', 'Zarsion-AEI',
       'Shanghai MicroPort-AEI', 'Shandong Gaosu-AEI', 'Meidu-AEI',
       'Yunnan Copper-led consortium-AEI', 'China Molybdenum-AEI',
       'Tsingshan-AEI',
       'Power Construction Corp. (PowerChina), China Petroleum and Chemical (Sinopec)-AEI',
       'Shanxi Coking Coal-AEI', 'Belle International, CDH-AEI',
       'China Railway Rolling Stock Corp. (CRR) -AEI',
       'Shenzhen Zhongjin Lingnan-AEI', 'Shaanxi Yanchang Petroleum-AEI',
       'China Energy Conservation-AEI',
       'China National Petroleum Corp. (CNPC), China National Off-shore Oil (CNOOC)-AEI',
       'Zongshen Industrial-AEI', 'Alibaba-AEI', 'Henan Meijing-AEI',
       'China Aerospace Science and Technology-AEI',
       'Sichuan Railway Industry-AEI',
       'Power Construction Corp. (PowerChina), Yingli Green Energy-AEI',
       'Harbin Electric, China Energy Engineering-AEI',
       'Shanghai Zendai-AEI', 'Ming Yan-AEI', 'Keer Group-AEI',
       'Oceanwide Holdings-AEI', 'Guangzhou R&F Properties-AEI',
       'Shenzhen Hepalink-AEI', 'Shenzhen Hazens-AEI',
       'China South Industries-AEI', 'Henan Civil Aviation-AEI',
       'Wanfeng Auto-AEI',
       'China Railway Construction, China Railway Engineering-AEI',
       'Power Construction Corp. (PowerChina), China National Machinery Industry (Sinomach)-AEI',
       'Shandong Electric Power Construction II-AEI', 'Goodbaby-AEI',
       'Power Construction Corp. (PowerChina), Shanghai Construction-AEI',
       'Goldleaf Jewelry-AEI',
       'Bank of China, China Life, Hopu Investment-AEI',
       'Beijing Capital-AEI', 'Anhui Landing-AEI',
       'Huaxin Post and Telecom-AEI', 'Dongfeng-AEI',
       'Zhenfa New Energy-AEI', 'Geo-Jade Petroleum-AEI', 'Cinda-AEI',
       'United Energy, Ningbo Orient-AEI', 'Tidfore Heavy-AEI',
       'Zhejiang Rongsheng, Shanghai Zhongrong, Legend-AEI',
       'Minmetals, Suzhou Guoxin, China International Trust and Investment (CITIC)-AEI',
       'Sanpower-AEI', 'Hubei Fuxing Science-AEI',
       'China National Cereal, Oil and Foodstuffs (COFCO), Hopu Investment-AEI',
       'China Petroleum and Chemical (Sinopec), Huadian-AEI',
       'Hongqiao-AEI', 'Shenzhen Genzon-AEI', 'Baidu-AEI',
       'Shanghai Shentong-AEI',
       'Shanghai International Group, Sanpower-AEI', 'LeEco-AEI',
       'Yida-AEI', 'Heilongjiang Grand Farm-AEI',
       'China Railway Construction, China Nonferrous-AEI', 'Huapont-AEI',
       'Legend-AEI', 'Shandong Daiyin-AEI',
       'State Development and Investment Corp., Anhui Conch-AEI',
       'Huajian-AEI', 'Solargiga-AEI', 'Sino Great Wall-AEI',
       'Sichuan Department of Agriculture-AEI',
       'Rongsheng Heavy Industries-AEI', 'China General Nuclear-AEI',
       'Dalian Wanda, Ridong-AEI', 'Shanghai Shenglong-AEI',
       'China National Machinery Industry (Sinomach), China National Chemical Engineering-AEI',
       'Huayi Brothers-AEI',
       'Power Construction Corp. (PowerChina), China Energy Engineering-AEI',
       'Anbang-AEI', 'Baidu, Ping An, Qihoo-AEI',
       'Hebei Zhongbo Platinum-AEI', 'Vision Investment-AEI',
       'Sunshine Insurance-AEI', 'Texhong Textile-AEI',
       'Shandong Landbridge-AEI', 'Xinyi Glass-AEI',
       'Haitong Securities-AEI', 'BlueFocus Communications-AEI',
       'Sichuan Xinglida-AEI',
       'Shandong Gaosu, China Aircraft Leasing-AEI',
       'Guangzhou Dongsong-AEI', 'Taikang Life-AEI',
       'Trip.com (formerly Ctrip.com)-AEI', 'Zhejiang Hengyi-AEI',
       'Gansu International Cooperation Corp-AEI',
       'Beijing Uni-Construction-AEI', 'Tencent, Renren-AEI',
       'Gansu Tianqing-AEI',
       'Jiangsu Changjiang, Semiconductor Manufacturing International, National IC Fund-AEI',
       'Zhejiang Huayou Cobalt-AEI',
       'China Launch and Tracking Control General-AEI',
       'Anhui Zhongding-AEI', 'SAIC Motor (Shanghai Auto), Wuling-AEI',
       'Qingdao Sentury-AEI', 'Jinko Solar-AEI', 'Hunan TV-AEI',
       'China Railway Construction, China Energy Engineering-AEI',
       'China Life, Ping An-AEI',
       'Tsinghua Holdings, China International Trust and Investment (CITIC)-AEI',
       'Cybernaut-AEI', 'Yantai Xinchao-AEI',
       'State Construction Engineering, Anhui Foreign Economic Construction-AEI',
       'Trina Solar-AEI', 'BYD-AEI', 'China Communications Bank-AEI',
       'Zhongrun Resources-AEI', 'Jumei-AEI', 'CEFC-AEI',
       'Zhongman Petroleum-AEI', 'ZOJE Resources-AEI',
       'China Minsheng Investment-AEI', 'Uphill Investment-AEI',
       'Aviation Industry Corp. (AVIC), Bank of China-AEI',
       'China National Chemical (ChemChina), State Administration of Foreign Exchange (SAFE)-AEI',
       'Sinolight-AEI',
       'China Railway Corp, China North Industries (Norinco)-AEI',
       'Taiping Life-AEI', 'NetDragon-AEI', 'Sinoenergy-AEI',
       'Hongshi-AEI', 'Power Construction Corp. (PowerChina), HTG-AEI',
       'Power Construction Corp. (PowerChina), China Railway Construction-AEI',
       'Southern Power Grid, State Power Investment-AEI',
       'Jiangnan Mould and Plastic-AEI', 'Shimao-AEI',
       'China Western Power Industrial-AEI',
       'Anton Oilfield Services-AEI', 'Phicomm-AEI', 'Jangho-AEI',
       'Shanghai Municipal Investment-AEI',
       'Bright Foods, JIC, Shenzhen Donghuatong-AEI',
       'China Merchants, China Investment Corporation (CIC), China Ocean Shipping (COSCO)-AEI',
       'Biostime-AEI', 'Didi Kuaidi-AEI', 'Shenzhen Government-AEI',
       'Xian LONGi-AEI', 'Fujian Thai Hot-AEI', 'Genimous Investment-AEI',
       'Angel Yeast-AEI', 'C Banner International-AEI',
       'Moon Lake Investments-AEI',
       'China Investment Corporation (CIC), Didi Kuaidi-AEI',
       'Sinocare-AEI', 'Nantong Fujitsu-AEI', 'Renren-AEI',
       'Shanxi Building Material, Asian and African Business Management-AEI',
       'Zhejiang Holley, Futong Group-AEI', 'Zhejiang Chint-AEI',
       'Shanghai Yuyuan Tourist Mart-AEI',
       'China General Nuclear, Southern Power Grid-AEI',
       'GR Investment, China International Trust and Investment (CITIC)-AEI',
       'China Media Capital, China International Trust and Investment (CITIC)-AEI',
       'Zhuhai Port Holdings, State Construction Engineering-AEI',
       'Landsea-AEI', 'Leyard Optoelectronics-AEI',
       'China Petroleum and Chemical (Sinopec), Jiangxi Water-AEI',
       'Qingdao Hengshun-AEI', 'Luye Life Sciences-AEI',
       'State Power Investment-AEI', 'Highland Fund-AEI',
       'Yunnan Construction Engineering-AEI', 'Liuhe-AEI',
       'Shanghai Inesa-AEI',
       'State Administration of Foreign Exchange (SAFE), China Reform Holdings-AEI',
       'Zhongli-AEI', 'Beijing Municipal Government-AEI',
       'Yunnan Energy Investment-AEI', 'Inspur Group-AEI',
       'China Lilongwe Grand-AEI', 'Zhuzhou Kibing-AEI',
       'China North Industries (Norinco), Shandong Taikai Group-AEI',
       'State Construction Engineering, China Communications Construction-AEI',
       'Chengdu Techcent-AEI', 'Perfect World Pictures-AEI',
       'Visual China-AEI', 'Lifan-AEI',
       'China Communications Construction, China National Petroleum Corp. (CNPC)-AEI',
       'Film Carnival-AEI', 'ENN Energy-AEI', 'Humanwell Healthcare-AEI',
       'Jiangsu Yongding, China National Machinery Industry (Sinomach)-AEI',
       'State Grid, Power Construction Corp. (PowerChina)-AEI',
       'China Light, Jiangxi Jianglian-AEI', 'Zhuhai Zhenrong-AEI',
       'China National Silicon (consortium of Shanghai state firms)-AEI',
       'Jiangsu Sunshine-AEI',
       'Harbin Electric, State Administration of Foreign Exchange (SAFE)-AEI',
       'China Orient Asset Management-AEI', 'Huatai Securities-AEI',
       'Ninestar, Legend-AEI', 'HNA, Jin Jiang International-AEI',
       'Guangdong Heng Fu-AEI',
       "Aviation Industry Corp. (AVIC), Han's Laser-AEI",
       'Zhejiang Kaishan-AEI', 'Shanghai Zhongji-AEI',
       'Tsinghua Holdings-AEI',
       'China Ocean Shipping (COSCO), State Administration of Foreign Exchange (SAFE)-AEI',
       'Qianhai Zone Authority-AEI', 'Recon Group-AEI',
       'China Everbright, Baofeng-AEI',
       'Guangdong Province, Huaneng Power-AEI', 'Guangxi Investment-AEI',
       'Envision Group-AEI', 'Guotsing-AEI',
       'Xinjiang Goldwind, China Energy Conservation-AEI', 'Creat-AEI',
       'China Investment Corporation (CIC), Wise Road Capital-AEI',
       'Spearhead-AEI', 'Everbright-AEI', 'Genzon-AEI',
       'Tencent-led consortium-AEI',
       'Xiwang Group, Primavera Capital-AEI', 'Qihoo, Beijing Kunlun-AEI',
       'China Resources-AEI', 'China Animal Husbandry-AEI',
       'Jiquan Iron and Steel-AEI',
       'IDG Capital, MLS, Yiwu State-Owned Assets-AEI', 'Hailiang-AEI',
       'Zhonghong Zhuoye-AEI', 'Wuhan Zhengtang-AEI',
       'Shanghai Giant Network-led consortium-AEI', 'Suzhou Dongshan-AEI',
       'Tidfore Heavy Equipment-AEI',
       'Shanghai Industrial Holdings, Primavera Capital-AEI',
       'Didi Chuxing-AEI', 'Shanghai Greenland-led consortium-AEI',
       'Yunyi Guokai Shanghai-AEI', 'Fujian Construction Engineering-AEI',
       'Jiangsu Longze-AEI', 'IDG Capital-AEI',
       'Shenyang Blue Silver-AEI', 'Tencent, Legend-AEI',
       'Power Construction Corp. (PowerChina), China Railway Engineering-AEI',
       'Chengdu Tianqi-AEI', 'Chongqing USUM-AEI',
       'Hangzhou Lianluo Interactive-AEI', 'Beijing Miteno-AEI',
       'China Energy Conservation, Jiangsu Dagang, China Tianying-AEI',
       'Beijing Shanhai Capital, National IC Fund-AEI',

In [1188]:
aei_data = aei_data[new_order]

In [1189]:
subsectors

array(['Aviation-AEI', 'Autos-AEI', 'Steel-AEI', 'Construction-AEI',
       'Oil-AEI', 'Coal-AEI', 'Rail-AEI', 'Hydro-AEI', 'Aluminum-AEI',
       'Industry-AEI', 'Property-AEI', 'Gas-AEI', 'Timber-AEI',
       'Alternative-AEI', 'Telecom-AEI', 'Copper-AEI', 'Investment-AEI',
       'Shipping-AEI', 'Banking-AEI', 'Textiles-AEI', 'Education-AEI'],
      dtype=object)

In [1190]:
aei_data

level_2       Minmetals-AEI  Chinese Academy of Sciences-AEI  Sinohydro-AEI  \
Country Year
AE      2006            NaN                              NaN            NaN
        2007            NaN                              NaN            1.0
        2008            NaN                              NaN            NaN
        2009            NaN                              NaN            NaN
        2010            NaN                              NaN            NaN
...                     ...                              ...            ...
ZW      2019            NaN                              NaN            NaN
        2020            NaN                              NaN            NaN
        2021            NaN                              NaN            NaN
        2022            NaN                              NaN            NaN
        2023            NaN                              NaN            NaN

level_2       MCC-AEI  Sinoma-AEI  China National Off-shore Oil (CNOOC)-AEI  \
Country Year
AE      2006      NaN         NaN                                       NaN
        2007      NaN         NaN                                       NaN
        2008      NaN         NaN                                       NaN
        2009      NaN         NaN                                       NaN
        2010      NaN         NaN                                       NaN
...               ...         ...                                       ...
ZW      2019      NaN         NaN                                       NaN
        2020      NaN         NaN                                       NaN
        2021      NaN         NaN                                       NaN
        2022      NaN         NaN                                       NaN
        2023      NaN         NaN                                       NaN

level_2       China National Machinery Industry (Sinomach)-AEI  \
Country Year
AE      2006                                               NaN
        2007                                               NaN
        2008                                               NaN
        2009                                               NaN
        2010                                               NaN
...                                                        ...
ZW      2019                                               NaN
        2020                                               NaN
        2021                                               NaN
        2022                                               NaN
        2023                                               NaN

level_2       Minmetals, MCC-AEI  China National Petroleum Corp. (CNPC)-AEI  \
Country Year
AE      2006                 NaN                                        NaN
        2007                 NaN                                        NaN
        2008                 NaN                                        1.0
        2009                 NaN                                        NaN
        2010                 NaN                                        NaN
...                          ...                                        ...
ZW      2019                 NaN                                        NaN
        2020                 NaN                                        NaN
        2021                 NaN                                        NaN
        2022                 NaN                                        NaN
        2023                 NaN                                        NaN

level_2       China Petroleum and Chemical (Sinopec)-AEI  ...  Telecom-AEI  \
Country Year                                              ...
AE      2006                                         NaN  ...          NaN
        2007                                         NaN  ...          NaN
        2008                                         NaN  ...          NaN
        2009                                         NaN  ...          NaN
        2010                                         NaN  ...          NaN
...                                                  ...  ...          ...
ZW      2019                                         NaN  ...          NaN
        2020                                         NaN  ...          NaN
        2021                                         NaN  ...          NaN
        2022                                         NaN  ...          NaN
        2023                                         NaN  ...          NaN

level_2       Copper-AEI  Investment-AEI  Shipping-AEI  Banking-AEI  \
Country Year
AE      2006         NaN             NaN           NaN          NaN
        2007         NaN             NaN           NaN          NaN
        2008         NaN             NaN           NaN          NaN
        2009         NaN             NaN           NaN          NaN
        2010         NaN             NaN           NaN          NaN
...                  ...             ...           ...          ...
ZW      2019         NaN             NaN           NaN          NaN
        2020         NaN             NaN           NaN          NaN
        2021         NaN             NaN           NaN          NaN
        2022         NaN             NaN           NaN          NaN
        2023         NaN             NaN           NaN          NaN

level_2       Textiles-AEI  Education-AEI  High-AEI  Low-AEI  Medium-AEI
Country Year
AE      2006           NaN            NaN       NaN      NaN         1.0
        2007           NaN            NaN       NaN      2.0         1.0
        2008           NaN            NaN       1.0      NaN         1.0
        2009           NaN            NaN       1.0      NaN         1.0
        2010           NaN            NaN       NaN      1.0         NaN
...                    ...            ...       ...      ...         ...
ZW      2019           NaN            NaN       NaN      NaN         2.0
        2020           NaN            NaN       1.0      NaN         NaN
        2021           NaN            NaN       NaN      2.0         1.0
        2022           NaN            NaN       1.0      1.0         2.0
        2023           NaN            NaN       NaN      1.0         NaN

[1369 rows x 935 columns]

In [1191]:
aei_data.fillna(0, inplace = True)

In [1192]:
aei_data.reset_index(inplace = True)

In [1193]:
aei_data = aei_data.sort_values(["Year", "Country"])

In [1194]:
aei_data

level_2,Country,Year,Minmetals-AEI,Chinese Academy of Sciences-AEI,Sinohydro-AEI,MCC-AEI,Sinoma-AEI,China National Off-shore Oil (CNOOC)-AEI,China National Machinery Industry (Sinomach)-AEI,"Minmetals, MCC-AEI",...,Telecom-AEI,Copper-AEI,Investment-AEI,Shipping-AEI,Banking-AEI,Textiles-AEI,Education-AEI,High-AEI,Low-AEI,Medium-AEI
24,AO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
57,AU,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
139,BR,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
175,CA,2005,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
267,CU,2005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,UZ,2023,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0
1318,VN,2023,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0
1337,ZA,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1354,ZM,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0
1368,ZW,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1195]:
aei_data[new_order] = aei_data[new_order].apply(lambda x: x.apply(lambda y: np.nan) if x.sum() < 50 else x)

In [1196]:
def drop_column_conditionally(x):
    for column in x.columns:
        if x[column].isnull().all():
            x.drop(column, axis = 1, inplace = True)
        

drop_column_conditionally(aei_data)
aei_data

level_2,Country,Year,Minmetals-AEI,Sinohydro-AEI,Sinoma-AEI,China National Machinery Industry (Sinomach)-AEI,China National Petroleum Corp. (CNPC)-AEI,China Petroleum and Chemical (Sinopec)-AEI,China Communications Construction-AEI,China International Trust and Investment (CITIC)-AEI,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
24,AO,2005,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
57,AU,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
139,BR,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
175,CA,2005,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
267,CU,2005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,UZ,2023,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,2.0,3.0
1318,VN,2023,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0
1337,ZA,2023,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1354,ZM,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0
1368,ZW,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1197]:
type(aei_data["Year"][0])

numpy.int64

In [1198]:
aei_data.set_index(["Country", "Year"], inplace = True)

In [1199]:
loan_debt_data = pd.concat([loan_debt_data, aei_data], axis = 1, join = "outer")

In [1200]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DZ,2000,57.96034348,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,2000,133.9141396,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,2000,105.1323732,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UZ,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,2.0,3.0
VN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0
ZA,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
ZM,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0
ZW,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1201]:
loan_debt_data.fillna("Not Available", inplace = True)

In [1202]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
DZ,2000,57.96034348,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
AO,2000,133.9141396,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
AG,2000,105.1323732,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UZ,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,2.0,3.0
VN,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0
ZA,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
ZM,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0
ZW,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1203]:
loan_debt_data.reset_index(inplace = True)

In [1204]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
0,AF,2000,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,AL,2000,63.37646291,63.76868358,1.0,0.0,0.0,0.0,1.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
2,DZ,2000,57.96034348,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
3,AO,2000,133.9141396,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4,AG,2000,105.1323732,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4474,UZ,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,2.0,3.0
4475,VN,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0
4476,ZA,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4477,ZM,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0
4478,ZW,2023,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1205]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] <= 2021]

In [1206]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] >= 2005]

In [1207]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
865,AF,2005,206.3560065,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
866,AL,2005,58.1995534,58.20335897,1.0,0.0,0.0,0.0,1.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
867,DZ,2005,26.31138467,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
868,AO,2005,33.46404183,Not Available,1.0,8.0,0.0,0.0,1.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
869,AG,2005,92.61438311,Not Available,1.0,1.0,0.0,0.0,2.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4394,CU,2020,Not Available,Not Available,4.0,0.0,0.0,0.0,4.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4395,KP,2020,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4396,CU,2021,Not Available,Not Available,5.0,0.0,0.0,0.0,5.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4397,SO,2021,Not Available,Not Available,3.0,0.0,0.0,0.0,3.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4400,CU,2014,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [1208]:
np.unique(loan_debt_data["Country"])

array(['AE', 'AF', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA',
       'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR',
       'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI',
       'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CY', 'CZ', 'DE',
       'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ER', 'ES', 'ET',
       'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN',
       'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID',
       'IE', 'IL', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE',
       'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KZ', 'LA', 'LB',
       'LC', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MD', 'ME',
       'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MR', 'MT', 'MU', 'MV', 'MW',
       'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR',
       'NU', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT',
       'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE',
       'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV',
       'SY', 'SZ', 'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR',
       'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VE',
       'VN', 'VU', 'WS', 'YE', 'ZA', 'ZM', 'ZW'], dtype=object)

In [1209]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [1210]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Industry-AEI,Property-AEI,Gas-AEI,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,High-AEI,Low-AEI,Medium-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2005,206.3560065,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
AL,2005,58.1995534,58.20335897,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
DZ,2005,26.31138467,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
AO,2005,33.46404183,Not Available,1.0,8.0,0.0,0.0,1.0,8.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
AG,2005,92.61438311,Not Available,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CU,2020,Not Available,Not Available,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
KP,2020,Not Available,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
CU,2021,Not Available,Not Available,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
SO,2021,Not Available,Not Available,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
CU,2014,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [1211]:
indicators_to_choose = pd.read_csv("Data/V-Dem Indicators Modified.csv")

In [1212]:
indicators_to_choose.columns

Index(['country_name', 'year', 'v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem',
       'v2smgovfilcap', 'v2smgovfilcap_ord', 'v2smgovfilprc',
       'v2smgovfilprc_ord', 'v2smgovshutcap', 'v2smgovshutcap_ord',
       'v2smgovshut', 'v2smgovsm_ord', 'v2smgovsmmon', 'v2smgovsmmon_ord',
       'v2smgovsmcenprc', 'v2smgovsmcenprc_ord', 'v2smarrest',
       'v2smarrest_ord', 'e_fh_cl', 'e_fh_pr', 'e_fh_rol', 'e_wbgi_cce',
       'e_wbgi_gee', 'e_wbgi_pve', 'e_autoc', 'e_democ', 'e_p_polity', 'e_gdp',
       'e_pop'],
      dtype='object')

In [1213]:
indicators = indicators_to_choose.iloc[:,[2,3,4]]

In [1214]:
select = np.array(indicators.columns)

In [1215]:
other_select = np.array(indicators_to_choose.columns[19:])

In [1216]:
select = np.concatenate([select, other_select])

In [1217]:
select

array(['v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem', 'e_fh_cl',
       'e_fh_pr', 'e_fh_rol', 'e_wbgi_cce', 'e_wbgi_gee', 'e_wbgi_pve',
       'e_autoc', 'e_democ', 'e_p_polity', 'e_gdp', 'e_pop'], dtype=object)

In [1218]:
all_indicators = pd.read_csv("Data/V-Dem Indicators.csv")

In [1219]:
all_indicators = all_indicators.rename({"country_name": "Country", "year": "Year"}, axis = 1)

In [1220]:
all_indicators = all_indicators.replace(name_to_alpha_2)

In [1221]:
all_indicators.set_index(["Country", "Year"], inplace = True)

In [1222]:
all_indicators = all_indicators[select]

In [1223]:
all_indicators.reset_index(inplace = True)

In [1224]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
0,MX,1789,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,871.938,645.627
1,MX,1790,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,878.908,647.112
2,MX,1791,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.411,647.464
3,MX,1792,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.880,649.721
4,MX,1793,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,912.872,650.911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27550,Piedmont-Sardinia,1857,0.207,0.135,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27551,Piedmont-Sardinia,1858,0.210,0.136,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27552,Piedmont-Sardinia,1859,0.210,0.136,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27553,Piedmont-Sardinia,1860,0.213,0.137,0.064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27554,Piedmont-Sardinia,1861,0.213,0.137,0.075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1225]:
all_indicators = all_indicators[all_indicators["Year"] >= 2005]

In [1226]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
216,MX,2005,0.710,0.510,0.441,2.0,2.0,8.0,-0.344,0.033,-0.446,0.0,8.0,8.0,162093.745,11313.743
217,MX,2006,0.675,0.482,0.417,3.0,2.0,8.0,-0.325,0.052,-0.637,0.0,8.0,8.0,167391.970,11479.812
218,MX,2007,0.644,0.454,0.397,3.0,2.0,7.0,-0.341,0.139,-0.730,0.0,8.0,8.0,171691.031,11657.849
219,MX,2008,0.643,0.456,0.394,3.0,2.0,6.0,-0.310,0.164,-0.804,0.0,8.0,8.0,174203.808,11795.028
220,MX,2009,0.641,0.455,0.395,3.0,2.0,6.0,-0.366,0.145,-0.687,0.0,8.0,8.0,171738.827,11908.825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26151,TZ,2018,0.268,0.223,0.177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26152,TZ,2019,0.266,0.215,0.169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26153,TZ,2020,0.258,0.209,0.165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26154,TZ,2021,0.276,0.225,0.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26155,TZ,2022,0.284,0.233,0.173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1227]:
np.unique(all_indicators["Country"])

array(['AE', 'AF', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB',
       'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BO', 'BR', 'BT', 'BW',
       'BY', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CL', 'CM', 'CN', 'CO',
       'CR', 'CU', 'CV', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DO', 'DZ', 'EC',
       'EE', 'EG', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FR', 'GA', 'GB', 'GE',
       'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR',
       'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JM',
       'JO', 'JP', 'KE', 'KG', 'KH', 'KM', 'KP', 'KR', 'KW', 'KZ', 'LA',
       'LB', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MD', 'ME',
       'MG', 'MK', 'ML', 'MM', 'MN', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX',
       'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NZ', 'OM',
       'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PY', 'QA', 'RO',
       'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SI', 'SK',
       'SL', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SY', 'SZ', 'Somaliland',
       'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TR', 'TT', 'TW', 'TZ',
       'UA', 'UG', 'US', 'UY', 'UZ', 'VE', 'VN', 'VU', 'XK', 'YE', 'ZA',
       'ZM', 'ZW'], dtype=object)

In [1228]:
all_indicators = all_indicators.sort_values(["Year", "Country"])

In [1229]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
25706,AE,2005,0.020,0.069,0.017,6.0,6.0,4.0,0.991,0.705,0.875,8.0,0.0,-8.0,44675.582,502.176
5478,AF,2005,0.335,0.137,0.139,5.0,5.0,4.0,-1.447,-1.217,-2.068,-66.0,-66.0,-66.0,2912.684,2746.122
1855,AL,2005,0.505,0.415,0.333,3.0,3.0,10.0,-0.813,-0.705,-0.505,0.0,9.0,9.0,2140.925,321.135
15962,AM,2005,0.346,0.192,0.186,4.0,5.0,6.0,-0.683,-0.139,-0.066,0.0,5.0,5.0,2085.719,315.380
15929,AO,2005,0.176,0.092,0.060,5.0,6.0,4.0,-1.323,-1.106,-0.885,4.0,2.0,-2.0,7375.750,1860.841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6656,XK,2022,0.618,0.463,0.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2273,YE,2022,0.123,0.045,0.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,ZA,2022,0.692,0.581,0.430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9242,ZM,2022,0.518,0.433,0.352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9365,ZW,2022,0.285,0.186,0.215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1230]:
all_indicators = all_indicators.groupby(['Country', 'Year']).mean()

In [1231]:
all_indicators

              v2x_polyarchy  v2x_libdem  v2x_partipdem  e_fh_cl  e_fh_pr  \
Country Year
AE      2005          0.020       0.069          0.017      6.0      6.0
        2006          0.024       0.071          0.017      5.0      6.0
        2007          0.069       0.079          0.022      5.0      6.0
        2008          0.070       0.080          0.022      5.0      6.0
        2009          0.070       0.080          0.022      5.0      6.0
...                     ...         ...            ...      ...      ...
ZW      2018          0.305       0.214          0.243      5.0      5.0
        2019          0.293       0.201          0.234      5.0      5.0
        2020          0.293       0.196          0.222      5.0      6.0
        2021          0.291       0.194          0.221      5.0      6.0
        2022          0.285       0.186          0.215      NaN      NaN

              e_fh_rol  e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  \
Country Year
AE      2005       4.0       0.991       0.705       0.875      8.0      0.0
        2006       4.0       0.886       0.937       0.923      8.0      0.0
        2007       3.0       1.006       0.917       0.975      8.0      0.0
        2008       4.0       1.071       0.868       0.696      8.0      0.0
        2009       4.0       0.906       0.987       0.919      8.0      0.0
...                ...         ...         ...         ...      ...      ...
ZW      2018       2.0      -1.228      -1.262      -0.723      1.0      5.0
        2019       2.0      -1.273      -1.267      -0.960      NaN      NaN
        2020       2.0      -1.289      -1.300      -1.072      NaN      NaN
        2021       NaN      -1.258      -1.243      -1.027      NaN      NaN
        2022       NaN         NaN         NaN         NaN      NaN      NaN

              e_p_polity      e_gdp     e_pop
Country Year
AE      2005        -8.0  44675.582   502.176
        2006        -8.0  49070.524   576.779
        2007        -8.0  51953.349   658.203
        2008        -8.0  53685.703   747.211
        2009        -8.0  51878.656   822.599
...                  ...        ...       ...
ZW      2018         4.0   4857.211  1564.405
        2019         NaN   4870.709  1566.385
        2020         NaN        NaN       NaN
        2021         NaN        NaN       NaN
        2022         NaN        NaN       NaN

[3180 rows x 14 columns]

In [1232]:
all_indicators.reset_index (inplace = True)

In [1233]:
all_indicators = all_indicators.sort_values(["Year", "Country"])

In [1234]:
all_indicators = all_indicators[all_indicators["Year"] <= 2021]

In [1235]:
loan_debt_data.reset_index(inplace = True)

In [1236]:
all_indicators = all_indicators[all_indicators["Country"].isin(loan_debt_data["Country"])]

In [1237]:
loan_debt_data = loan_debt_data.sort_values(["Year", "Country"])

In [1238]:
all_indicators.set_index(["Country", "Year"], inplace = True)

In [1239]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [1240]:
loan_debt_data = pd.concat([loan_debt_data, all_indicators], axis = 1, join = "outer")

In [1241]:

loan_debt_data

             Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                         Not Available
AF      2005                           206.3560065
AG      2005                           92.61438311
AL      2005                            58.1995534
AM      2005                           20.46716654
...                                            ...
KP      2018                                   NaN
        2019                                   NaN
SO      2019                                   NaN
        2020                                   NaN
KP      2021                                   NaN

             General Govt Debt (Percentage of GDP) Grant Loan Vague  \
Country Year
AE      2005                           4.481496626   0.0  0.0   0.0
AF      2005                         Not Available   1.0  0.0   0.0
AG      2005                         Not Available   1.0  1.0   0.0
AL      2005                           58.20335897   1.0  0.0   0.0
AM      2005                         Not Available   0.0  0.0   0.0
...                                            ...   ...  ...   ...
KP      2018                                   NaN   NaN  NaN   NaN
        2019                                   NaN   NaN  NaN   NaN
SO      2019                                   NaN   NaN  NaN   NaN
        2020                                   NaN   NaN  NaN   NaN
KP      2021                                   NaN   NaN  NaN   NaN

             Commercial Development Mixed Representational  \
Country Year
AE      2005        0.0         0.0   0.0              0.0
AF      2005        0.0         1.0   0.0              0.0
AG      2005        0.0         2.0   0.0              0.0
AL      2005        0.0         1.0   0.0              0.0
AM      2005        0.0         0.0   0.0              0.0
...                 ...         ...   ...              ...
KP      2018        NaN         NaN   NaN              NaN
        2019        NaN         NaN   NaN              NaN
SO      2019        NaN         NaN   NaN              NaN
        2020        NaN         NaN   NaN              NaN
KP      2021        NaN         NaN   NaN              NaN

             ACTION RELATING TO DEBT  ... e_fh_pr e_fh_rol e_wbgi_cce  \
Country Year                          ...
AE      2005                     0.0  ...     6.0      4.0      0.991
AF      2005                     0.0  ...     5.0      4.0     -1.447
AG      2005                     0.0  ...     NaN      NaN        NaN
AL      2005                     0.0  ...     3.0     10.0     -0.813
AM      2005                     0.0  ...     5.0      6.0     -0.683
...                              ...  ...     ...      ...        ...
KP      2018                     NaN  ...     7.0      0.0     -1.571
        2019                     NaN  ...     7.0      0.0     -1.594
SO      2019                     NaN  ...     7.0      0.0     -1.709
        2020                     NaN  ...     7.0      0.0     -1.671
KP      2021                     NaN  ...     7.0      NaN     -1.605

             e_wbgi_gee e_wbgi_pve e_autoc e_democ e_p_polity      e_gdp  \
Country Year
AE      2005      0.705      0.875     8.0     0.0       -8.0  44675.582
AF      2005     -1.217     -2.068   -66.0   -66.0      -66.0   2912.684
AG      2005        NaN        NaN     NaN     NaN        NaN        NaN
AL      2005     -0.705     -0.505     0.0     9.0        9.0   2140.925
AM      2005     -0.139     -0.066     0.0     5.0        5.0   2085.719
...                 ...        ...     ...     ...        ...        ...
KP      2018     -1.573     -0.348    10.0     0.0      -10.0   4867.297
        2019     -1.398     -0.318     NaN     NaN        NaN   4873.972
SO      2019     -2.251     -2.387     NaN     NaN        NaN   2710.709
        2020     -2.109     -2.577     NaN     NaN        NaN        NaN
KP      2021     -1.557     -0.453     NaN     NaN        NaN        NaN

                 e_pop
Country Year
AE      2005   502.176
AF      2005  2746.122
AG      2005       NaN
AL      2005   321.135
AM      2005   315.380
...                ...
KP      2018  2712.980
        2019  2717.578
SO      2019  1581.318
        2020       NaN
KP      2021       NaN

[3276 rows x 101 columns]

In [1242]:
loan_debt_data["gdp_per_cap"] = loan_debt_data["e_gdp"] / loan_debt_data["e_pop"]

In [1243]:
loan_debt_data.fillna("Not Available", inplace = True)

In [1244]:
loan_debt_data

             Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                         Not Available
AF      2005                           206.3560065
AG      2005                           92.61438311
AL      2005                            58.1995534
AM      2005                           20.46716654
...                                            ...
KP      2018                         Not Available
        2019                         Not Available
SO      2019                         Not Available
        2020                         Not Available
KP      2021                         Not Available

             General Govt Debt (Percentage of GDP)          Grant  \
Country Year
AE      2005                           4.481496626            0.0
AF      2005                         Not Available            1.0
AG      2005                         Not Available            1.0
AL      2005                           58.20335897            1.0
AM      2005                         Not Available            0.0
...                                            ...            ...
KP      2018                         Not Available  Not Available
        2019                         Not Available  Not Available
SO      2019                         Not Available  Not Available
        2020                         Not Available  Not Available
KP      2021                         Not Available  Not Available

                       Loan          Vague     Commercial    Development  \
Country Year
AE      2005            0.0            0.0            0.0            0.0
AF      2005            0.0            0.0            0.0            1.0
AG      2005            1.0            0.0            0.0            2.0
AL      2005            0.0            0.0            0.0            1.0
AM      2005            0.0            0.0            0.0            0.0
...                     ...            ...            ...            ...
KP      2018  Not Available  Not Available  Not Available  Not Available
        2019  Not Available  Not Available  Not Available  Not Available
SO      2019  Not Available  Not Available  Not Available  Not Available
        2020  Not Available  Not Available  Not Available  Not Available
KP      2021  Not Available  Not Available  Not Available  Not Available

                      Mixed Representational ACTION RELATING TO DEBT  ...  \
Country Year                                                          ...
AE      2005            0.0              0.0                     0.0  ...
AF      2005            0.0              0.0                     0.0  ...
AG      2005            0.0              0.0                     0.0  ...
AL      2005            0.0              0.0                     0.0  ...
AM      2005            0.0              0.0                     0.0  ...
...                     ...              ...                     ...  ...
KP      2018  Not Available    Not Available           Not Available  ...
        2019  Not Available    Not Available           Not Available  ...
SO      2019  Not Available    Not Available           Not Available  ...
        2020  Not Available    Not Available           Not Available  ...
KP      2021  Not Available    Not Available           Not Available  ...

                   e_fh_rol     e_wbgi_cce     e_wbgi_gee     e_wbgi_pve  \
Country Year
AE      2005            4.0          0.991          0.705          0.875
AF      2005            4.0         -1.447         -1.217         -2.068
AG      2005  Not Available  Not Available  Not Available  Not Available
AL      2005           10.0         -0.813         -0.705         -0.505
AM      2005            6.0         -0.683         -0.139         -0.066
...                     ...            ...            ...            ...
KP      2018            0.0         -1.571         -1.573         -0.348
        2019            0.0         -1.594         -1.398         -0.318
SO      2019            0.0         -1.709         -2.251         -2.387
        2020            0.0         -1.671         -2.109         -2.577
KP      2021  Not Available         -1.605         -1.557         -0.453

                    e_autoc        e_democ     e_p_polity          e_gdp  \
Country Year
AE      2005            8.0            0.0           -8.0      44675.582
AF      2005          -66.0          -66.0          -66.0       2912.684
AG      2005  Not Available  Not Available  Not Available  Not Available
AL      2005            0.0            9.0            9.0       2140.925
AM      2005            0.0            5.0            5.0       2085.719
...                     ...            ...            ...            ...
KP      2018           10.0            0.0          -10.0       4867.297
        2019  Not Available  Not Available  Not Available       4873.972
SO      2019  Not Available  Not Available  Not Available       2710.709
        2020  Not Available  Not Available  Not Available  Not Available
KP      2021  Not Available  Not Available  Not Available  Not Available

                      e_pop    gdp_per_cap
Country Year
AE      2005        502.176      88.963993
AF      2005       2746.122       1.060654
AG      2005  Not Available  Not Available
AL      2005        321.135       6.666745
AM      2005         315.38       6.613352
...                     ...            ...
KP      2018        2712.98       1.794078
        2019       2717.578       1.793498
SO      2019       1581.318       1.714209
        2020  Not Available  Not Available
KP      2021  Not Available  Not Available

[3276 rows x 102 columns]

In [1245]:
loan_debt_data.reset_index(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_3612\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)

In [1246]:
loan_debt_data.replace(alpha_2_to_name, inplace = True)

In [1247]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap
0,United Arab Emirates,2005,Not Available,4.481496626,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.991,0.705,0.875,8.0,0.0,-8.0,44675.582,502.176,88.963993
1,Afghanistan,2005,206.3560065,Not Available,1.0,0.0,0.0,0.0,1.0,0.0,...,4.0,-1.447,-1.217,-2.068,-66.0,-66.0,-66.0,2912.684,2746.122,1.060654
2,Antigua and Barbuda,2005,92.61438311,Not Available,1.0,1.0,0.0,0.0,2.0,0.0,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
3,Albania,2005,58.1995534,58.20335897,1.0,0.0,0.0,0.0,1.0,0.0,...,10.0,-0.813,-0.705,-0.505,0.0,9.0,9.0,2140.925,321.135,6.666745
4,Armenia,2005,20.46716654,Not Available,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,-0.683,-0.139,-0.066,0.0,5.0,5.0,2085.719,315.38,6.613352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3271,"Korea, Democratic People's Republic of",2018,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,-1.571,-1.573,-0.348,10.0,0.0,-10.0,4867.297,2712.98,1.794078
3272,"Korea, Democratic People's Republic of",2019,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,-1.594,-1.398,-0.318,Not Available,Not Available,Not Available,4873.972,2717.578,1.793498
3273,Somalia,2019,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,-1.709,-2.251,-2.387,Not Available,Not Available,Not Available,2710.709,1581.318,1.714209
3274,Somalia,2020,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,0.0,-1.671,-2.109,-2.577,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
3275,"Korea, Democratic People's Republic of",2021,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,Not Available,-1.605,-1.557,-0.453,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available

In [1248]:
loan_debt_data.to_csv("loan_debt_data.csv", index = False)