In [258]:
import pandas as pd
import numpy as np
from standardize_country import name_to_alpha_2, alpha_2_to_name, alpha_3_to_alpha_2, alpha_2_to_alpha_3

In [259]:
central_debt = pd.read_csv("Data/central_debt_as_gdp.csv")

In [260]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479,8.700291,9.154083,8.437266,7.997660,7.384413,6.130410,7.397495,NaN,NaN
2,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.530002,70.030002,72.670076,72.380044,70.119932,67.610017,65.729868,74.451517,73.162897,66.463658
3,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511,7.658320,8.733314,20.438287,27.241982,38.366454,46.046388,52.009312,62.821924,52.396881
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149104,39.809857,57.093048,75.662637,69.322868,92.995001,113.554175,138.897101,86.860582,67.049940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
172,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.908728,33.856769,61.868897,58.034613,63.357780,75.229471,94.426069,140.210618,110.789739,NaN
173,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.044159,42.303896,48.014263,49.891912,74.075110,51.001445,82.338057,84.447716,59.806567,92.823732
174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,"Â©IMF, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [261]:
#removing blank rows
central_debt.drop([0,174,175], inplace = True)

In [262]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479,8.700291,9.154083,8.437266,7.997660,7.384413,6.130410,7.397495,NaN,NaN
2,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.530002,70.030002,72.670076,72.380044,70.119932,67.610017,65.729868,74.451517,73.162897,66.463658
3,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511,7.658320,8.733314,20.438287,27.241982,38.366454,46.046388,52.009312,62.821924,52.396881
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149104,39.809857,57.093048,75.662637,69.322868,92.995001,113.554175,138.897101,86.860582,67.049940
5,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.791048,101.369132,99.071288,86.125894,92.192732,87.699587,81.250837,101.476956,102.357629,90.562166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.156993,36.986822,39.771071,42.082042,41.109164,39.480846,37.599357,39.016290,38.720767,NaN
170,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.231390,33.952136,37.070953,41.549825,42.660734,44.610042,46.111334,61.216669,64.289084,59.776142
171,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
172,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.908728,33.856769,61.868897,58.034613,63.357780,75.229471,94.426069,140.210618,110.789739,NaN
173,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.044159,42.303896,48.014263,49.891912,74.075110,51.001445,82.338057,84.447716,59.806567,92.823732

In [263]:
#standardizing country names
central_debt.replace(name_to_alpha_2, inplace = True)

In [264]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479,8.700291,9.154083,8.437266,7.997660,7.384413,6.130410,7.397495,NaN,NaN
2,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.530002,70.030002,72.670076,72.380044,70.119932,67.610017,65.729868,74.451517,73.162897,66.463658
3,DZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511,7.658320,8.733314,20.438287,27.241982,38.366454,46.046388,52.009312,62.821924,52.396881
4,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149104,39.809857,57.093048,75.662637,69.322868,92.995001,113.554175,138.897101,86.860582,67.049940
5,AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.791048,101.369132,99.071288,86.125894,92.192732,87.699587,81.250837,101.476956,102.357629,90.562166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.156993,36.986822,39.771071,42.082042,41.109164,39.480846,37.599357,39.016290,38.720767,NaN
170,PS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.231390,33.952136,37.070953,41.549825,42.660734,44.610042,46.111334,61.216669,64.289084,59.776142
171,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
172,ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.908728,33.856769,61.868897,58.034613,63.357780,75.229471,94.426069,140.210618,110.789739,NaN
173,ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.044159,42.303896,48.014263,49.891912,74.075110,51.001445,82.338057,84.447716,59.806567,92.823732

In [265]:
#replacing "no data" with np.nan for standardization

In [266]:
central_debt

,Central Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479,8.700291,9.154083,8.437266,7.997660,7.384413,6.130410,7.397495,NaN,NaN
2,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.530002,70.030002,72.670076,72.380044,70.119932,67.610017,65.729868,74.451517,73.162897,66.463658
3,DZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511,7.658320,8.733314,20.438287,27.241982,38.366454,46.046388,52.009312,62.821924,52.396881
4,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149104,39.809857,57.093048,75.662637,69.322868,92.995001,113.554175,138.897101,86.860582,67.049940
5,AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.791048,101.369132,99.071288,86.125894,92.192732,87.699587,81.250837,101.476956,102.357629,90.562166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.156993,36.986822,39.771071,42.082042,41.109164,39.480846,37.599357,39.016290,38.720767,NaN
170,PS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.231390,33.952136,37.070953,41.549825,42.660734,44.610042,46.111334,61.216669,64.289084,59.776142
171,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
172,ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.908728,33.856769,61.868897,58.034613,63.357780,75.229471,94.426069,140.210618,110.789739,NaN
173,ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.044159,42.303896,48.014263,49.891912,74.075110,51.001445,82.338057,84.447716,59.806567,92.823732

In [267]:
#rename col to country
central_debt.rename({"Central Government Debt (Percent of GDP)": "Country"}, axis = 1, inplace = True)

In [268]:
central_debt

,Country,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.904479,8.700291,9.154083,8.437266,7.997660,7.384413,6.130410,7.397495,NaN,NaN
2,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.530002,70.030002,72.670076,72.380044,70.119932,67.610017,65.729868,74.451517,73.162897,66.463658
3,DZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.093511,7.658320,8.733314,20.438287,27.241982,38.366454,46.046388,52.009312,62.821924,52.396881
4,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.149104,39.809857,57.093048,75.662637,69.322868,92.995001,113.554175,138.897101,86.860582,67.049940
5,AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.791048,101.369132,99.071288,86.125894,92.192732,87.699587,81.250837,101.476956,102.357629,90.562166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.156993,36.986822,39.771071,42.082042,41.109164,39.480846,37.599357,39.016290,38.720767,NaN
170,PS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.231390,33.952136,37.070953,41.549825,42.660734,44.610042,46.111334,61.216669,64.289084,59.776142
171,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
172,ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.908728,33.856769,61.868897,58.034613,63.357780,75.229471,94.426069,140.210618,110.789739,NaN
173,ZW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.044159,42.303896,48.014263,49.891912,74.075110,51.001445,82.338057,84.447716,59.806567,92.823732

In [269]:
#converting to long format
central_debt = pd.melt(central_debt, id_vars = 'Country', var_name = 'Year', value_name = 'Central Govt Debt (Percentage of GDP)')

In [270]:
central_debt

      Country  Year  Central Govt Debt (Percentage of GDP)
0          AF  1950                                    NaN
1          AL  1950                                    NaN
2          DZ  1950                                    NaN
3          AO  1950                                    NaN
4          AG  1950                                    NaN
...       ...   ...                                    ...
12624      VN  2022                                    NaN
12625      PS  2022                              59.776142
12626      YE  2022                              73.531359
12627      ZM  2022                                    NaN
12628      ZW  2022                              92.823732

[12629 rows x 3 columns]

In [271]:
central_debt.set_index(['Country', 'Year'], inplace = True)

In [272]:
central_debt

              Central Govt Debt (Percentage of GDP)
Country Year
AF      1950                                    NaN
AL      1950                                    NaN
DZ      1950                                    NaN
AO      1950                                    NaN
AG      1950                                    NaN
...                                             ...
VN      2022                                    NaN
PS      2022                              59.776142
YE      2022                              73.531359
ZM      2022                                    NaN
ZW      2022                              92.823732

[12629 rows x 1 columns]

In [273]:
#reading in general debt data
general_debt = pd.read_csv("Data/general_debt_as_gdp.csv")

In [274]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,"Â©IMF, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [275]:
#removing blank rows
general_debt.drop([0,88,89], inplace = True)

In [276]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,United States,83.126037,72.955032,72.525492,71.753219,73.568066,68.498633,64.726033,62.329546,64.927332,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [277]:
#standardizing country names
general_debt.replace(name_to_alpha_2, inplace = True)

In [278]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.126037,72.955032,72.525492,71.753219,73.568066,68.498633,64.726033,62.329546,64.927332,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [279]:
#replacing "no data" with np.nan for standardization

In [280]:
general_debt

,General Government Debt (Percent of GDP),1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.126037,72.955032,72.525492,71.753219,73.568066,68.498633,64.726033,62.329546,64.927332,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [281]:
#rename col to country
general_debt.rename({"General Government Debt (Percent of GDP)": "Country"}, axis = 1, inplace = True)

In [282]:
general_debt

,Country,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.391063,71.992300,73.716336,73.324410,71.894783,69.472044,67.367670,75.926873,73.877756,67.581205
2,AU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.484850,34.045452,37.751735,40.593482,41.180764,41.762470,46.744039,57.115015,57.575566,55.701839
3,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.011265,83.757940,84.401089,82.548609,78.603451,74.073811,70.639707,82.930030,82.275804,77.786411
4,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.859473,38.790605,53.006888,53.481630,53.159846,47.515236,40.999215,47.493317,41.182010,39.752693
5,BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.485645,107.040873,105.230356,105.005290,102.020222,99.854364,97.617232,112.035422,109.192693,105.270421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,US,83.126037,72.955032,72.525492,71.753219,73.568066,68.498633,64.726033,62.329546,64.927332,...,104.544444,104.541461,105.127978,107.156330,106.207302,107.436714,108.744672,133.483757,126.426366,121.383217
84,UZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.228016,6.087355,6.724146,8.191619,19.274350,19.625930,28.542074,37.106953,35.384998,34.294587
85,VE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.399473,84.896728,129.762232,138.404232,133.609595,174.629459,205.103219,327.720484,250.582804,157.809488
86,VN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.412898,43.642335,46.115999,47.548352,46.319849,43.513707,40.800069,41.262943,39.309678,37.091308
87,YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.431843,48.949944,57.050394,75.348917,83.996819,89.535085,94.609081,98.469524,85.083023,73.531359

In [283]:
#converting to long format
general_debt = pd.melt(general_debt, id_vars = 'Country', var_name = 'Year', value_name = 'General Govt Debt (Percentage of GDP)')

In [284]:
general_debt

     Country  Year  General Govt Debt (Percentage of GDP)
0         AL  1950                                    NaN
1         AU  1950                                    NaN
2         AT  1950                                    NaN
3         BY  1950                                    NaN
4         BE  1950                                    NaN
...      ...   ...                                    ...
6346      US  2022                             121.383217
6347      UZ  2022                              34.294587
6348      VE  2022                             157.809488
6349      VN  2022                              37.091308
6350      YE  2022                              73.531359

[6351 rows x 3 columns]

In [285]:
#setting index to country and year for merging
general_debt.set_index(['Country', 'Year'], inplace = True)

In [286]:
general_debt

              General Govt Debt (Percentage of GDP)
Country Year
AL      1950                                    NaN
AU      1950                                    NaN
AT      1950                                    NaN
BY      1950                                    NaN
BE      1950                                    NaN
...                                             ...
US      2022                             121.383217
UZ      2022                              34.294587
VE      2022                             157.809488
VN      2022                              37.091308
YE      2022                              73.531359

[6351 rows x 1 columns]

In [287]:
loan_debt_data = pd.concat([central_debt, general_debt], axis = 1)

In [288]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
Country,Year,,
AF,1950,NaN,NaN
AL,1950,NaN,NaN
DZ,1950,NaN,NaN
AO,1950,NaN,NaN
AG,1950,NaN,NaN
...,...,...,...
PH,2022,NaN,57.519704
TJ,2022,NaN,34.631164
TZ,2022,NaN,41.622404
AE,2022,NaN,29.957880
UZ,2022,NaN,34.294587

In [289]:
chinese_loan = pd.read_csv("Data/chinese_loan_data.csv")

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\2323119892.py:1: DtypeWarning: Columns (23,45,46,86,87,88,89,91,92,94,95,97) have mixed types. Specify dtype option on import or set low_memory=False.
  chinese_loan = pd.read_csv("Data/chinese_loan_data.csv")

In [290]:
chinese_loan

,AidData Record ID,Recommended For Aggregates,AidData Parent ID,Umbrella,Financier Country,Recipient,Recipient ISO-3,Recipient Region,Commitment Year,Implementation Start Year,...,Geographic Level of Precision Available,ADM1 Level Available,ADM2 Level Available,Geospatial Feature Available,Source Quality Score,Data Completeness Score,Implementation Detail Score,Loan Detail Score,Unnamed: 126,Unnamed: 127
0,94556,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
1,94564,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
2,94565,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,4,3,5.0,NaN,NaN,NaN
3,94567,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,4,3.0,NaN,NaN,NaN
4,94568,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,NaN,...,NaN,NaN,NaN,NaN,5,4,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20980,16239,No,NaN,Yes,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN
20981,16401,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,3,3.0,NaN,NaN,NaN
20982,63472,Yes,715,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,Precise,Yes,Yes,Yes,5,4,3.0,5.0,NaN,NaN
20983,72639,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,5,3,4.0,NaN,NaN,NaN
20984,73615,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,NaN,NaN,NaN,NaN,4,3,1.0,NaN,NaN,NaN

In [291]:
chinese_loan = chinese_loan[chinese_loan["Recommended For Aggregates"] == "Yes"]

In [292]:
chinese_loan

,AidData Record ID,Recommended For Aggregates,AidData Parent ID,Umbrella,Financier Country,Recipient,Recipient ISO-3,Recipient Region,Commitment Year,Implementation Start Year,...,Geographic Level of Precision Available,ADM1 Level Available,ADM2 Level Available,Geospatial Feature Available,Source Quality Score,Data Completeness Score,Implementation Detail Score,Loan Detail Score,Unnamed: 126,Unnamed: 127
0,94556,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
1,94564,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,3,4.0,NaN,NaN,NaN
2,94565,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,4,3,5.0,NaN,NaN,NaN
3,94567,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,2021.0,...,NaN,NaN,NaN,NaN,5,4,3.0,NaN,NaN,NaN
4,94568,Yes,NaN,No,China (People's Republic of),Afghanistan,AFG,Asia,2021,NaN,...,NaN,NaN,NaN,NaN,5,4,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20978,34717,Yes,NaN,No,China (People's Republic of),Zambia,ZMB,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,3,3,4.0,NaN,NaN,NaN
20981,16401,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,NaN,NaN,NaN,NaN,1,3,3.0,NaN,NaN,NaN
20982,63472,Yes,715,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,Precise,Yes,Yes,Yes,5,4,3.0,5.0,NaN,NaN
20983,72639,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,2000.0,...,Precise,Yes,Yes,Yes,5,3,4.0,NaN,NaN,NaN
20984,73615,Yes,NaN,No,China (People's Republic of),Zimbabwe,ZWE,Africa,2000,NaN,...,NaN,NaN,NaN,NaN,4,3,1.0,NaN,NaN,NaN

In [293]:
chinese_loan.columns[45:60]

Index(['Security Agent/Collateral Agent',
       'Security Agent/Collateral Agent Type', 'Collateral',
       ' Amount (Original Currency) ', 'Original Currency', 'Amount Estimated',
       ' Amount (Constant USD 2021) ', ' Amount (Nominal USD) ',
       ' Adjusted Amount (Original Currency) ',
       ' Adjusted Amount (Constant USD 2021) ',
       ' Adjusted Amount (Nominal USD) ', 'Financial Distress',
       'Commitment Date (MM/DD/YYYY)', 'Commitment Date Estimated',
       'Planned Implementation Start Date (MM/DD/YYYY)'],
      dtype='object')

In [294]:
#isolating for only the columns we want
chinese_loan = chinese_loan[["Recipient", "Implementation Start Year", "Intent", "Flow Type Simplified", "Sector Name", "COVID", "Direct Receiving Agencies Type", "Non-Chinese Financier", ' Adjusted Amount (Nominal USD) ']]

In [295]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,NaN,Recipient Government Agency,No,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,No,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,No,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,No,"13,000,000.00"
4,Afghanistan,NaN,Development,Grant,EMERGENCY RESPONSE,NaN,Recipient Government Agency,No,"7,500,000.00"
...,...,...,...,...,...,...,...,...,...
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,NaN,Recipient Government Agency,No,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,NaN,Recipient Government Agency,No,"603,974.73"
20982,Zimbabwe,NaN,Mixed,Loan,"INDUSTRY, MINING, CONSTRUCTION",NaN,Recipient State-owned Company,No,"5,822,316.37"
20983,Zimbabwe,2000.0,Development,Grant,HEALTH,NaN,Recipient Government Agency,No,NaN
20984,Zimbabwe,NaN,Development,Grant,EMERGENCY RESPONSE,NaN,Recipient Government Agency,No,"19,931.00"

In [296]:
#Adding nos to COVID column
chinese_loan['COVID'].fillna("No", inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3051015601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan['COVID'].fillna("No", inplace = True)

In [297]:
chinese_loan["Non-Chinese Financier"].replace({"No": "Chinese Financier", "Yes": "Non-Chinese Financier"}, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\661500757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Non-Chinese Financier"].replace({"No": "Chinese Financier", "Yes": "Non-Chinese Financier"}, inplace = True)

In [298]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,"13,000,000.00"
4,Afghanistan,NaN,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"7,500,000.00"
...,...,...,...,...,...,...,...,...,...
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"603,974.73"
20982,Zimbabwe,NaN,Mixed,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient State-owned Company,Chinese Financier,"5,822,316.37"
20983,Zimbabwe,2000.0,Development,Grant,HEALTH,No,Recipient Government Agency,Chinese Financier,NaN
20984,Zimbabwe,NaN,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"19,931.00"

In [299]:
#dropping years without implementation dates
chinese_loan.dropna(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\643575008.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.dropna(inplace = True)

In [300]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"7,111,455.91"
1,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"12,600,000.00"
2,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"14,400,000.00"
3,Afghanistan,2021.0,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,"13,000,000.00"
6,Afghanistan,2021.0,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"3,600,000.00"
...,...,...,...,...,...,...,...,...,...
20971,Viet Nam,2000.0,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"10,760,000.00"
20972,Viet Nam,2000.0,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"15,316,000.00"
20974,Viet Nam,2000.0,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"20,000.00"
20978,Zambia,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"120,794.95"
20981,Zimbabwe,2000.0,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"603,974.73"

In [301]:
np.unique(chinese_loan["Direct Receiving Agencies Type"])

array(['Chinese Government Agency',
       'Chinese Joint Venture/Special Purpose Vehicle',
       'Chinese Joint Venture/Special Purpose Vehicle|Chinese Joint Venture/Special Purpose Vehicle',
       'Chinese Joint Venture/Special Purpose Vehicle|Chinese State-owned Company',
       'Chinese NGO/CSO/Foundation', 'Chinese Private Sector',
       'Chinese Private Sector|Recipient State-owned Company',
       'Chinese State-owned Company',
       'Chinese State-owned Company|Chinese State-owned Company',
       'Chinese State-owned Company|Recipient Private Sector',
       'Chinese State-owned Company|Recipient State-owned Company',
       'Chinese State-owned Fund',
       'Chinese State-owned Fund|Chinese State-owned Fund',
       'Chinese State-owned Fund|Other Intergovernmental Organization',
       'Other Government Agency',
       'Other Government Agency|Other Government Agency|Recipient Government Agency|Other Government Agency|Other Government Agency',
       'Other Intergovernmental Organization',
       'Other Intergovernmental Organization|Recipient Government Agency|Recipient NGO/CSO/Foundation|Other NGO/CSO/Foundation|Recipient NGO/CSO/Foundation|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency',
       'Other Joint Venture/Special Purpose Vehicle',
       'Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle',
       'Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle',
       'Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle',
       'Other Joint Venture/Special Purpose Vehicle|Recipient State-owned Company',
       'Other Miscellaneous Agency Type', 'Other NGO/CSO/Foundation',
       'Other Private Sector', 'Other State-owned Bank',
       'Other State-owned Fund',
       'Other State-owned Fund|Recipient Government Agency',
       'Recipient Government Agency',
       'Recipient Government Agency|Other Intergovernmental Organization',
       'Recipient Government Agency|Other Joint Venture/Special Purpose Vehicle',
       'Recipient Government Agency|Other State-owned Fund',
       'Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient State-owned Company|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Miscellaneous Agency Type|Recipient Government Agency|Recipient Government Agency',
       'Recipient Government Agency|Recipient Miscellaneous Agency Type',
       'Recipient Government Agency|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Government Agency|Recipient NGO/CSO/Foundation',
       'Recipient Government Agency|Recipient State-owned Company',
       'Recipient Joint Venture/Special Purpose Vehicle',
       'Recipient Joint Venture/Special Purpose Vehicle|Chinese State-owned Company',
       'Recipient Joint Venture/Special Purpose Vehicle|Other Joint Venture/Special Purpose Vehicle',
       'Recipient Joint Venture/Special Purpose Vehicle|Recipient Government Agency',
       'Recipient Joint Venture/Special Purpose Vehicle|Recipient Joint Venture/Special Purpose Vehicle|Recipient Joint Venture/Special Purpose Vehicle',
       'Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Government Agency',
       'Recipient Miscellaneous Agency Type|Recipient Government Agency|Recipient NGO/CSO/Foundation|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Government Agency|Recipient Miscellaneous Agency Type|Recipient Government Agency',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type',
       'Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient Miscellaneous Agency Type|Recipient NGO/CSO/Foundation|Recipient Miscellaneous Agency Type',
       'Recipient NGO/CSO/Foundation',
       'Recipient NGO/CSO/Foundation|Recipient Government Agency',
       'Recipient NGO/CSO/Foundation|Recipient Government Agency|Recipient Government Agency',
       'Recipient NGO/CSO/Foundation|Recipient Miscellaneous Agency Type|Recipient NGO/CSO/Foundation|Recipient NGO/CSO/Foundation',
       'Recipient NGO/CSO/Foundation|Recipient NGO/CSO/Foundation',
       'Recipient Private Sector',
       'Recipient Private Sector|Recipient Private Sector',
       'Recipient Private Sector|Recipient Private Sector|Recipient Private Sector',
       'Recipient Private Sector|Recipient Private Sector|Recipient Private Sector|Recipient Private Sector',
       'Recipient Private Sector|Recipient State-owned Company',
       'Recipient State-owned Bank',
       'Recipient State-owned Bank|Recipient Joint Venture/Special Purpose Vehicle',
       'Recipient State-owned Bank|Recipient State-owned Company',
       'Recipient State-owned Company',
       'Recipient State-owned Company|Recipient Government Agency',
       'Recipient State-owned Company|Recipient State-owned Company',
       'Recipient State-owned Company|Recipient State-owned Company|Recipient State-owned Company',
       'Recipient State-owned Fund'], dtype=object)

In [302]:
chinese_loan["Direct Receiving Agencies Type"] = chinese_loan["Direct Receiving Agencies Type"].apply(lambda x: x.split("|")[0])
chinese_loan["Direct Receiving Agencies Type"] = chinese_loan["Direct Receiving Agencies Type"].apply(lambda x: x.split("/")[0])

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\1317401900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Direct Receiving Agencies Type"] = chinese_loan["Direct Receiving Agencies Type"].apply(lambda x: x.split("|")[0])
C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\1317401900.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Direct Receiving Agencies Type"] = chinese_loan["Direct Receiving Agencies Type"].apply(lambda x: x.split("/")[0])

In [303]:
np.unique(chinese_loan["Direct Receiving Agencies Type"])

array(['Chinese Government Agency', 'Chinese Joint Venture',
       'Chinese NGO', 'Chinese Private Sector',
       'Chinese State-owned Company', 'Chinese State-owned Fund',
       'Other Government Agency', 'Other Intergovernmental Organization',
       'Other Joint Venture', 'Other Miscellaneous Agency Type',
       'Other NGO', 'Other Private Sector', 'Other State-owned Bank',
       'Other State-owned Fund', 'Recipient Government Agency',
       'Recipient Joint Venture', 'Recipient Miscellaneous Agency Type',
       'Recipient NGO', 'Recipient Private Sector',
       'Recipient State-owned Bank', 'Recipient State-owned Company',
       'Recipient State-owned Fund'], dtype=object)

In [304]:
chinese_loan["Implementation Start Year"] = chinese_loan["Implementation Start Year"].astype('int32')

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\828448132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Implementation Start Year"] = chinese_loan["Implementation Start Year"].astype('int32')

In [305]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,Afghanistan,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"7,111,455.91"
1,Afghanistan,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"12,600,000.00"
2,Afghanistan,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"14,400,000.00"
3,Afghanistan,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,"13,000,000.00"
6,Afghanistan,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"3,600,000.00"
...,...,...,...,...,...,...,...,...,...
20971,Viet Nam,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"10,760,000.00"
20972,Viet Nam,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"15,316,000.00"
20974,Viet Nam,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"20,000.00"
20978,Zambia,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"120,794.95"
20981,Zimbabwe,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"603,974.73"

In [306]:
chinese_loan.replace(name_to_alpha_2, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3419558913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.replace(name_to_alpha_2, inplace = True)

In [307]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"7,111,455.91"
1,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"12,600,000.00"
2,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"14,400,000.00"
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,"13,000,000.00"
6,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,"3,600,000.00"
...,...,...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"10,760,000.00"
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,"15,316,000.00"
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,"20,000.00"
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"120,794.95"
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,"603,974.73"

In [308]:
#converted adjusted to float

def remove_space(x):
    one = x
    two = ""
    for s in one:
        if s.isdigit():
            two += s
    return two

chinese_loan["Adjusted Amount (Nominal USD)"] = chinese_loan[" Adjusted Amount (Nominal USD) "].apply(lambda x: remove_space(x))
    

chinese_loan["Adjusted Amount (Nominal USD)"] = pd.to_numeric(chinese_loan["Adjusted Amount (Nominal USD)"], downcast = 'float')

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3437805329.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"] = chinese_loan[" Adjusted Amount (Nominal USD) "].apply(lambda x: remove_space(x))
C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3437805329.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"] = pd.to_numeric(chinese_loan["Adjusted Amount (Nominal USD)"], downcast = 'float')

In [309]:
chinese_loan.drop(" Adjusted Amount (Nominal USD) ", axis = 1, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3540160246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.drop(" Adjusted Amount (Nominal USD) ", axis = 1, inplace = True)

In [310]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,7.111456e+08
1,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,1.260000e+09
2,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,1.440000e+09
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,1.300000e+09
6,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,3.600000e+08
...,...,...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,1.076000e+09
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,1.531600e+09
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,2.000000e+06
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,1.207950e+07
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,6.039747e+07

In [311]:
#categorizing loan amounts into 4 even blocks

#chinese_loan = chinese_loan[chinese_loan["Adjusted Amount (Nominal USD)"] > 0]
#["Adjusted Amount (Nominal USD)"], bins = pd.cut(chinese_loan["Adjusted Amount (Nominal USD)"].to_numpy(), bins = 4, retbins = True)
#bins

In [312]:
#chinese_loan["Adjusted Amount (Nominal USD)"][0]

In [313]:
#chinese_loan

In [314]:
#chinese_loan.replace({pd.Interval(-1499998698.7, 375000000975.0, closed = "right"): "Grade One",
                      #pd.Interval(375000000975.0, 750000000650.0, closed = "right"): "Grade Two",
                      #pd.Interval(750000000650.0, 1125000000325.0, closed = "right"): "Grade Three",
                      #pd.Interval(1125000000325.0, 1500000000000.0, closed = "right"): "Grade Four"
                     #}, inplace = True)

In [315]:
#chinese_loan

In [316]:
#Limiting recipients to only countries

chinese_loan = chinese_loan[chinese_loan["Recipient"].isin(alpha_2_to_name.keys())]
np.unique(chinese_loan["Recipient"])

array(['AF', 'AG', 'AL', 'AM', 'AO', 'AR', 'AZ', 'BA', 'BB', 'BD', 'BF',
       'BG', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BW', 'BY', 'CD', 'CF',
       'CG', 'CI', 'CK', 'CL', 'CM', 'CO', 'CR', 'CU', 'CV', 'DJ', 'DM',
       'DO', 'DZ', 'EC', 'EG', 'ER', 'ET', 'FJ', 'FM', 'GA', 'GD', 'GE',
       'GH', 'GM', 'GN', 'GQ', 'GW', 'GY', 'HN', 'HT', 'ID', 'IL', 'IN',
       'IQ', 'IR', 'JM', 'JO', 'KE', 'KG', 'KH', 'KI', 'KM', 'KP', 'KZ',
       'LA', 'LB', 'LC', 'LK', 'LR', 'LS', 'LY', 'MA', 'MD', 'ME', 'MG',
       'MH', 'MK', 'ML', 'MM', 'MN', 'MR', 'MU', 'MV', 'MW', 'MX', 'MY',
       'MZ', 'NA', 'NE', 'NG', 'NI', 'NP', 'NR', 'NU', 'OM', 'PA', 'PE',
       'PG', 'PH', 'PK', 'PS', 'PY', 'RO', 'RS', 'RU', 'RW', 'SB', 'SC',
       'SD', 'SL', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SY', 'TD', 'TG',
       'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TZ', 'UA', 'UG',
       'UY', 'UZ', 'VE', 'VN', 'VU', 'WS', 'YE', 'ZA', 'ZM', 'ZW'],
      dtype=object)

In [317]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,7.111456e+08
1,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,1.260000e+09
2,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,1.440000e+09
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,1.300000e+09
6,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,3.600000e+08
...,...,...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,1.076000e+09
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,1.531600e+09
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,2.000000e+06
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,1.207950e+07
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,6.039747e+07

In [318]:
usd = chinese_loan[["Recipient", "Implementation Start Year", "Adjusted Amount (Nominal USD)"]]

In [319]:
usd

      Recipient  Implementation Start Year  Adjusted Amount (Nominal USD)
0            AF                       2021                   7.111456e+08
1            AF                       2021                   1.260000e+09
2            AF                       2021                   1.440000e+09
3            AF                       2021                   1.300000e+09
6            AF                       2021                   3.600000e+08
...         ...                        ...                            ...
20971        VN                       2000                   1.076000e+09
20972        VN                       2000                   1.531600e+09
20974        VN                       2000                   2.000000e+06
20978        ZM                       2000                   1.207950e+07
20981        ZW                       2000                   6.039747e+07

[5771 rows x 3 columns]

In [320]:
average = usd.groupby(["Recipient", "Implementation Start Year"]).mean()
total = usd.groupby(["Recipient", "Implementation Start Year"]).sum()

In [321]:
average.rename({"Adjusted Amount (Nominal USD)": "Average Loan Amount (Nominal USD)"}, axis = 1, inplace = True)
total.rename({"Adjusted Amount (Nominal USD)": "Total Loan Amount (Nominal USD)"}, axis = 1, inplace = True)

In [322]:
chinese_loan["Adjusted Amount (Nominal USD)"], bins = pd.qcut(chinese_loan["Adjusted Amount (Nominal USD)"], q = 4, labels = ["Q1", "Q2", "Q3", "Q4"], retbins = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\2657200072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan["Adjusted Amount (Nominal USD)"], bins = pd.qcut(chinese_loan["Adjusted Amount (Nominal USD)"], q = 4, labels = ["Q1", "Q2", "Q3", "Q4"], retbins = True)

In [323]:

chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,Q3
1,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q3
2,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q3
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,Q3
6,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q2
...,...,...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,Q3
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,Q3
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,Q1
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,Q1
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,Q2

In [324]:
chinese_loan.dropna(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\1448102153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chinese_loan.dropna(inplace = True)

In [325]:
chinese_loan

,Recipient,Implementation Start Year,Intent,Flow Type Simplified,Sector Name,COVID,Direct Receiving Agencies Type,Non-Chinese Financier,Adjusted Amount (Nominal USD)
0,AF,2021,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,Q3
1,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q3
2,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q3
3,AF,2021,Development,Grant,EMERGENCY RESPONSE,Yes,Recipient Government Agency,Chinese Financier,Q3
6,AF,2021,Development,Grant,HEALTH,Yes,Recipient Government Agency,Chinese Financier,Q2
...,...,...,...,...,...,...,...,...,...
20971,VN,2000,Development,Grant,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,Q3
20972,VN,2000,Development,Loan,"INDUSTRY, MINING, CONSTRUCTION",No,Recipient Government Agency,Chinese Financier,Q3
20974,VN,2000,Development,Grant,EMERGENCY RESPONSE,No,Recipient Government Agency,Chinese Financier,Q1
20978,ZM,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,Q1
20981,ZW,2000,Development,Grant,GOVERNMENT AND CIVIL SOCIETY,No,Recipient Government Agency,Chinese Financier,Q2

In [326]:
sectors = np.unique(chinese_loan["Sector Name"])
intents = np.unique(chinese_loan["Intent"])
flows = np.unique(chinese_loan["Flow Type Simplified"])
covid = np.unique(chinese_loan["COVID"])
receiving_agencies = np.unique(chinese_loan["Direct Receiving Agencies Type"])
financiers = np.unique(chinese_loan["Non-Chinese Financier"])
amounts = np.unique(chinese_loan["Adjusted Amount (Nominal USD)"])

In [327]:
chinese_loan = chinese_loan.groupby(['Recipient', 'Implementation Start Year']).apply(lambda x: x.drop(['Recipient', 'Implementation Start Year'], axis = 1)
                                                                                                       .apply(pd.Series.value_counts))

In [328]:
chinese_loan

                                                                         Intent  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                       NaN
                                    Development                             1.0
                                    EMERGENCY RESPONSE                      NaN
                                    Grant                                   NaN
                                    No                                      NaN
...                                                                         ...
ZW        2021                      Q4                                      NaN
                                    Recipient Government Agency             NaN
                                    Recipient Miscellaneous Agency Type     NaN
                                    WATER SUPPLY AND SANITATION             NaN
                                    Yes                                     NaN

                                                                         Flow Type Simplified  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                                     NaN
                                    Development                                           NaN
                                    EMERGENCY RESPONSE                                    NaN
                                    Grant                                                 1.0
                                    No                                                    NaN
...                                                                                       ...
ZW        2021                      Q4                                                    NaN
                                    Recipient Government Agency                           NaN
                                    Recipient Miscellaneous Agency Type                   NaN
                                    WATER SUPPLY AND SANITATION                           NaN
                                    Yes                                                   NaN

                                                                         Sector Name  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                            NaN
                                    Development                                  NaN
                                    EMERGENCY RESPONSE                           1.0
                                    Grant                                        NaN
                                    No                                           NaN
...                                                                              ...
ZW        2021                      Q4                                           NaN
                                    Recipient Government Agency                  NaN
                                    Recipient Miscellaneous Agency Type          NaN
                                    WATER SUPPLY AND SANITATION                  1.0
                                    Yes                                          NaN

                                                                         COVID  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                      NaN
                                    Development                            NaN
                                    EMERGENCY RESPONSE                     NaN
                                    Grant                                  NaN
                                    No                                     1.0
...                                                                        ...
ZW        2021                      Q4                                     NaN
                                    Recipient Government Agency            NaN
                                    Recipient Miscellaneous Agency Type    NaN
                                    WATER SUPPLY AND SANITATION            NaN
                                    Yes                                    6.0

                                                                         Direct Receiving Agencies Type  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                                               NaN
                                    Development                                                     NaN
                                    EMERGENCY RESPONSE                                              NaN
                                    Grant                                                           NaN
                                    No                                                              NaN
...                                                                                                 ...
ZW        2021                      Q4                                                              NaN
                                    Recipient Government Agency                                     8.0
                                    Recipient Miscellaneous Agency Type                             1.0
                                    WATER SUPPLY AND SANITATION                                     NaN
                                    Yes                                                             NaN

                                                                         Non-Chinese Financier  \
Recipient Implementation Start Year
AF        2002                      Chinese Financier                                      1.0
                                    Development                                            NaN
                                    EMERGENCY RESPONSE                                     NaN
                                    Grant                                                  NaN
                                    No                                                     NaN
...                                                                                        ...
ZW        2021                      Q4                                                     NaN
                                    Recipient Government Agency                            NaN
                                    Recipient Miscellaneous Agency Type                    NaN
                                    WATER SUPPLY AND SANITATION                            NaN
                                    Yes                                                    NaN

                                                                         Adjusted Amount (Nominal USD)
Recipient Implementation Start Year
AF        2002                      Chinese Financier                                              NaN
                                    Development                                                    NaN
                                    EMERGENCY RESPONSE                                             NaN
                                    Grant                                                          NaN
                                    No                                                             NaN
...                                                                                                ...
ZW        2021                      Q4                                                             2.0
                                    Recipient Government Agency                                    NaN
                                    Recipient Miscellaneous Agency Type                            NaN
                                    WATER SUPPLY AND SANITATION                                    NaN
                                    Yes                                                            NaN

[22062 rows x 7 columns]

In [329]:
def return_not_na(x):
    for item in x:
        if pd.notna(item):
            return item


count = chinese_loan.apply(lambda x: return_not_na(x), axis = 1)
chinese_loan.drop(["Intent", "Flow Type Simplified", "Sector Name", "COVID", "Adjusted Amount (Nominal USD)", "Direct Receiving Agencies Type", "Non-Chinese Financier"], axis = 1, inplace = True)
chinese_loan["Count"] = count

In [330]:
chinese_loan

                                                                         Count
Recipient Implementation Start Year
AF        2002                      Chinese Financier                      1.0
                                    Development                            1.0
                                    EMERGENCY RESPONSE                     1.0
                                    Grant                                  1.0
                                    No                                     1.0
...                                                                        ...
ZW        2021                      Q4                                     2.0
                                    Recipient Government Agency            8.0
                                    Recipient Miscellaneous Agency Type    1.0
                                    WATER SUPPLY AND SANITATION            1.0
                                    Yes                                    6.0

[22062 rows x 1 columns]

In [331]:
chinese_loan.reset_index(inplace = True)

In [332]:
chinese_loan

,Recipient,Implementation Start Year,level_2,Count
0,AF,2002,Chinese Financier,1.0
1,AF,2002,Development,1.0
2,AF,2002,EMERGENCY RESPONSE,1.0
3,AF,2002,Grant,1.0
4,AF,2002,No,1.0
...,...,...,...,...
22057,ZW,2021,Q4,2.0
22058,ZW,2021,Recipient Government Agency,8.0
22059,ZW,2021,Recipient Miscellaneous Agency Type,1.0
22060,ZW,2021,WATER SUPPLY AND SANITATION,1.0
22061,ZW,2021,Yes,6.0

In [333]:
chinese_loan = chinese_loan.pivot(index = ['Recipient', 'Implementation Start Year'], columns = 'level_2')

In [334]:
chinese_loan

                                                      Count  \
level_2                             ACTION RELATING TO DEBT
Recipient Implementation Start Year
AF        2002                                          NaN
          2004                                          1.0
          2005                                          NaN
          2006                                          NaN
          2007                                          NaN
...                                                     ...
ZW        2017                                          NaN
          2018                                          NaN
          2019                                          NaN
          2020                                          NaN
          2021                                          NaN

                                                                    \
level_2                             AGRICULTURE, FORESTRY, FISHING
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 1.0
          2018                                                 1.0
          2019                                                 1.0
          2020                                                 NaN
          2021                                                 NaN

                                                                    \
level_2                             BANKING AND FINANCIAL SERVICES
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

                                                                 \
level_2                             BUSINESS AND OTHER SERVICES
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

                                                                      \
level_2                             COMMUNICATIONS Chinese Financier
Recipient Implementation Start Year
AF        2002                                 NaN               1.0
          2004                                 NaN               3.0
          2005                                 NaN               1.0
          2006                                 NaN               2.0
          2007                                 NaN               2.0
...                                            ...               ...
ZW        2017                                 NaN               3.0
          2018                                 1.0               4.0
          2019                                 NaN               7.0
          2020                                 NaN              11.0
          2021                                 1.0               9.0

                                                               \
level_2                             Chinese Government Agency
Recipient Implementation Start Year
AF        2002                                            NaN
          2004                                            NaN
          2005                                            NaN
          2006                                            NaN
          2007                                            NaN
...                                                       ...
ZW        2017                                            NaN
          2018                                            NaN
          2019                                            NaN
          2020                                            NaN
          2021                                            NaN

                                                                       \
level_2                             Chinese Joint Venture Chinese NGO
Recipient Implementation Start Year
AF        2002                                        NaN         NaN
          2004                                        NaN         NaN
          2005                                        NaN         NaN
          2006                                        NaN         NaN
          2007                                        NaN         NaN
...                                                   ...         ...
ZW        2017                                        NaN         NaN
          2018                                        NaN         NaN
          2019                                        NaN         NaN
          2020                                        NaN         NaN
          2021                                        NaN         NaN

                                                            ...  \
level_2                             Chinese Private Sector  ...
Recipient Implementation Start Year                         ...
AF        2002                                         NaN  ...
          2004                                         NaN  ...
          2005                                         NaN  ...
          2006                                         NaN  ...
          2007                                         NaN  ...
...                                                    ...  ...
ZW        2017                                         NaN  ...
          2018                                         NaN  ...
          2019                                         NaN  ...
          2020                                         NaN  ...
          2021                                         NaN  ...

                                                                \
level_2                             Recipient State-owned Bank
Recipient Implementation Start Year
AF        2002                                             NaN
          2004                                             NaN
          2005                                             NaN
          2006                                             NaN
          2007                                             NaN
...                                                        ...
ZW        2017                                             NaN
          2018                                             NaN
          2019                                             NaN
          2020                                             NaN
          2021                                             NaN

                                                                   \
level_2                             Recipient State-owned Company
Recipient Implementation Start Year
AF        2002                                                NaN
          2004                                                NaN
          2005                                                NaN
          2006                                                NaN
          2007                                                NaN
...                                                           ...
ZW        2017                                                NaN
          2018                                                NaN
          2019                                                NaN
          2020                                                NaN
          2021                                                NaN

                                                                \
level_2                             Recipient State-owned Fund
Recipient Implementation Start Year
AF        2002                                             NaN
          2004                                             NaN
          2005                                             NaN
          2006                                             NaN
          2007                                             NaN
...                                                        ...
ZW        2017                                             NaN
          2018                                             NaN
          2019                                             NaN
          2020                                             NaN
          2021                                             NaN

                                                      \
level_2                             Representational
Recipient Implementation Start Year
AF        2002                                   NaN
          2004                                   NaN
          2005                                   NaN
          2006                                   NaN
          2007                                   NaN
...                                              ...
ZW        2017                                   NaN
          2018                                   NaN
          2019                                   NaN
          2020                                   NaN
          2021                                   NaN

                                                                    \
level_2                             TRADE POLICIES AND REGULATIONS
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

                                                           \
level_2                             TRANSPORT AND STORAGE
Recipient Implementation Start Year
AF        2002                                        NaN
          2004                                        NaN
          2005                                        NaN
          2006                                        NaN
          2007                                        NaN
...                                                   ...
ZW        2017                                        NaN
          2018                                        1.0
          2019                                        NaN
          2020                                        NaN
          2021                                        NaN

                                                                   \
level_2                             UNALLOCATED/UNSPECIFIED Vague
Recipient Implementation Start Year
AF        2002                                          NaN   NaN
          2004                                          NaN   NaN
          2005                                          NaN   NaN
          2006                                          NaN   NaN
          2007                                          NaN   NaN
...                                                     ...   ...
ZW        2017                                          NaN   NaN
          2018                                          NaN   NaN
          2019                                          NaN   NaN
          2020                                          NaN   NaN
          2021                                          NaN   NaN


level_2                             WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2002                                              NaN   NaN
          2004                                              1.0   NaN
          2005                                              NaN   NaN
          2006                                              NaN   NaN
          2007                                              NaN   NaN
...                                                         ...   ...
ZW        2017                                              NaN   NaN
          2018                                              NaN   NaN
          2019                                              NaN   NaN
          2020                                              NaN  11.0
          2021                                              1.0   6.0

[1811 rows x 61 columns]

In [335]:
chinese_loan.columns = chinese_loan.columns.droplevel(level = 0)

In [336]:
chinese_loan

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2002                                           NaN
          2004                                           1.0
          2005                                           NaN
          2006                                           NaN
          2007                                           NaN
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

level_2                              BANKING AND FINANCIAL SERVICES  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              BUSINESS AND OTHER SERVICES  \
Recipient Implementation Start Year
AF        2002                                               NaN
          2004                                               NaN
          2005                                               NaN
          2006                                               NaN
          2007                                               NaN
...                                                          ...
ZW        2017                                               NaN
          2018                                               NaN
          2019                                               NaN
          2020                                               NaN
          2021                                               NaN

level_2                              COMMUNICATIONS  Chinese Financier  \
Recipient Implementation Start Year
AF        2002                                  NaN                1.0
          2004                                  NaN                3.0
          2005                                  NaN                1.0
          2006                                  NaN                2.0
          2007                                  NaN                2.0
...                                             ...                ...
ZW        2017                                  NaN                3.0
          2018                                  1.0                4.0
          2019                                  NaN                7.0
          2020                                  NaN               11.0
          2021                                  1.0                9.0

level_2                              Chinese Government Agency  \
Recipient Implementation Start Year
AF        2002                                             NaN
          2004                                             NaN
          2005                                             NaN
          2006                                             NaN
          2007                                             NaN
...                                                        ...
ZW        2017                                             NaN
          2018                                             NaN
          2019                                             NaN
          2020                                             NaN
          2021                                             NaN

level_2                              Chinese Joint Venture  Chinese NGO  \
Recipient Implementation Start Year
AF        2002                                         NaN          NaN
          2004                                         NaN          NaN
          2005                                         NaN          NaN
          2006                                         NaN          NaN
          2007                                         NaN          NaN
...                                                    ...          ...
ZW        2017                                         NaN          NaN
          2018                                         NaN          NaN
          2019                                         NaN          NaN
          2020                                         NaN          NaN
          2021                                         NaN          NaN

level_2                              Chinese Private Sector  ...  \
Recipient Implementation Start Year                          ...
AF        2002                                          NaN  ...
          2004                                          NaN  ...
          2005                                          NaN  ...
          2006                                          NaN  ...
          2007                                          NaN  ...
...                                                     ...  ...
ZW        2017                                          NaN  ...
          2018                                          NaN  ...
          2019                                          NaN  ...
          2020                                          NaN  ...
          2021                                          NaN  ...

level_2                              Recipient State-owned Bank  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

level_2                              Recipient State-owned Company  \
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

level_2                              Recipient State-owned Fund  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

level_2                              Representational  \
Recipient Implementation Start Year
AF        2002                                    NaN
          2004                                    NaN
          2005                                    NaN
          2006                                    NaN
          2007                                    NaN
...                                               ...
ZW        2017                                    NaN
          2018                                    NaN
          2019                                    NaN
          2020                                    NaN
          2021                                    NaN

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2002                                         NaN
          2004                                         NaN
          2005                                         NaN
          2006                                         NaN
          2007                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

level_2                              UNALLOCATED/UNSPECIFIED  Vague  \
Recipient Implementation Start Year
AF        2002                                           NaN    NaN
          2004                                           NaN    NaN
          2005                                           NaN    NaN
          2006                                           NaN    NaN
          2007                                           NaN    NaN
...                                                      ...    ...
ZW        2017                                           NaN    NaN
          2018                                           NaN    NaN
          2019                                           NaN    NaN
          2020                                           NaN    NaN
          2021                                           NaN    NaN

level_2                              WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2002                                               NaN   NaN
          2004                                               1.0   NaN
          2005                                               NaN   NaN
          2006                                               NaN   NaN
          2007                                               NaN   NaN
...                                                          ...   ...
ZW        2017                                               NaN   NaN
          2018                                               NaN   NaN
          2019                                               NaN   NaN
          2020                                               NaN  11.0
          2021                                               1.0   6.0

[1811 rows x 61 columns]

In [337]:
chinese_loan

level_2                              ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2002                                           NaN
          2004                                           1.0
          2005                                           NaN
          2006                                           NaN
          2007                                           NaN
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

level_2                              AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

level_2                              BANKING AND FINANCIAL SERVICES  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              BUSINESS AND OTHER SERVICES  \
Recipient Implementation Start Year
AF        2002                                               NaN
          2004                                               NaN
          2005                                               NaN
          2006                                               NaN
          2007                                               NaN
...                                                          ...
ZW        2017                                               NaN
          2018                                               NaN
          2019                                               NaN
          2020                                               NaN
          2021                                               NaN

level_2                              COMMUNICATIONS  Chinese Financier  \
Recipient Implementation Start Year
AF        2002                                  NaN                1.0
          2004                                  NaN                3.0
          2005                                  NaN                1.0
          2006                                  NaN                2.0
          2007                                  NaN                2.0
...                                             ...                ...
ZW        2017                                  NaN                3.0
          2018                                  1.0                4.0
          2019                                  NaN                7.0
          2020                                  NaN               11.0
          2021                                  1.0                9.0

level_2                              Chinese Government Agency  \
Recipient Implementation Start Year
AF        2002                                             NaN
          2004                                             NaN
          2005                                             NaN
          2006                                             NaN
          2007                                             NaN
...                                                        ...
ZW        2017                                             NaN
          2018                                             NaN
          2019                                             NaN
          2020                                             NaN
          2021                                             NaN

level_2                              Chinese Joint Venture  Chinese NGO  \
Recipient Implementation Start Year
AF        2002                                         NaN          NaN
          2004                                         NaN          NaN
          2005                                         NaN          NaN
          2006                                         NaN          NaN
          2007                                         NaN          NaN
...                                                    ...          ...
ZW        2017                                         NaN          NaN
          2018                                         NaN          NaN
          2019                                         NaN          NaN
          2020                                         NaN          NaN
          2021                                         NaN          NaN

level_2                              Chinese Private Sector  ...  \
Recipient Implementation Start Year                          ...
AF        2002                                          NaN  ...
          2004                                          NaN  ...
          2005                                          NaN  ...
          2006                                          NaN  ...
          2007                                          NaN  ...
...                                                     ...  ...
ZW        2017                                          NaN  ...
          2018                                          NaN  ...
          2019                                          NaN  ...
          2020                                          NaN  ...
          2021                                          NaN  ...

level_2                              Recipient State-owned Bank  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

level_2                              Recipient State-owned Company  \
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

level_2                              Recipient State-owned Fund  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

level_2                              Representational  \
Recipient Implementation Start Year
AF        2002                                    NaN
          2004                                    NaN
          2005                                    NaN
          2006                                    NaN
          2007                                    NaN
...                                               ...
ZW        2017                                    NaN
          2018                                    NaN
          2019                                    NaN
          2020                                    NaN
          2021                                    NaN

level_2                              TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

level_2                              TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2002                                         NaN
          2004                                         NaN
          2005                                         NaN
          2006                                         NaN
          2007                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

level_2                              UNALLOCATED/UNSPECIFIED  Vague  \
Recipient Implementation Start Year
AF        2002                                           NaN    NaN
          2004                                           NaN    NaN
          2005                                           NaN    NaN
          2006                                           NaN    NaN
          2007                                           NaN    NaN
...                                                      ...    ...
ZW        2017                                           NaN    NaN
          2018                                           NaN    NaN
          2019                                           NaN    NaN
          2020                                           NaN    NaN
          2021                                           NaN    NaN

level_2                              WATER SUPPLY AND SANITATION   Yes
Recipient Implementation Start Year
AF        2002                                               NaN   NaN
          2004                                               1.0   NaN
          2005                                               NaN   NaN
          2006                                               NaN   NaN
          2007                                               NaN   NaN
...                                                          ...   ...
ZW        2017                                               NaN   NaN
          2018                                               NaN   NaN
          2019                                               NaN   NaN
          2020                                               NaN  11.0
          2021                                               1.0   6.0

[1811 rows x 61 columns]

In [338]:
chinese_loan = pd.concat([chinese_loan, average, total], axis = 1)

In [339]:
chinese_loan

                                     ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2002                                           NaN
          2004                                           1.0
          2005                                           NaN
          2006                                           NaN
          2007                                           NaN
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

                                     AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

                                     BANKING AND FINANCIAL SERVICES  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

                                     BUSINESS AND OTHER SERVICES  \
Recipient Implementation Start Year
AF        2002                                               NaN
          2004                                               NaN
          2005                                               NaN
          2006                                               NaN
          2007                                               NaN
...                                                          ...
ZW        2017                                               NaN
          2018                                               NaN
          2019                                               NaN
          2020                                               NaN
          2021                                               NaN

                                     COMMUNICATIONS  Chinese Financier  \
Recipient Implementation Start Year
AF        2002                                  NaN                1.0
          2004                                  NaN                3.0
          2005                                  NaN                1.0
          2006                                  NaN                2.0
          2007                                  NaN                2.0
...                                             ...                ...
ZW        2017                                  NaN                3.0
          2018                                  1.0                4.0
          2019                                  NaN                7.0
          2020                                  NaN               11.0
          2021                                  1.0                9.0

                                     Chinese Government Agency  \
Recipient Implementation Start Year
AF        2002                                             NaN
          2004                                             NaN
          2005                                             NaN
          2006                                             NaN
          2007                                             NaN
...                                                        ...
ZW        2017                                             NaN
          2018                                             NaN
          2019                                             NaN
          2020                                             NaN
          2021                                             NaN

                                     Chinese Joint Venture  Chinese NGO  \
Recipient Implementation Start Year
AF        2002                                         NaN          NaN
          2004                                         NaN          NaN
          2005                                         NaN          NaN
          2006                                         NaN          NaN
          2007                                         NaN          NaN
...                                                    ...          ...
ZW        2017                                         NaN          NaN
          2018                                         NaN          NaN
          2019                                         NaN          NaN
          2020                                         NaN          NaN
          2021                                         NaN          NaN

                                     Chinese Private Sector  ...  \
Recipient Implementation Start Year                          ...
AF        2002                                          NaN  ...
          2004                                          NaN  ...
          2005                                          NaN  ...
          2006                                          NaN  ...
          2007                                          NaN  ...
...                                                     ...  ...
ZW        2017                                          NaN  ...
          2018                                          NaN  ...
          2019                                          NaN  ...
          2020                                          NaN  ...
          2021                                          NaN  ...

                                     Recipient State-owned Fund  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

                                     Representational  \
Recipient Implementation Start Year
AF        2002                                    NaN
          2004                                    NaN
          2005                                    NaN
          2006                                    NaN
          2007                                    NaN
...                                               ...
ZW        2017                                    NaN
          2018                                    NaN
          2019                                    NaN
          2020                                    NaN
          2021                                    NaN

                                     TRADE POLICIES AND REGULATIONS  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  NaN
          2018                                                  NaN
          2019                                                  NaN
          2020                                                  NaN
          2021                                                  NaN

                                     TRANSPORT AND STORAGE  \
Recipient Implementation Start Year
AF        2002                                         NaN
          2004                                         NaN
          2005                                         NaN
          2006                                         NaN
          2007                                         NaN
...                                                    ...
ZW        2017                                         NaN
          2018                                         1.0
          2019                                         NaN
          2020                                         NaN
          2021                                         NaN

                                     UNALLOCATED/UNSPECIFIED  Vague  \
Recipient Implementation Start Year
AF        2002                                           NaN    NaN
          2004                                           NaN    NaN
          2005                                           NaN    NaN
          2006                                           NaN    NaN
          2007                                           NaN    NaN
...                                                      ...    ...
ZW        2017                                           NaN    NaN
          2018                                           NaN    NaN
          2019                                           NaN    NaN
          2020                                           NaN    NaN
          2021                                           NaN    NaN

                                     WATER SUPPLY AND SANITATION   Yes  \
Recipient Implementation Start Year
AF        2002                                               NaN   NaN
          2004                                               1.0   NaN
          2005                                               NaN   NaN
          2006                                               NaN   NaN
          2007                                               NaN   NaN
...                                                          ...   ...
ZW        2017                                               NaN   NaN
          2018                                               NaN   NaN
          2019                                               NaN   NaN
          2020                                               NaN  11.0
          2021                                               1.0   6.0

                                     Average Loan Amount (Nominal USD)  \
Recipient Implementation Start Year
AF        2002                                            3.624493e+08
          2004                                            1.002966e+09
          2005                                            1.000000e+08
          2006                                            1.300000e+09
          2007                                            5.358857e+08
...                                                                ...
ZW        2017                                            5.200000e+07
          2018                                            2.547125e+10
          2019                                            6.159234e+08
          2020                                            1.772421e+07
          2021                                            2.216556e+09

                                     Total Loan Amount (Nominal USD)
Recipient Implementation Start Year
AF        2002                                          3.624493e+08
          2004                                          3.008898e+09
          2005                                          1.000000e+08
          2006                                          2.600000e+09
          2007                                          1.071771e+09
...                                                              ...
ZW        2017                                          1.560000e+08
          2018                                          1.273562e+11
          2019                                          4.311464e+09
          2020                                          1.949663e+08
          2021                                          1.994900e+10

[1811 rows x 63 columns]

In [340]:
new_order = np.concatenate((flows, intents, sectors, covid, receiving_agencies, financiers, amounts))

In [341]:
new_order

array(['Grant', 'Loan', 'Vague', 'Commercial', 'Development', 'Mixed',
       'Representational', 'ACTION RELATING TO DEBT',
       'AGRICULTURE, FORESTRY, FISHING', 'BANKING AND FINANCIAL SERVICES',
       'BUSINESS AND OTHER SERVICES', 'COMMUNICATIONS',
       'DEVELOPMENTAL FOOD AID/FOOD SECURITY ASSISTANCE',
       'DISASTER PREVENTION AND PREPAREDNESS', 'EDUCATION',
       'EMERGENCY RESPONSE', 'ENERGY', 'GENERAL BUDGET SUPPORT',
       'GENERAL ENVIRONMENTAL PROTECTION', 'GOVERNMENT AND CIVIL SOCIETY',
       'HEALTH', 'INDUSTRY, MINING, CONSTRUCTION',
       'OTHER COMMODITY ASSISTANCE', 'OTHER MULTISECTOR',
       'OTHER SOCIAL INFRASTRUCTURE AND SERVICES',
       'POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH',
       'RECONSTRUCTION RELIEF AND REHABILITATION',
       'TRADE POLICIES AND REGULATIONS', 'TRANSPORT AND STORAGE',
       'UNALLOCATED/UNSPECIFIED', 'WATER SUPPLY AND SANITATION', 'No',
       'Yes', 'Chinese Government Agency', 'Chinese Joint Venture',
       'Chinese NGO', 'Chinese Private Sector',
       'Chinese State-owned Company', 'Chinese State-owned Fund',
       'Other Government Agency', 'Other Intergovernmental Organization',
       'Other Joint Venture', 'Other Miscellaneous Agency Type',
       'Other NGO', 'Other Private Sector', 'Other State-owned Bank',
       'Other State-owned Fund', 'Recipient Government Agency',
       'Recipient Joint Venture', 'Recipient Miscellaneous Agency Type',
       'Recipient NGO', 'Recipient Private Sector',
       'Recipient State-owned Bank', 'Recipient State-owned Company',
       'Recipient State-owned Fund', 'Chinese Financier',
       'Non-Chinese Financier', 'Q1', 'Q2', 'Q3', 'Q4'], dtype=object)

In [342]:
new_order = np.concatenate((new_order, ["Average Loan Amount (Nominal USD)", "Total Loan Amount (Nominal USD)"]))

In [343]:
chinese_loan = chinese_loan[new_order]
chinese_loan

                                     Grant  Loan  Vague  Commercial  \
Recipient Implementation Start Year
AF        2002                         1.0   NaN    NaN         NaN
          2004                         3.0   NaN    NaN         NaN
          2005                         1.0   NaN    NaN         NaN
          2006                         2.0   NaN    NaN         NaN
          2007                         2.0   NaN    NaN         NaN
...                                    ...   ...    ...         ...
ZW        2017                         3.0   NaN    NaN         NaN
          2018                         3.0   2.0    NaN         NaN
          2019                         7.0   NaN    NaN         NaN
          2020                        11.0   NaN    NaN         NaN
          2021                         7.0   2.0    NaN         NaN

                                     Development  Mixed  Representational  \
Recipient Implementation Start Year
AF        2002                               1.0    NaN               NaN
          2004                               3.0    NaN               NaN
          2005                               1.0    NaN               NaN
          2006                               2.0    NaN               NaN
          2007                               2.0    NaN               NaN
...                                          ...    ...               ...
ZW        2017                               3.0    NaN               NaN
          2018                               4.0    1.0               NaN
          2019                               7.0    NaN               NaN
          2020                              11.0    NaN               NaN
          2021                               9.0    NaN               NaN

                                     ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2002                                           NaN
          2004                                           1.0
          2005                                           NaN
          2006                                           NaN
          2007                                           NaN
...                                                      ...
ZW        2017                                           NaN
          2018                                           NaN
          2019                                           NaN
          2020                                           NaN
          2021                                           NaN

                                     AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2002                                                  NaN
          2004                                                  NaN
          2005                                                  NaN
          2006                                                  NaN
          2007                                                  NaN
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  NaN
          2021                                                  NaN

                                     BANKING AND FINANCIAL SERVICES  ...  \
Recipient Implementation Start Year                                  ...
AF        2002                                                  NaN  ...
          2004                                                  NaN  ...
          2005                                                  NaN  ...
          2006                                                  NaN  ...
          2007                                                  NaN  ...
...                                                             ...  ...
ZW        2017                                                  NaN  ...
          2018                                                  NaN  ...
          2019                                                  NaN  ...
          2020                                                  NaN  ...
          2021                                                  NaN  ...

                                     Recipient State-owned Company  \
Recipient Implementation Start Year
AF        2002                                                 NaN
          2004                                                 NaN
          2005                                                 NaN
          2006                                                 NaN
          2007                                                 NaN
...                                                            ...
ZW        2017                                                 NaN
          2018                                                 NaN
          2019                                                 NaN
          2020                                                 NaN
          2021                                                 NaN

                                     Recipient State-owned Fund  \
Recipient Implementation Start Year
AF        2002                                              NaN
          2004                                              NaN
          2005                                              NaN
          2006                                              NaN
          2007                                              NaN
...                                                         ...
ZW        2017                                              NaN
          2018                                              NaN
          2019                                              NaN
          2020                                              NaN
          2021                                              NaN

                                     Chinese Financier  Non-Chinese Financier  \
Recipient Implementation Start Year
AF        2002                                     1.0                    NaN
          2004                                     3.0                    NaN
          2005                                     1.0                    NaN
          2006                                     2.0                    NaN
          2007                                     2.0                    NaN
...                                                ...                    ...
ZW        2017                                     3.0                    NaN
          2018                                     4.0                    1.0
          2019                                     7.0                    NaN
          2020                                    11.0                    NaN
          2021                                     9.0                    NaN

                                      Q1   Q2   Q3   Q4  \
Recipient Implementation Start Year
AF        2002                       0.0  1.0  0.0  0.0
          2004                       0.0  1.0  2.0  0.0
          2005                       0.0  1.0  0.0  0.0
          2006                       0.0  1.0  1.0  0.0
          2007                       1.0  0.0  1.0  0.0
...                                  ...  ...  ...  ...
ZW        2017                       1.0  2.0  0.0  0.0
          2018                       0.0  1.0  1.0  3.0
          2019                       3.0  2.0  2.0  0.0
          2020                       8.0  3.0  0.0  0.0
          2021                       2.0  3.0  2.0  2.0

                                     Average Loan Amount (Nominal USD)  \
Recipient Implementation Start Year
AF        2002                                            3.624493e+08
          2004                                            1.002966e+09
          2005                                            1.000000e+08
          2006                                            1.300000e+09
          2007                                            5.358857e+08
...                                                                ...
ZW        2017                                            5.200000e+07
          2018                                            2.547125e+10
          2019                                            6.159234e+08
          2020                                            1.772421e+07
          2021                                            2.216556e+09

                                     Total Loan Amount (Nominal USD)
Recipient Implementation Start Year
AF        2002                                          3.624493e+08
          2004                                          3.008898e+09
          2005                                          1.000000e+08
          2006                                          2.600000e+09
          2007                                          1.071771e+09
...                                                              ...
ZW        2017                                          1.560000e+08
          2018                                          1.273562e+11
          2019                                          4.311464e+09
          2020                                          1.949663e+08
          2021                                          1.994900e+10

[1811 rows x 63 columns]

In [344]:
chinese_loan.fillna(0, inplace = True)
chinese_loan

                                     Grant  Loan  Vague  Commercial  \
Recipient Implementation Start Year
AF        2002                         1.0   0.0    0.0         0.0
          2004                         3.0   0.0    0.0         0.0
          2005                         1.0   0.0    0.0         0.0
          2006                         2.0   0.0    0.0         0.0
          2007                         2.0   0.0    0.0         0.0
...                                    ...   ...    ...         ...
ZW        2017                         3.0   0.0    0.0         0.0
          2018                         3.0   2.0    0.0         0.0
          2019                         7.0   0.0    0.0         0.0
          2020                        11.0   0.0    0.0         0.0
          2021                         7.0   2.0    0.0         0.0

                                     Development  Mixed  Representational  \
Recipient Implementation Start Year
AF        2002                               1.0    0.0               0.0
          2004                               3.0    0.0               0.0
          2005                               1.0    0.0               0.0
          2006                               2.0    0.0               0.0
          2007                               2.0    0.0               0.0
...                                          ...    ...               ...
ZW        2017                               3.0    0.0               0.0
          2018                               4.0    1.0               0.0
          2019                               7.0    0.0               0.0
          2020                              11.0    0.0               0.0
          2021                               9.0    0.0               0.0

                                     ACTION RELATING TO DEBT  \
Recipient Implementation Start Year
AF        2002                                           0.0
          2004                                           1.0
          2005                                           0.0
          2006                                           0.0
          2007                                           0.0
...                                                      ...
ZW        2017                                           0.0
          2018                                           0.0
          2019                                           0.0
          2020                                           0.0
          2021                                           0.0

                                     AGRICULTURE, FORESTRY, FISHING  \
Recipient Implementation Start Year
AF        2002                                                  0.0
          2004                                                  0.0
          2005                                                  0.0
          2006                                                  0.0
          2007                                                  0.0
...                                                             ...
ZW        2017                                                  1.0
          2018                                                  1.0
          2019                                                  1.0
          2020                                                  0.0
          2021                                                  0.0

                                     BANKING AND FINANCIAL SERVICES  ...  \
Recipient Implementation Start Year                                  ...
AF        2002                                                  0.0  ...
          2004                                                  0.0  ...
          2005                                                  0.0  ...
          2006                                                  0.0  ...
          2007                                                  0.0  ...
...                                                             ...  ...
ZW        2017                                                  0.0  ...
          2018                                                  0.0  ...
          2019                                                  0.0  ...
          2020                                                  0.0  ...
          2021                                                  0.0  ...

                                     Recipient State-owned Company  \
Recipient Implementation Start Year
AF        2002                                                 0.0
          2004                                                 0.0
          2005                                                 0.0
          2006                                                 0.0
          2007                                                 0.0
...                                                            ...
ZW        2017                                                 0.0
          2018                                                 0.0
          2019                                                 0.0
          2020                                                 0.0
          2021                                                 0.0

                                     Recipient State-owned Fund  \
Recipient Implementation Start Year
AF        2002                                              0.0
          2004                                              0.0
          2005                                              0.0
          2006                                              0.0
          2007                                              0.0
...                                                         ...
ZW        2017                                              0.0
          2018                                              0.0
          2019                                              0.0
          2020                                              0.0
          2021                                              0.0

                                     Chinese Financier  Non-Chinese Financier  \
Recipient Implementation Start Year
AF        2002                                     1.0                    0.0
          2004                                     3.0                    0.0
          2005                                     1.0                    0.0
          2006                                     2.0                    0.0
          2007                                     2.0                    0.0
...                                                ...                    ...
ZW        2017                                     3.0                    0.0
          2018                                     4.0                    1.0
          2019                                     7.0                    0.0
          2020                                    11.0                    0.0
          2021                                     9.0                    0.0

                                      Q1   Q2   Q3   Q4  \
Recipient Implementation Start Year
AF        2002                       0.0  1.0  0.0  0.0
          2004                       0.0  1.0  2.0  0.0
          2005                       0.0  1.0  0.0  0.0
          2006                       0.0  1.0  1.0  0.0
          2007                       1.0  0.0  1.0  0.0
...                                  ...  ...  ...  ...
ZW        2017                       1.0  2.0  0.0  0.0
          2018                       0.0  1.0  1.0  3.0
          2019                       3.0  2.0  2.0  0.0
          2020                       8.0  3.0  0.0  0.0
          2021                       2.0  3.0  2.0  2.0

                                     Average Loan Amount (Nominal USD)  \
Recipient Implementation Start Year
AF        2002                                            3.624493e+08
          2004                                            1.002966e+09
          2005                                            1.000000e+08
          2006                                            1.300000e+09
          2007                                            5.358857e+08
...                                                                ...
ZW        2017                                            5.200000e+07
          2018                                            2.547125e+10
          2019                                            6.159234e+08
          2020                                            1.772421e+07
          2021                                            2.216556e+09

                                     Total Loan Amount (Nominal USD)
Recipient Implementation Start Year
AF        2002                                          3.624493e+08
          2004                                          3.008898e+09
          2005                                          1.000000e+08
          2006                                          2.600000e+09
          2007                                          1.071771e+09
...                                                              ...
ZW        2017                                          1.560000e+08
          2018                                          1.273562e+11
          2019                                          4.311464e+09
          2020                                          1.949663e+08
          2021                                          1.994900e+10

[1811 rows x 63 columns]

In [345]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
Country,Year,,
AF,1950,NaN,NaN
AL,1950,NaN,NaN
DZ,1950,NaN,NaN
AO,1950,NaN,NaN
AG,1950,NaN,NaN
...,...,...,...
PH,2022,NaN,57.519704
TJ,2022,NaN,34.631164
TZ,2022,NaN,41.622404
AE,2022,NaN,29.957880
UZ,2022,NaN,34.294587

In [346]:
loan_debt_data.reset_index(inplace = True)

In [347]:
loan_debt_data["Year"] = pd.to_numeric(loan_debt_data["Year"])

In [348]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP)
0,AF,1950,NaN,NaN
1,AL,1950,NaN,NaN
2,DZ,1950,NaN,NaN
3,AO,1950,NaN,NaN
4,AG,1950,NaN,NaN
...,...,...,...,...
13792,PH,2022,NaN,57.519704
13793,TJ,2022,NaN,34.631164
13794,TZ,2022,NaN,41.622404
13795,AE,2022,NaN,29.957880
13796,UZ,2022,NaN,34.294587

In [349]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] >= 2000]

In [350]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [351]:
chinese_loan.reset_index(inplace = True)
chinese_loan

,Recipient,Implementation Start Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
0,AF,2002,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.624493e+08,3.624493e+08
1,AF,2004,3.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,...,0.0,0.0,3.0,0.0,0.0,1.0,2.0,0.0,1.002966e+09,3.008898e+09
2,AF,2005,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.000000e+08,1.000000e+08
3,AF,2006,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,0.0,1.300000e+09,2.600000e+09
4,AF,2007,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,1.0,0.0,1.0,0.0,5.358857e+08,1.071771e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1806,ZW,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,5.200000e+07,1.560000e+08
1807,ZW,2018,3.0,2.0,0.0,0.0,4.0,1.0,0.0,0.0,...,0.0,0.0,4.0,1.0,0.0,1.0,1.0,3.0,2.547125e+10,1.273562e+11
1808,ZW,2019,7.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,3.0,2.0,2.0,0.0,6.159234e+08,4.311464e+09
1809,ZW,2020,11.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,...,0.0,0.0,11.0,0.0,8.0,3.0,0.0,0.0,1.772421e+07,1.949663e+08
1810,ZW,2021,7.0,2.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,9.0,0.0,2.0,3.0,2.0,2.0,2.216556e+09,1.994900e+10

In [352]:
chinese_loan = chinese_loan.rename({"Implementation Start Year": "Year", "Recipient": "Country"}, axis = 1)

In [353]:
chinese_loan

,Country,Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
0,AF,2002,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.624493e+08,3.624493e+08
1,AF,2004,3.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,...,0.0,0.0,3.0,0.0,0.0,1.0,2.0,0.0,1.002966e+09,3.008898e+09
2,AF,2005,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.000000e+08,1.000000e+08
3,AF,2006,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,0.0,1.300000e+09,2.600000e+09
4,AF,2007,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,1.0,0.0,1.0,0.0,5.358857e+08,1.071771e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1806,ZW,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,5.200000e+07,1.560000e+08
1807,ZW,2018,3.0,2.0,0.0,0.0,4.0,1.0,0.0,0.0,...,0.0,0.0,4.0,1.0,0.0,1.0,1.0,3.0,2.547125e+10,1.273562e+11
1808,ZW,2019,7.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,3.0,2.0,2.0,0.0,6.159234e+08,4.311464e+09
1809,ZW,2020,11.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,...,0.0,0.0,11.0,0.0,8.0,3.0,0.0,0.0,1.772421e+07,1.949663e+08
1810,ZW,2021,7.0,2.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,9.0,0.0,2.0,3.0,2.0,2.0,2.216556e+09,1.994900e+10

In [354]:
chinese_loan.sort_values(["Year", "Country"], inplace = True)
chinese_loan

,Country,Year,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
1670,UZ,1996,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.924000e+09,2.924000e+09
466,ET,1998,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.200000e+09,1.200000e+09
1006,MM,1998,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,8.500000e+09,1.700000e+10
794,KM,1999,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.002759e+08,5.002759e+08
26,AL,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597,TR,2022,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,5.416863e+09,1.083373e+10
1732,VU,2022,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,3.157389e+09,6.314778e+09
1788,ZM,2022,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.216000e+09,2.216000e+09
301,CI,2023,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
573,GH,2023,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [355]:
chinese_loan = chinese_loan[chinese_loan["Year"] >= 2000]

In [356]:
chinese_loan.set_index(["Country", "Year"], inplace = True)

In [357]:
chinese_loan

,,Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,"AGRICULTURE, FORESTRY, FISHING",BANKING AND FINANCIAL SERVICES,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
Country,Year,,,,,,,,,,,,,,,,,,,,,
AL,2000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
BJ,2000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,8.878428e+08,8.878428e+08
CD,2000,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,0.0,7.726274e+08,1.545255e+09
ER,2000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,9.663596e+08,9.663596e+08
ET,2000,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.120795e+07,2.241590e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TR,2022,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,5.416863e+09,1.083373e+10
VU,2022,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,3.157389e+09,6.314778e+09
ZM,2022,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.216000e+09,2.216000e+09
CI,2023,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
GH,2023,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [358]:
loan_debt_data = pd.concat([loan_debt_data, chinese_loan], axis = 1, join = "outer")

In [359]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
DZ,2000,57.960343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,2000,133.914140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,2000,105.132373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.030860e+10,1.030860e+10
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,2.0,3.0,0.0,0.0,6.037369e+07,3.018685e+08
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,2.0,1.0,0.0,5.533333e+08,1.660000e+09
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [360]:
loan_debt_data[new_order] = loan_debt_data[new_order].fillna(0)

In [361]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.030860e+10,1.030860e+10
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,2.0,3.0,0.0,0.0,6.037369e+07,3.018685e+08
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,2.0,1.0,0.0,5.533333e+08,1.660000e+09
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [362]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.030860e+10,1.030860e+10
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,2.0,3.0,0.0,0.0,6.037369e+07,3.018685e+08
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,2.0,1.0,0.0,5.533333e+08,1.660000e+09
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [363]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Recipient State-owned Company,Recipient State-owned Fund,Chinese Financier,Non-Chinese Financier,Q1,Q2,Q3,Q4,Average Loan Amount (Nominal USD),Total Loan Amount (Nominal USD)
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.200000e+08,1.200000e+08
DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.030860e+10,1.030860e+10
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,2.0,3.0,0.0,0.0,6.037369e+07,3.018685e+08
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,2.0,1.0,0.0,5.533333e+08,1.660000e+09
CI,2023,NaN,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.024594e+10,1.024594e+10
GH,2023,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.942029e+09,1.942029e+09

In [364]:
aei_data = pd.read_csv("Data/AEI-Data.csv", skiprows = 5)

In [365]:
aei_data.columns

Index(['Year', 'Month', 'Investor', ' Quantity in Millions ', 'Share Size',
       'Transaction Party', 'Sector', 'Subsector', 'Country', 'Region', 'BRI',
       'Greenfield', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')

In [366]:
aei_data = aei_data[["Country", "Year", "Investor","Sector", "Subsector", " Quantity in Millions "]]

In [367]:
aei_data

,Country,Year,Investor,Sector,Subsector,Quantity in Millions
0,Cuba,2005,Minmetals,Metals,NaN,$500
1,USA,2005,Chinese Academy of Sciences,Technology,NaN,"$1,740"
2,Qatar,2005,Sinohydro,Transport,Aviation,$100
3,Oman,2005,Sinohydro,Utilities,NaN,$150
4,Ecuador,2005,Sinohydro,Transport,Autos,$370
...,...,...,...,...,...,...
4293,Guinea,2023,Power Construction Corp. (PowerChina),Metals,Aluminum,$110
4294,Saudi Arabia,2023,Power Construction Corp. (PowerChina),Energy,Alternative,$410
4295,Saudi Arabia,2023,China National Chemical Engineering,Chemicals,NaN,$270
4296,Nigeria,2023,China National Building Material,Real estate,Construction,$590
4297,Algeria,2023,China National Petroleum Corp. (CNPC),Chemicals,NaN,$440

In [368]:
aei_data = aei_data.replace(name_to_alpha_2)

In [369]:
aei_data[ " Quantity in Millions "] = aei_data[ " Quantity in Millions "].apply(lambda x: x[2:len(x)-1])
aei_data[ " Quantity in Millions "] = aei_data[ " Quantity in Millions "].apply(lambda x: x.replace(",", ""))

In [370]:
aei_data = aei_data.rename({ " Quantity in Millions ": "Quantity in Millions"}, axis = 1)

In [371]:
aei_data["Quantity in Millions"] = pd.to_numeric(aei_data["Quantity in Millions"], downcast = 'float')

In [372]:
usd = aei_data[["Country", "Year", "Quantity in Millions"]]
total = usd.groupby(["Country", "Year"]).sum() 
average = usd.groupby(["Country", "Year"]).mean()

total.rename({"Quantity in Millions": "Total Loan Amount-AEI"}, axis = 1, inplace = True)
average.rename({"Quantity in Millions": "Average Loan Amount-AEI"}, axis = 1, inplace = True)

In [373]:
aei_data["Quantity in Millions"], aei_bins = pd.qcut(aei_data["Quantity in Millions"], q = 4, labels = ["Q1", "Q2", "Q3", "Q4"], retbins = True)

In [374]:
aei_data

,Country,Year,Investor,Sector,Subsector,Quantity in Millions
0,CU,2005,Minmetals,Metals,NaN,Q3
1,US,2005,Chinese Academy of Sciences,Technology,NaN,Q4
2,QA,2005,Sinohydro,Transport,Aviation,Q1
3,OM,2005,Sinohydro,Utilities,NaN,Q1
4,EC,2005,Sinohydro,Transport,Autos,Q3
...,...,...,...,...,...,...
4293,GN,2023,Power Construction Corp. (PowerChina),Metals,Aluminum,Q1
4294,SA,2023,Power Construction Corp. (PowerChina),Energy,Alternative,Q3
4295,SA,2023,China National Chemical Engineering,Chemicals,NaN,Q2
4296,NG,2023,China National Building Material,Real estate,Construction,Q4
4297,DZ,2023,China National Petroleum Corp. (CNPC),Chemicals,NaN,Q3

In [375]:
aei_data.set_index(["Country", "Year"], inplace = True)

In [376]:
aei_data

                                           Investor       Sector  \
Country Year
CU      2005                              Minmetals       Metals
US      2005            Chinese Academy of Sciences   Technology
QA      2005                              Sinohydro    Transport
OM      2005                              Sinohydro    Utilities
EC      2005                              Sinohydro    Transport
...                                             ...          ...
GN      2023  Power Construction Corp. (PowerChina)       Metals
SA      2023  Power Construction Corp. (PowerChina)       Energy
        2023    China National Chemical Engineering    Chemicals
NG      2023       China National Building Material  Real estate
DZ      2023  China National Petroleum Corp. (CNPC)    Chemicals

                 Subsector Quantity in Millions
Country Year
CU      2005           NaN                   Q3
US      2005           NaN                   Q4
QA      2005      Aviation                   Q1
OM      2005           NaN                   Q1
EC      2005         Autos                   Q3
...                    ...                  ...
GN      2023      Aluminum                   Q1
SA      2023   Alternative                   Q3
        2023           NaN                   Q2
NG      2023  Construction                   Q4
DZ      2023           NaN                   Q3

[4298 rows x 4 columns]

In [377]:
aei_data = aei_data.apply(lambda x: x.apply(lambda y: y + "-AEI" if isinstance(y, str) else None), axis = 1)

In [378]:
aei_data

                                               Investor           Sector  \
Country Year
CU      2005                              Minmetals-AEI       Metals-AEI
US      2005            Chinese Academy of Sciences-AEI   Technology-AEI
QA      2005                              Sinohydro-AEI    Transport-AEI
OM      2005                              Sinohydro-AEI    Utilities-AEI
EC      2005                              Sinohydro-AEI    Transport-AEI
...                                                 ...              ...
GN      2023  Power Construction Corp. (PowerChina)-AEI       Metals-AEI
SA      2023  Power Construction Corp. (PowerChina)-AEI       Energy-AEI
        2023    China National Chemical Engineering-AEI    Chemicals-AEI
NG      2023       China National Building Material-AEI  Real estate-AEI
DZ      2023  China National Petroleum Corp. (CNPC)-AEI    Chemicals-AEI

                     Subsector Quantity in Millions
Country Year
CU      2005              None               Q3-AEI
US      2005              None               Q4-AEI
QA      2005      Aviation-AEI               Q1-AEI
OM      2005              None               Q1-AEI
EC      2005         Autos-AEI               Q3-AEI
...                        ...                  ...
GN      2023      Aluminum-AEI               Q1-AEI
SA      2023   Alternative-AEI               Q3-AEI
        2023              None               Q2-AEI
NG      2023  Construction-AEI               Q4-AEI
DZ      2023              None               Q3-AEI

[4298 rows x 4 columns]

In [379]:
investors = aei_data["Investor"].unique()
sectors = aei_data["Sector"].unique()
subsectors = aei_data["Subsector"].unique()[1:]
quantities = aei_data["Quantity in Millions"].unique() 

new_order = np.concatenate([investors, sectors, subsectors, quantities])

In [380]:
aei_data.reset_index(inplace = True)

In [381]:
aei_data = aei_data.groupby(['Country', 'Year']).apply(lambda x: x.drop(['Country', 'Year'], axis = 1)
                                                                                                       .apply(pd.Series.value_counts))

In [382]:
aei_data

                                                 Investor  Sector  Subsector  \
Country Year
AE      2006 Construction-AEI                         NaN     NaN        1.0
             Q3-AEI                                   NaN     NaN        NaN
             Real estate-AEI                          NaN     1.0        NaN
             State Construction Engineering-AEI       1.0     NaN        NaN
        2007 Autos-AEI                                NaN     NaN        1.0
...                                                   ...     ...        ...
ZW      2022 Tsingshan-AEI                            1.0     NaN        NaN
             Zhejiang Huayou Cobalt-AEI               1.0     NaN        NaN
        2023 Feishang Group-AEI                       1.0     NaN        NaN
             Metals-AEI                               NaN     1.0        NaN
             Q2-AEI                                   NaN     NaN        NaN

                                                 Quantity in Millions
Country Year
AE      2006 Construction-AEI                                     NaN
             Q3-AEI                                               1.0
             Real estate-AEI                                      NaN
             State Construction Engineering-AEI                   NaN
        2007 Autos-AEI                                            NaN
...                                                               ...
ZW      2022 Tsingshan-AEI                                        NaN
             Zhejiang Huayou Cobalt-AEI                           NaN
        2023 Feishang Group-AEI                                   NaN
             Metals-AEI                                           NaN
             Q2-AEI                                               1.0

[11476 rows x 4 columns]

In [383]:
count = aei_data.apply(lambda x: return_not_na(x), axis = 1)

In [384]:
aei_data = aei_data.drop(aei_data.columns, axis = 1)

In [385]:
aei_data["Count"] = count

In [386]:
aei_data

                                                 Count
Country Year
AE      2006 Construction-AEI                      1.0
             Q3-AEI                                1.0
             Real estate-AEI                       1.0
             State Construction Engineering-AEI    1.0
        2007 Autos-AEI                             1.0
...                                                ...
ZW      2022 Tsingshan-AEI                         1.0
             Zhejiang Huayou Cobalt-AEI            1.0
        2023 Feishang Group-AEI                    1.0
             Metals-AEI                            1.0
             Q2-AEI                                1.0

[11476 rows x 1 columns]

In [387]:
aei_data.reset_index(inplace = True)

In [388]:
aei_data = aei_data.pivot(index = ['Country', 'Year'], columns = 'level_2')

In [389]:
aei_data

                                                                   Count  \
level_2      3SBio, China International Trust and Investment (CITIC)-AEI
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

                                                                               \
level_2      AAC-AEI Agile Property-AEI Agriculture-AEI Aier Eye Hospital-AEI
Country Year
AE      2006     NaN                NaN             NaN                   NaN
        2007     NaN                NaN             NaN                   NaN
        2008     NaN                NaN             NaN                   NaN
        2009     NaN                NaN             NaN                   NaN
        2010     NaN                NaN             1.0                   NaN
...              ...                ...             ...                   ...
ZW      2019     NaN                NaN             NaN                   NaN
        2020     NaN                NaN             NaN                   NaN
        2021     NaN                NaN             NaN                   NaN
        2022     NaN                NaN             NaN                   NaN
        2023     NaN                NaN             NaN                   NaN

                                          \
level_2      Alibaba-AEI Alternative-AEI
Country Year
AE      2006         NaN             NaN
        2007         NaN             NaN
        2008         NaN             NaN
        2009         NaN             NaN
        2010         NaN             NaN
...                  ...             ...
ZW      2019         NaN             1.0
        2020         NaN             NaN
        2021         NaN             NaN
        2022         NaN             NaN
        2023         NaN             NaN

                                                                        \
level_2      Aluminum Corporation of China (Chinalco)-AEI Aluminum-AEI
Country Year
AE      2006                                          NaN          NaN
        2007                                          NaN          NaN
        2008                                          NaN          NaN
        2009                                          NaN          NaN
        2010                                          NaN          NaN
...                                                   ...          ...
ZW      2019                                          NaN          NaN
        2020                                          NaN          NaN
        2021                                          NaN          NaN
        2022                                          NaN          NaN
        2023                                          NaN          NaN

                         ...                   \
level_2      Anbang-AEI  ... Zhuhai Huafa-AEI
Country Year             ...
AE      2006        NaN  ...              NaN
        2007        NaN  ...              NaN
        2008        NaN  ...              NaN
        2009        NaN  ...              NaN
        2010        NaN  ...              NaN
...                 ...  ...              ...
ZW      2019        NaN  ...              NaN
        2020        NaN  ...              NaN
        2021        NaN  ...              NaN
        2022        NaN  ...              NaN
        2023        NaN  ...              NaN

                                                                       \
level_2      Zhuhai Port Holdings, State Construction Engineering-AEI
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

                                                     \
level_2      Zhuhai Zhenrong-AEI Zhuzhou Kibing-AEI
Country Year
AE      2006                 NaN                NaN
        2007                 NaN                NaN
        2008                 NaN                NaN
        2009                 NaN                NaN
        2010                 NaN                NaN
...                          ...                ...
ZW      2019                 NaN                NaN
        2020                 NaN                NaN
        2021                 NaN                NaN
        2022                 NaN                NaN
        2023                 NaN                NaN

                                                                              \
level_2      Zijin Mining, China Nonferrous, Xiamen C&D-AEI Zijin Mining-AEI
Country Year
AE      2006                                            NaN              NaN
        2007                                            NaN              NaN
        2008                                            NaN              NaN
        2009                                            NaN              NaN
        2010                                            NaN              NaN
...                                                     ...              ...
ZW      2019                                            NaN              NaN
        2020                                            NaN              NaN
        2021                                            NaN              NaN
        2022                                            NaN              NaN
        2023                                            NaN              NaN


level_2      Zongshen Industrial-AEI Zoomlion-AEI iCarbonX-AEI xFusion-AEI
Country Year
AE      2006                     NaN          NaN          NaN         NaN
        2007                     NaN          NaN          NaN         NaN
        2008                     NaN          NaN          NaN         NaN
        2009                     NaN          NaN          NaN         NaN
        2010                     NaN          NaN          NaN         NaN
...                              ...          ...          ...         ...
ZW      2019                     NaN          NaN          NaN         NaN
        2020                     NaN          NaN          NaN         NaN
        2021                     NaN          NaN          NaN         NaN
        2022                     NaN          NaN          NaN         NaN
        2023                     NaN          NaN          NaN         NaN

[1369 rows x 936 columns]

In [390]:
aei_data.columns = aei_data.columns.droplevel(level = 0)

In [391]:
aei_data

level_2       3SBio, China International Trust and Investment (CITIC)-AEI  \
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

level_2       AAC-AEI  Agile Property-AEI  Agriculture-AEI  \
Country Year
AE      2006      NaN                 NaN              NaN
        2007      NaN                 NaN              NaN
        2008      NaN                 NaN              NaN
        2009      NaN                 NaN              NaN
        2010      NaN                 NaN              1.0
...               ...                 ...              ...
ZW      2019      NaN                 NaN              NaN
        2020      NaN                 NaN              NaN
        2021      NaN                 NaN              NaN
        2022      NaN                 NaN              NaN
        2023      NaN                 NaN              NaN

level_2       Aier Eye Hospital-AEI  Alibaba-AEI  Alternative-AEI  \
Country Year
AE      2006                    NaN          NaN              NaN
        2007                    NaN          NaN              NaN
        2008                    NaN          NaN              NaN
        2009                    NaN          NaN              NaN
        2010                    NaN          NaN              NaN
...                             ...          ...              ...
ZW      2019                    NaN          NaN              1.0
        2020                    NaN          NaN              NaN
        2021                    NaN          NaN              NaN
        2022                    NaN          NaN              NaN
        2023                    NaN          NaN              NaN

level_2       Aluminum Corporation of China (Chinalco)-AEI  Aluminum-AEI  \
Country Year
AE      2006                                           NaN           NaN
        2007                                           NaN           NaN
        2008                                           NaN           NaN
        2009                                           NaN           NaN
        2010                                           NaN           NaN
...                                                    ...           ...
ZW      2019                                           NaN           NaN
        2020                                           NaN           NaN
        2021                                           NaN           NaN
        2022                                           NaN           NaN
        2023                                           NaN           NaN

level_2       Anbang-AEI  ...  Zhuhai Huafa-AEI  \
Country Year              ...
AE      2006         NaN  ...               NaN
        2007         NaN  ...               NaN
        2008         NaN  ...               NaN
        2009         NaN  ...               NaN
        2010         NaN  ...               NaN
...                  ...  ...               ...
ZW      2019         NaN  ...               NaN
        2020         NaN  ...               NaN
        2021         NaN  ...               NaN
        2022         NaN  ...               NaN
        2023         NaN  ...               NaN

level_2       Zhuhai Port Holdings, State Construction Engineering-AEI  \
Country Year
AE      2006                                                NaN
        2007                                                NaN
        2008                                                NaN
        2009                                                NaN
        2010                                                NaN
...                                                         ...
ZW      2019                                                NaN
        2020                                                NaN
        2021                                                NaN
        2022                                                NaN
        2023                                                NaN

level_2       Zhuhai Zhenrong-AEI  Zhuzhou Kibing-AEI  \
Country Year
AE      2006                  NaN                 NaN
        2007                  NaN                 NaN
        2008                  NaN                 NaN
        2009                  NaN                 NaN
        2010                  NaN                 NaN
...                           ...                 ...
ZW      2019                  NaN                 NaN
        2020                  NaN                 NaN
        2021                  NaN                 NaN
        2022                  NaN                 NaN
        2023                  NaN                 NaN

level_2       Zijin Mining, China Nonferrous, Xiamen C&D-AEI  \
Country Year
AE      2006                                             NaN
        2007                                             NaN
        2008                                             NaN
        2009                                             NaN
        2010                                             NaN
...                                                      ...
ZW      2019                                             NaN
        2020                                             NaN
        2021                                             NaN
        2022                                             NaN
        2023                                             NaN

level_2       Zijin Mining-AEI  Zongshen Industrial-AEI  Zoomlion-AEI  \
Country Year
AE      2006               NaN                      NaN           NaN
        2007               NaN                      NaN           NaN
        2008               NaN                      NaN           NaN
        2009               NaN                      NaN           NaN
        2010               NaN                      NaN           NaN
...                        ...                      ...           ...
ZW      2019               NaN                      NaN           NaN
        2020               NaN                      NaN           NaN
        2021               NaN                      NaN           NaN
        2022               NaN                      NaN           NaN
        2023               NaN                      NaN           NaN

level_2       iCarbonX-AEI  xFusion-AEI
Country Year
AE      2006           NaN          NaN
        2007           NaN          NaN
        2008           NaN          NaN
        2009           NaN          NaN
        2010           NaN          NaN
...                    ...          ...
ZW      2019           NaN          NaN
        2020           NaN          NaN
        2021           NaN          NaN
        2022           NaN          NaN
        2023           NaN          NaN

[1369 rows x 936 columns]

In [392]:
aei_data = pd.concat([aei_data, average, total], axis = 1)

In [393]:
new_order

array(['Minmetals-AEI', 'Chinese Academy of Sciences-AEI',
       'Sinohydro-AEI', 'MCC-AEI', 'Sinoma-AEI',
       'China National Off-shore Oil (CNOOC)-AEI',
       'China National Machinery Industry (Sinomach)-AEI',
       'Minmetals, MCC-AEI', 'China National Petroleum Corp. (CNPC)-AEI',
       'China Petroleum and Chemical (Sinopec)-AEI',
       'China National Machinery Industry (Sinomach), Sinohydro-AEI',
       'China Railway Construction, China General Technology (Genertec)-AEI',
       'Jiangsu Yuejin-AEI',
       'China International Trust and Investment (CITIC), Sinohydro-AEI',
       'China National Petroleum Corp. (CNPC), China Petroleum and Chemical (Sinopec)-AEI',
       'China Investment Corporation (CIC), Beijing Jingdeshun-AEI',
       'China National Chemical (ChemChina)-AEI', 'Sinosteel-AEI',
       'China Nonferrous-AEI', 'China Communications Construction-AEI',
       'China North Industries (Norinco)-AEI',
       'China International Trust and Investment (CITIC)-AEI',
       'Zhejiang Holley-AEI',
       'China International Trust and Investment (CITIC), Aluminum Corporation of China (Chinalco)-AEI',
       'China National Nuclear-AEI', 'State Construction Engineering-AEI',
       'Shanghai Municipal Government-AEI',
       'Shandong Electric Power Construction III-AEI',
       'China Power Engineering Consulting-AEI',
       'China International Trust and Investment (CITIC), China Railway Construction-AEI',
       'Tebian Electric Apparatus (TBEA)-AEI',
       'Weihai International Economic-AEI',
       'Jiangsu International Cooperation Corp-AEI',
       'Dongfang Electric-AEI', 'Wuxi Suntech-AEI',
       'ZTE (Zhongxing Telecommunications Equipment), Huawei, China Communications Construction-AEI',
       'Huawei-AEI', 'Jiangxi Copper-AEI', 'China Development Bank-AEI',
       'Ex-Im Bank-AEI', 'Three Gorges-AEI',
       'China National Chemical Engineering-AEI',
       'China General Technology (Genertec)-AEI', 'Sichuan Changhong-AEI',
       'Bank of China-AEI', 'Harbin Electric-AEI', 'Huadian-AEI',
       'Shanghai Electric-AEI', 'China Mobile-AEI',
       'Shandong Electric Power Construction-AEI',
       'Aluminum Corporation of China (Chinalco)-AEI',
       'China Railway Construction-AEI',
       'Zijin Mining, China Nonferrous, Xiamen C&D-AEI',
       'Shanghai Shengong, Shanghai Foreign Economic and Technological Cooperation-AEI',
       'Gezhouba-AEI', 'Sinohydro, China Communications Construction-AEI',
       'China National Machinery Industry (Sinomach), China Nonferrous-AEI',
       'China Investment Corporation (CIC)-AEI',
       'LinkGlobal Logistics-AEI', 'China National Building Material-AEI',
       'China Ocean Shipping (COSCO)-AEI', 'Golden Dragon-AEI',
       'Dongfang Electric, Shanghai Electric-AEI', 'Ansteel-AEI',
       'Sany Heavy Industry-AEI',
       'Industrial and Commercial Bank of China-AEI',
       'Southern Power Grid-AEI', 'China Electronics Corporation-AEI',
       'Ping An-AEI', 'MCC, Jiangxi Copper-AEI', 'Youngor-AEI',
       'Guizhou Hongfu-AEI', 'Minmetals, Jiangxi Copper-AEI',
       'Shenzhen Energy, China Development Bank-AEI',
       'State Administration of Foreign Exchange (SAFE)-AEI',
       'Jinchuan Group-AEI', 'WuXi Pharma-AEI', 'State Grid-AEI',
       'Sinochem-AEI', 'Minmetals, Xinxing Iron-AEI', 'Huaneng Power-AEI',
       'China Life-AEI', 'Mindray Medical-AEI',
       'China Railway Engineering-AEI', 'Hopu Investment-AEI',
       'Sinohydro, Three Gorges-AEI',
       'China National Chemical Engineering, China General Technology (Genertec)-AEI',
       'China National Cereal, Oil and Foodstuffs (COFCO)-AEI',
       'Zoomlion-AEI', 'MCC, Sinohydro-AEI',
       'Guangdong Overseas Construction-AEI',
       'Shanghai Tunnel Engineering-AEI',
       'Jiangsu Shagang, RGL Group-AEI', 'Datong-AEI', 'Shenhua-AEI',
       'Three Gorges-led consortium-AEI',
       'ZTE (Zhongxing Telecommunications Equipment)-AEI',
       'Zhongmei Engineering-AEI', 'Xinjiang Guanghui-AEI',
       'Wuhan Iron and Steel, China Development Bank-AEI', 'Datang-AEI',
       'Union Development-AEI', 'Hunan Valin-AEI', 'Shougang Group-AEI',
       'Wuhan Iron and Steel-AEI', 'Tianjin Pipe-AEI',
       'Jiangsu Taihu-AEI',
       'China National Off-shore Oil (CNOOC), China Petroleum and Chemical (Sinopec)-AEI',
       'HNA-AEI', 'Nanjinzhao-AEI',
       'Guangdong Rising Asset Management-AEI',
       'Haicheng Xiyang Group-AEI', 'Tianjin Development-AEI',
       'Taiyuan Iron, China Development Bank, Shanxi Coking Coal, and Tianli Enterprises-AEI',
       'Shandong Electric Power Construction III, Dongfang Electric-AEI',
       'Yankuang-AEI', 'MCC, China Architecture Design-AEI',
       'China United Network Communications (Unicom)-AEI',
       'BaoWu Steel (Baosteel)-AEI', 'Great Wall-AEI',
       'Jin Jiang International-AEI', 'Beijing Auto (BAIC)-AEI',
       'SAIC Motor (Shanghai Auto)-AEI',
       'Aviation Industry Corp. (AVIC)-AEI', 'China Poly-AEI',
       'China Railway Construction, Tongling Nonferrous-AEI',
       'Baiyin Non-Ferrous, China International Trust and Investment (CITIC), Chang Xin-AEI',
       'Shandong Sun Paper-AEI', 'Jinsheng Trading-AEI',
       'Shunde Rixin, Minmetals-AEI', 'Wuhan Kaidi Electric-AEI',
       'Wanhua Industrial-AEI',
       'Gezhouba, Xinjiang International Cooperation Corp-AEI',
       'East China Mineral Exploration and Development Bureau (Jiangsu)-AEI',
       'Geely-AEI', 'First Auto Works, China Development Bank-AEI',
       'Honbridge Capital-AEI',
       'China National Machinery Industry (Sinomach), Gezhouba-AEI',
       'Sichuan Hanlong-AEI', 'Tencent-AEI',
       'Guangdong Power Engineering-AEI', 'Jiangsu Zongyi-AEI',
       'Jinchuan Group, China Development Bank-AEI',
       'Tangshan Jidong Cement, China Development Bank-AEI',
       'Jiangsu Qiyuan-AEI', 'Tianyu Group-AEI',
       'Rongsheng Holding, China National Chemical Engineering-AEI',
       'Shaanxi Coal and Chemical-AEI', 'Yunnan Metallurgical-AEI',
       'Beijing Construction Engineering-AEI',
       'State Development and Investment Corp.-AEI',
       'Tempo Group, Beijing Municipal Government-AEI',
       'China Merchants-AEI', 'China Machine New Energy-AEI',
       'Inner Mongolia Hongjun-AEI', 'Bosai Minerals-AEI',
       'Shanda Group-AEI', 'Three Gorges, Sinohydro-AEI',
       'Guangxi Road and Bridge-AEI', 'Chongqing Chonggang-AEI',
       'China Merchants, China Development Bank-AEI', 'Taiyuan Heavy-AEI',
       'China Railway Construction, Nanjing Government, China Development Bank, Guangdong Xinguang-AEI',
       'Ashima Cultural Industry-AEI',
       'Xinjiang Hualing, Shanghai Boda-AEI', 'Reignwood-AEI',
       'China National Machinery Industry (Sinomach)-led consortium-AEI',
       'Hydrochina-AEI', 'China Electronics Technology-AEI',
       'Jiangsu Jinsheng-AEI', 'Lenovo-AEI',
       'Shangdi Guanqun Investment-AEI',
       'Guangdong Changda Highway Engineering-AEI',
       'China State Shipbuilding-AEI', 'Nanshan Group-AEI',
       'Fulida Group-AEI', 'Chongqing Grain-AEI',
       'Shengli Engineering-led consortium-AEI',
       'Anhui Foreign Economic Construction-AEI', 'Evergreen-AEI',
       'Datang Power, China South Industries-AEI', 'Ningbo Joyson-AEI',
       'Zhongding International Construction-AEI', 'Shandong Iron-AEI',
       'China International Trust and Investment (CITIC), China Development Bank, Long March Capital-AEI',
       'Zijin Mining-AEI', 'Fosun-AEI', 'China Chengtong-AEI',
       'Chery Auto-AEI', 'Dalian International Cooperation Corp-AEI',
       'Suning-AEI', 'Dreal-AEI', 'Fuyao Glass-AEI', 'Gold One-AEI',
       'Guodian-AEI', 'Jilin Nonferrous-AEI', 'Haier-AEI',
       'Beijing Enterprises (BEHL)-AEI', 'Bright Foods-AEI',
       'Taiyuan Iron, China International Trust and Investment (CITIC), BaoWu Steel (Baosteel)-AEI',
       'Midea-AEI', 'JAC Motors-AEI',
       'China National Chemical Engineering, Dongfang Electric, China Energy Engineering-AEI',
       'Xinjiang Goldwind-AEI', 'United Energy-AEI',
       'Qingdao Tianzhong-AEI',
       'Power Construction Corp. (PowerChina)-AEI', 'Henan Guoju-AEI',
       'Jiangxi International Cooperation Corp-AEI', 'Tsingtao Beer-AEI',
       'China Nickel Resources-AEI', 'Soho China-AEI', 'Wolong-AEI',
       'Beijing Urban Construction-AEI', 'Guangxi Nonferrous-AEI',
       'Zhouda Real Estate-AEI',
       'Sinosteel, Power Construction Corp. (PowerChina)-AEI',
       'Sany Heavy Industry, China International Trust and Investment (CITIC)-AEI',
       'Shanghai Wanfeng-AEI', 'Shandong Heavy-AEI',
       'China Energy Engineering-AEI',
       'China Investment Corporation (CIC), China Petroleum and Chemical (Sinopec)-AEI',
       'Guangxi Liugong Machinery-AEI', 'China Shipping-AEI',
       'Guangdong Nuclear Power, China Development Bank-AEI',
       'Dalian Shipbuilding-AEI', 'Shanghai Pengxin-AEI',
       'Hebei Steel-AEI', 'Xuzhou Construction Machinery-AEI',
       'Wanxiang-AEI', 'China Construction Bank-AEI', 'Dalian Wanda-AEI',
       'China Architecture Design and Research-AEI',
       'Shanghai Construction-AEI', 'Hanergy-AEI', 'Xinjiang Hualing-AEI',
       'Wison Engineering-AEI', 'China Electric Equipment-AEI',
       'China Copper Mines-AEI', 'Sichuan Bohong-AEI',
       'China South Locomotive-AEI', 'Jiangxi Zhongmei-AEI',
       'Beijing Shenwu-AEI', 'Wanbao Grain-AEI', 'Shandong Ruyi-AEI',
       'Synutra-AEI', 'Shandong Energy-AEI', 'China Power Investment-AEI',
       'Shandong Gold-AEI', 'BGI-AEI', 'Xinwei-AEI',
       'Beijing Jingmei-AEI', 'Shanghai Greenland-AEI',
       'Shandong Linglong Tire-AEI', 'Sailun Tire-AEI', 'Yuanda-AEI',
       'Shanghai Zhongfu-AEI', 'Yili Industrial-AEI',
       'Hebei Steel, General Development, Tewoo-AEI',
       'Chengdu Tianqi, China Investment Corporation (CIC)-AEI',
       'Country Garden-AEI',
       'China Shipping, China Ocean Shipping (COSCO), China Merchants-AEI',
       'Anhui Conch-AEI',
       'Tebian Electric Apparatus (TBEA), Power Construction Corp. (PowerChina)-AEI',
       'Xiamen University-AEI',
       'Henan International Cooperation Corp-AEI', 'Guangxi Beibu-AEI',
       'Vanke-AEI', 'Shandong Bright Ruby-AEI',
       'Shenyang International Cooperation Corp-AEI',
       'China National Aviation Fuel-AEI', 'Hongye Investment-AEI',
       'Shuanghui-AEI', 'Shandong Qixing-AEI', 'Keep Glory-AEI',
       'CDH-AEI', 'Comtec Solar-AEI', 'Zarsion-AEI',
       'Shanghai MicroPort-AEI', 'Shandong Gaosu-AEI', 'Meidu-AEI',
       'Yunnan Copper-led consortium-AEI', 'China Molybdenum-AEI',
       'Tsingshan-AEI',
       'Power Construction Corp. (PowerChina), China Petroleum and Chemical (Sinopec)-AEI',
       'Shanxi Coking Coal-AEI', 'Belle International, CDH-AEI',
       'China Railway Rolling Stock Corp. (CRR) -AEI',
       'Shenzhen Zhongjin Lingnan-AEI', 'Shaanxi Yanchang Petroleum-AEI',
       'China Energy Conservation-AEI',
       'China National Petroleum Corp. (CNPC), China National Off-shore Oil (CNOOC)-AEI',
       'Zongshen Industrial-AEI', 'Alibaba-AEI', 'Henan Meijing-AEI',
       'China Aerospace Science and Technology-AEI',
       'Sichuan Railway Industry-AEI',
       'Power Construction Corp. (PowerChina), Yingli Green Energy-AEI',
       'Harbin Electric, China Energy Engineering-AEI',
       'Shanghai Zendai-AEI', 'Ming Yan-AEI', 'Keer Group-AEI',
       'Oceanwide Holdings-AEI', 'Guangzhou R&F Properties-AEI',
       'Shenzhen Hepalink-AEI', 'Shenzhen Hazens-AEI',
       'China South Industries-AEI', 'Henan Civil Aviation-AEI',
       'Wanfeng Auto-AEI',
       'China Railway Construction, China Railway Engineering-AEI',
       'Power Construction Corp. (PowerChina), China National Machinery Industry (Sinomach)-AEI',
       'Shandong Electric Power Construction II-AEI', 'Goodbaby-AEI',
       'Power Construction Corp. (PowerChina), Shanghai Construction-AEI',
       'Goldleaf Jewelry-AEI',
       'Bank of China, China Life, Hopu Investment-AEI',
       'Beijing Capital-AEI', 'Anhui Landing-AEI',
       'Huaxin Post and Telecom-AEI', 'Dongfeng-AEI',
       'Zhenfa New Energy-AEI', 'Geo-Jade Petroleum-AEI', 'Cinda-AEI',
       'United Energy, Ningbo Orient-AEI', 'Tidfore Heavy-AEI',
       'Zhejiang Rongsheng, Shanghai Zhongrong, Legend-AEI',
       'Minmetals, Suzhou Guoxin, China International Trust and Investment (CITIC)-AEI',
       'Sanpower-AEI', 'Hubei Fuxing Science-AEI',
       'China National Cereal, Oil and Foodstuffs (COFCO), Hopu Investment-AEI',
       'China Petroleum and Chemical (Sinopec), Huadian-AEI',
       'Hongqiao-AEI', 'Shenzhen Genzon-AEI', 'Baidu-AEI',
       'Shanghai Shentong-AEI',
       'Shanghai International Group, Sanpower-AEI', 'LeEco-AEI',
       'Yida-AEI', 'Heilongjiang Grand Farm-AEI',
       'China Railway Construction, China Nonferrous-AEI', 'Huapont-AEI',
       'Legend-AEI', 'Shandong Daiyin-AEI',
       'State Development and Investment Corp., Anhui Conch-AEI',
       'Huajian-AEI', 'Solargiga-AEI', 'Sino Great Wall-AEI',
       'Sichuan Department of Agriculture-AEI',
       'Rongsheng Heavy Industries-AEI', 'China General Nuclear-AEI',
       'Dalian Wanda, Ridong-AEI', 'Shanghai Shenglong-AEI',
       'China National Machinery Industry (Sinomach), China National Chemical Engineering-AEI',
       'Huayi Brothers-AEI',
       'Power Construction Corp. (PowerChina), China Energy Engineering-AEI',
       'Anbang-AEI', 'Baidu, Ping An, Qihoo-AEI',
       'Hebei Zhongbo Platinum-AEI', 'Vision Investment-AEI',
       'Sunshine Insurance-AEI', 'Texhong Textile-AEI',
       'Shandong Landbridge-AEI', 'Xinyi Glass-AEI',
       'Haitong Securities-AEI', 'BlueFocus Communications-AEI',
       'Sichuan Xinglida-AEI',
       'Shandong Gaosu, China Aircraft Leasing-AEI',
       'Guangzhou Dongsong-AEI', 'Taikang Life-AEI',
       'Trip.com (formerly Ctrip.com)-AEI', 'Zhejiang Hengyi-AEI',
       'Gansu International Cooperation Corp-AEI',
       'Beijing Uni-Construction-AEI', 'Tencent, Renren-AEI',
       'Gansu Tianqing-AEI',
       'Jiangsu Changjiang, Semiconductor Manufacturing International, National IC Fund-AEI',
       'Zhejiang Huayou Cobalt-AEI',
       'China Launch and Tracking Control General-AEI',
       'Anhui Zhongding-AEI', 'SAIC Motor (Shanghai Auto), Wuling-AEI',
       'Qingdao Sentury-AEI', 'Jinko Solar-AEI', 'Hunan TV-AEI',
       'China Railway Construction, China Energy Engineering-AEI',
       'China Life, Ping An-AEI',
       'Tsinghua Holdings, China International Trust and Investment (CITIC)-AEI',
       'Cybernaut-AEI', 'Yantai Xinchao-AEI',
       'State Construction Engineering, Anhui Foreign Economic Construction-AEI',
       'Trina Solar-AEI', 'BYD-AEI', 'China Communications Bank-AEI',
       'Zhongrun Resources-AEI', 'Jumei-AEI', 'CEFC-AEI',
       'Zhongman Petroleum-AEI', 'ZOJE Resources-AEI',
       'China Minsheng Investment-AEI', 'Uphill Investment-AEI',
       'Aviation Industry Corp. (AVIC), Bank of China-AEI',
       'China National Chemical (ChemChina), State Administration of Foreign Exchange (SAFE)-AEI',
       'Sinolight-AEI',
       'China Railway Corp, China North Industries (Norinco)-AEI',
       'Taiping Life-AEI', 'NetDragon-AEI', 'Sinoenergy-AEI',
       'Hongshi-AEI', 'Power Construction Corp. (PowerChina), HTG-AEI',
       'Power Construction Corp. (PowerChina), China Railway Construction-AEI',
       'Southern Power Grid, State Power Investment-AEI',
       'Jiangnan Mould and Plastic-AEI', 'Shimao-AEI',
       'China Western Power Industrial-AEI',
       'Anton Oilfield Services-AEI', 'Phicomm-AEI', 'Jangho-AEI',
       'Shanghai Municipal Investment-AEI',
       'Bright Foods, JIC, Shenzhen Donghuatong-AEI',
       'China Merchants, China Investment Corporation (CIC), China Ocean Shipping (COSCO)-AEI',
       'Biostime-AEI', 'Didi Kuaidi-AEI', 'Shenzhen Government-AEI',
       'Xian LONGi-AEI', 'Fujian Thai Hot-AEI', 'Genimous Investment-AEI',
       'Angel Yeast-AEI', 'C Banner International-AEI',
       'Moon Lake Investments-AEI',
       'China Investment Corporation (CIC), Didi Kuaidi-AEI',
       'Sinocare-AEI', 'Nantong Fujitsu-AEI', 'Renren-AEI',
       'Shanxi Building Material, Asian and African Business Management-AEI',
       'Zhejiang Holley, Futong Group-AEI', 'Zhejiang Chint-AEI',
       'Shanghai Yuyuan Tourist Mart-AEI',
       'China General Nuclear, Southern Power Grid-AEI',
       'GR Investment, China International Trust and Investment (CITIC)-AEI',
       'China Media Capital, China International Trust and Investment (CITIC)-AEI',
       'Zhuhai Port Holdings, State Construction Engineering-AEI',
       'Landsea-AEI', 'Leyard Optoelectronics-AEI',
       'China Petroleum and Chemical (Sinopec), Jiangxi Water-AEI',
       'Qingdao Hengshun-AEI', 'Luye Life Sciences-AEI',
       'State Power Investment-AEI', 'Highland Fund-AEI',
       'Yunnan Construction Engineering-AEI', 'Liuhe-AEI',
       'Shanghai Inesa-AEI',
       'State Administration of Foreign Exchange (SAFE), China Reform Holdings-AEI',
       'Zhongli-AEI', 'Beijing Municipal Government-AEI',
       'Yunnan Energy Investment-AEI', 'Inspur Group-AEI',
       'China Lilongwe Grand-AEI', 'Zhuzhou Kibing-AEI',
       'China North Industries (Norinco), Shandong Taikai Group-AEI',
       'State Construction Engineering, China Communications Construction-AEI',
       'Chengdu Techcent-AEI', 'Perfect World Pictures-AEI',
       'Visual China-AEI', 'Lifan-AEI',
       'China Communications Construction, China National Petroleum Corp. (CNPC)-AEI',
       'Film Carnival-AEI', 'ENN Energy-AEI', 'Humanwell Healthcare-AEI',
       'Jiangsu Yongding, China National Machinery Industry (Sinomach)-AEI',
       'State Grid, Power Construction Corp. (PowerChina)-AEI',
       'China Light, Jiangxi Jianglian-AEI', 'Zhuhai Zhenrong-AEI',
       'China National Silicon (consortium of Shanghai state firms)-AEI',
       'Jiangsu Sunshine-AEI',
       'Harbin Electric, State Administration of Foreign Exchange (SAFE)-AEI',
       'China Orient Asset Management-AEI', 'Huatai Securities-AEI',
       'Ninestar, Legend-AEI', 'HNA, Jin Jiang International-AEI',
       'Guangdong Heng Fu-AEI',
       "Aviation Industry Corp. (AVIC), Han's Laser-AEI",
       'Zhejiang Kaishan-AEI', 'Shanghai Zhongji-AEI',
       'Tsinghua Holdings-AEI',
       'China Ocean Shipping (COSCO), State Administration of Foreign Exchange (SAFE)-AEI',
       'Qianhai Zone Authority-AEI', 'Recon Group-AEI',
       'China Everbright, Baofeng-AEI',
       'Guangdong Province, Huaneng Power-AEI', 'Guangxi Investment-AEI',
       'Envision Group-AEI', 'Guotsing-AEI',
       'Xinjiang Goldwind, China Energy Conservation-AEI', 'Creat-AEI',
       'China Investment Corporation (CIC), Wise Road Capital-AEI',
       'Spearhead-AEI', 'Everbright-AEI', 'Genzon-AEI',
       'Tencent-led consortium-AEI',
       'Xiwang Group, Primavera Capital-AEI', 'Qihoo, Beijing Kunlun-AEI',
       'China Resources-AEI', 'China Animal Husbandry-AEI',
       'Jiquan Iron and Steel-AEI',
       'IDG Capital, MLS, Yiwu State-Owned Assets-AEI', 'Hailiang-AEI',
       'Zhonghong Zhuoye-AEI', 'Wuhan Zhengtang-AEI',
       'Shanghai Giant Network-led consortium-AEI', 'Suzhou Dongshan-AEI',
       'Tidfore Heavy Equipment-AEI',
       'Shanghai Industrial Holdings, Primavera Capital-AEI',
       'Didi Chuxing-AEI', 'Shanghai Greenland-led consortium-AEI',
       'Yunyi Guokai Shanghai-AEI', 'Fujian Construction Engineering-AEI',
       'Jiangsu Longze-AEI', 'IDG Capital-AEI',
       'Shenyang Blue Silver-AEI', 'Tencent, Legend-AEI',
       'Power Construction Corp. (PowerChina), China Railway Engineering-AEI',
       'Chengdu Tianqi-AEI', 'Chongqing USUM-AEI',
       'Hangzhou Lianluo Interactive-AEI', 'Beijing Miteno-AEI',
       'China Energy Conservation, Jiangsu Dagang, China Tianying-AEI',
       'Beijing Shanhai Capital, National IC Fund-AEI',

In [394]:
new_order = np.concatenate([new_order, ["Average Loan Amount-AEI", "Total Loan Amount-AEI"]])

In [395]:
aei_data = aei_data[new_order]

In [396]:
subsectors

array(['Aviation-AEI', 'Autos-AEI', 'Steel-AEI', 'Construction-AEI',
       'Oil-AEI', 'Coal-AEI', 'Rail-AEI', 'Hydro-AEI', 'Aluminum-AEI',
       'Industry-AEI', 'Property-AEI', 'Gas-AEI', 'Timber-AEI',
       'Alternative-AEI', 'Telecom-AEI', 'Copper-AEI', 'Investment-AEI',
       'Shipping-AEI', 'Banking-AEI', 'Textiles-AEI', 'Education-AEI'],
      dtype=object)

In [397]:
aei_data

              Minmetals-AEI  Chinese Academy of Sciences-AEI  Sinohydro-AEI  \
Country Year
AE      2006            NaN                              NaN            NaN
        2007            NaN                              NaN            1.0
        2008            NaN                              NaN            NaN
        2009            NaN                              NaN            NaN
        2010            NaN                              NaN            NaN
...                     ...                              ...            ...
ZW      2019            NaN                              NaN            NaN
        2020            NaN                              NaN            NaN
        2021            NaN                              NaN            NaN
        2022            NaN                              NaN            NaN
        2023            NaN                              NaN            NaN

              MCC-AEI  Sinoma-AEI  China National Off-shore Oil (CNOOC)-AEI  \
Country Year
AE      2006      NaN         NaN                                       NaN
        2007      NaN         NaN                                       NaN
        2008      NaN         NaN                                       NaN
        2009      NaN         NaN                                       NaN
        2010      NaN         NaN                                       NaN
...               ...         ...                                       ...
ZW      2019      NaN         NaN                                       NaN
        2020      NaN         NaN                                       NaN
        2021      NaN         NaN                                       NaN
        2022      NaN         NaN                                       NaN
        2023      NaN         NaN                                       NaN

              China National Machinery Industry (Sinomach)-AEI  \
Country Year
AE      2006                                               NaN
        2007                                               NaN
        2008                                               NaN
        2009                                               NaN
        2010                                               NaN
...                                                        ...
ZW      2019                                               NaN
        2020                                               NaN
        2021                                               NaN
        2022                                               NaN
        2023                                               NaN

              Minmetals, MCC-AEI  China National Petroleum Corp. (CNPC)-AEI  \
Country Year
AE      2006                 NaN                                        NaN
        2007                 NaN                                        NaN
        2008                 NaN                                        1.0
        2009                 NaN                                        NaN
        2010                 NaN                                        NaN
...                          ...                                        ...
ZW      2019                 NaN                                        NaN
        2020                 NaN                                        NaN
        2021                 NaN                                        NaN
        2022                 NaN                                        NaN
        2023                 NaN                                        NaN

              China Petroleum and Chemical (Sinopec)-AEI  ...  Shipping-AEI  \
Country Year                                              ...
AE      2006                                         NaN  ...           NaN
        2007                                         NaN  ...           NaN
        2008                                         NaN  ...           NaN
        2009                                         NaN  ...           NaN
        2010                                         NaN  ...           NaN
...                                                  ...  ...           ...
ZW      2019                                         NaN  ...           NaN
        2020                                         NaN  ...           NaN
        2021                                         NaN  ...           NaN
        2022                                         NaN  ...           NaN
        2023                                         NaN  ...           NaN

              Banking-AEI  Textiles-AEI  Education-AEI  Q3-AEI  Q4-AEI  \
Country Year
AE      2006          NaN           NaN            NaN     1.0     NaN
        2007          NaN           NaN            NaN     1.0     NaN
        2008          NaN           NaN            NaN     NaN     1.0
        2009          NaN           NaN            NaN     1.0     NaN
        2010          NaN           NaN            NaN     NaN     NaN
...                   ...           ...            ...     ...     ...
ZW      2019          NaN           NaN            NaN     NaN     NaN
        2020          NaN           NaN            NaN     NaN     1.0
        2021          NaN           NaN            NaN     1.0     NaN
        2022          NaN           NaN            NaN     1.0     1.0
        2023          NaN           NaN            NaN     NaN     NaN

              Q1-AEI  Q2-AEI  Average Loan Amount-AEI  Total Loan Amount-AEI
Country Year
AE      2006     NaN     NaN               300.000000                  300.0
        2007     1.0     1.0               216.666672                  650.0
        2008     NaN     1.0              1775.000000                 3550.0
        2009     NaN     1.0               335.000000                  670.0
        2010     1.0     NaN               130.000000                  130.0
...              ...     ...                      ...                    ...
ZW      2019     NaN     2.0               220.000000                  440.0
        2020     NaN     NaN               630.000000                  630.0
        2021     2.0     NaN               220.000000                  660.0
        2022     NaN     2.0               357.500000                 1430.0
        2023     NaN     1.0               180.000000                  180.0

[1369 rows x 938 columns]

In [398]:
aei_data.fillna(0, inplace = True)

In [399]:
aei_data.reset_index(inplace = True)

In [400]:
aei_data = aei_data.sort_values(["Year", "Country"])

In [401]:
aei_data

,Country,Year,Minmetals-AEI,Chinese Academy of Sciences-AEI,Sinohydro-AEI,MCC-AEI,Sinoma-AEI,China National Off-shore Oil (CNOOC)-AEI,China National Machinery Industry (Sinomach)-AEI,"Minmetals, MCC-AEI",...,Shipping-AEI,Banking-AEI,Textiles-AEI,Education-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
24,AO,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,210.000000,210.0
57,AU,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,160.000000,320.0
139,BR,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,335.000000,670.0
175,CA,2005,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,125.000000,250.0
267,CU,2005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,500.000000,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,UZ,2023,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,316.666656,1900.0
1318,VN,2023,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,221.250000,1770.0
1337,ZA,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,165.000000,330.0
1354,ZM,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,313.333344,940.0
1368,ZW,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,180.000000,180.0

In [402]:
aei_data[new_order] = aei_data[new_order].apply(lambda x: x.apply(lambda y: np.nan) if x.sum() < 50 else x)

In [403]:
def drop_column_conditionally(x):
    for column in x.columns:
        if x[column].isnull().all():
            x.drop(column, axis = 1, inplace = True)
        

drop_column_conditionally(aei_data)
aei_data

,Country,Year,Minmetals-AEI,Sinohydro-AEI,Sinoma-AEI,China National Machinery Industry (Sinomach)-AEI,China National Petroleum Corp. (CNPC)-AEI,China Petroleum and Chemical (Sinopec)-AEI,China Communications Construction-AEI,China International Trust and Investment (CITIC)-AEI,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
24,AO,2005,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,210.000000,210.0
57,AU,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,160.000000,320.0
139,BR,2005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,335.000000,670.0
175,CA,2005,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,125.000000,250.0
267,CU,2005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,500.000000,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,UZ,2023,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,3.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,316.666656,1900.0
1318,VN,2023,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,221.250000,1770.0
1337,ZA,2023,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,165.000000,330.0
1354,ZM,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,313.333344,940.0
1368,ZW,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,180.000000,180.0

In [404]:
type(aei_data["Year"][0])

numpy.int64

In [405]:
aei_data.set_index(["Country", "Year"], inplace = True)

In [406]:
loan_debt_data = pd.concat([loan_debt_data, aei_data], axis = 1, join = "outer")

In [407]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UZ,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,316.666656,1900.0
VN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,221.250000,1770.0
ZA,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,165.000000,330.0
ZM,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,313.333344,940.0
ZW,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,180.000000,180.0

In [408]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UZ,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,316.666656,1900.0
VN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,221.250000,1770.0
ZA,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,165.000000,330.0
ZM,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,313.333344,940.0
ZW,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,180.000000,180.0

In [409]:
loan_debt_data.reset_index(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)

In [410]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
0,AF,2000,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AL,2000,63.376463,63.768684,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DZ,2000,57.960343,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AO,2000,133.914140,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AG,2000,105.132373,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4469,UZ,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,316.666656,1900.0
4470,VN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,221.250000,1770.0
4471,ZA,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,165.000000,330.0
4472,ZM,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,313.333344,940.0
4473,ZW,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,180.000000,180.0

In [411]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] <= 2021]

In [412]:
loan_debt_data = loan_debt_data[loan_debt_data["Year"] >= 2005]

In [413]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
865,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
866,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867,DZ,2005,26.311385,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,300.0,600.0
868,AO,2005,33.464042,NaN,1.0,8.0,0.0,0.0,1.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,210.0,210.0
869,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4389,CU,2020,NaN,NaN,4.0,0.0,0.0,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,CU,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,100.0,100.0

In [414]:
np.unique(loan_debt_data["Country"])

array(['AE', 'AF', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA',
       'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR',
       'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI',
       'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CY', 'CZ', 'DE',
       'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ER', 'ES', 'ET',
       'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN',
       'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID',
       'IE', 'IL', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE',
       'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KZ', 'LA', 'LB',
       'LC', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MD', 'ME',
       'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MR', 'MT', 'MU', 'MV', 'MW',
       'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR',
       'NU', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT',
       'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE',
       'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV',
       'SY', 'SZ', 'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR',
       'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VE',
       'VN', 'VU', 'WS', 'YE', 'ZA', 'ZM', 'ZW'], dtype=object)

In [415]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [416]:
loan_debt_data

,,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,Representational,ACTION RELATING TO DEBT,...,Alternative-AEI,Telecom-AEI,Copper-AEI,Shipping-AEI,Q3-AEI,Q4-AEI,Q1-AEI,Q2-AEI,Average Loan Amount-AEI,Total Loan Amount-AEI
Country,Year,,,,,,,,,,,,,,,,,,,,,
AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DZ,2005,26.311385,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,300.0,600.0
AO,2005,33.464042,NaN,1.0,8.0,0.0,0.0,1.0,8.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,210.0,210.0
AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CU,2020,NaN,NaN,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KP,2020,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CU,2021,NaN,NaN,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SO,2021,NaN,NaN,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CU,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,100.0,100.0

In [417]:
indicators_to_choose = pd.read_csv("Data/V-Dem Indicators Modified.csv")

In [418]:
indicators_to_choose.columns

Index(['country_name', 'year', 'v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem',
       'v2smgovfilcap', 'v2smgovfilcap_ord', 'v2smgovfilprc',
       'v2smgovfilprc_ord', 'v2smgovshutcap', 'v2smgovshutcap_ord',
       'v2smgovshut', 'v2smgovsm_ord', 'v2smgovsmmon', 'v2smgovsmmon_ord',
       'v2smgovsmcenprc', 'v2smgovsmcenprc_ord', 'v2smarrest',
       'v2smarrest_ord', 'e_fh_cl', 'e_fh_pr', 'e_fh_rol', 'e_wbgi_cce',
       'e_wbgi_gee', 'e_wbgi_pve', 'e_autoc', 'e_democ', 'e_p_polity', 'e_gdp',
       'e_pop'],
      dtype='object')

In [419]:
indicators = indicators_to_choose.iloc[:,[2,3,4]]

In [420]:
select = np.array(indicators.columns)

In [421]:
other_select = np.array(indicators_to_choose.columns[19:])

In [422]:
select = np.concatenate([select, other_select])

In [423]:
select

array(['v2x_polyarchy', 'v2x_libdem', 'v2x_partipdem', 'e_fh_cl',
       'e_fh_pr', 'e_fh_rol', 'e_wbgi_cce', 'e_wbgi_gee', 'e_wbgi_pve',
       'e_autoc', 'e_democ', 'e_p_polity', 'e_gdp', 'e_pop'], dtype=object)

In [424]:
all_indicators = pd.read_csv("Data/V-Dem Indicators.csv")

In [425]:
all_indicators = all_indicators.rename({"country_name": "Country", "year": "Year"}, axis = 1)

In [426]:
all_indicators = all_indicators.replace(name_to_alpha_2)

In [427]:
all_indicators.set_index(["Country", "Year"], inplace = True)

In [428]:
all_indicators = all_indicators[select]

In [429]:
all_indicators.reset_index(inplace = True)

In [430]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
0,MX,1789,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,871.938,645.627
1,MX,1790,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,878.908,647.112
2,MX,1791,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.411,647.464
3,MX,1792,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902.880,649.721
4,MX,1793,0.028,0.042,0.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,912.872,650.911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27550,Piedmont-Sardinia,1857,0.207,0.135,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27551,Piedmont-Sardinia,1858,0.210,0.136,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27552,Piedmont-Sardinia,1859,0.210,0.136,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27553,Piedmont-Sardinia,1860,0.213,0.137,0.064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27554,Piedmont-Sardinia,1861,0.213,0.137,0.075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [431]:
all_indicators = all_indicators[all_indicators["Year"] >= 2005]

In [432]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
216,MX,2005,0.710,0.510,0.441,2.0,2.0,8.0,-0.344,0.033,-0.446,0.0,8.0,8.0,162093.745,11313.743
217,MX,2006,0.675,0.482,0.417,3.0,2.0,8.0,-0.325,0.052,-0.637,0.0,8.0,8.0,167391.970,11479.812
218,MX,2007,0.644,0.454,0.397,3.0,2.0,7.0,-0.341,0.139,-0.730,0.0,8.0,8.0,171691.031,11657.849
219,MX,2008,0.643,0.456,0.394,3.0,2.0,6.0,-0.310,0.164,-0.804,0.0,8.0,8.0,174203.808,11795.028
220,MX,2009,0.641,0.455,0.395,3.0,2.0,6.0,-0.366,0.145,-0.687,0.0,8.0,8.0,171738.827,11908.825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26151,TZ,2018,0.268,0.223,0.177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26152,TZ,2019,0.266,0.215,0.169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26153,TZ,2020,0.258,0.209,0.165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26154,TZ,2021,0.276,0.225,0.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26155,TZ,2022,0.284,0.233,0.173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [433]:
np.unique(all_indicators["Country"])

array(['AE', 'AF', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB',
       'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BO', 'BR', 'BT', 'BW',
       'BY', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CL', 'CM', 'CN', 'CO',
       'CR', 'CU', 'CV', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DO', 'DZ', 'EC',
       'EE', 'EG', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FR', 'GA', 'GB', 'GE',
       'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR',
       'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JM',
       'JO', 'JP', 'KE', 'KG', 'KH', 'KM', 'KP', 'KR', 'KW', 'KZ', 'LA',
       'LB', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MD', 'ME',
       'MG', 'MK', 'ML', 'MM', 'MN', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX',
       'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NZ', 'OM',
       'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PY', 'QA', 'RO',
       'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SI', 'SK',
       'SL', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SY', 'SZ', 'Somaliland',
       'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TR', 'TT', 'TW', 'TZ',
       'UA', 'UG', 'US', 'UY', 'UZ', 'VE', 'VN', 'VU', 'XK', 'YE', 'ZA',
       'ZM', 'ZW'], dtype=object)

In [434]:
all_indicators = all_indicators.sort_values(["Year", "Country"])

In [435]:
all_indicators

,Country,Year,v2x_polyarchy,v2x_libdem,v2x_partipdem,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
25706,AE,2005,0.020,0.069,0.017,6.0,6.0,4.0,0.991,0.705,0.875,8.0,0.0,-8.0,44675.582,502.176
5478,AF,2005,0.335,0.137,0.139,5.0,5.0,4.0,-1.447,-1.217,-2.068,-66.0,-66.0,-66.0,2912.684,2746.122
1855,AL,2005,0.505,0.415,0.333,3.0,3.0,10.0,-0.813,-0.705,-0.505,0.0,9.0,9.0,2140.925,321.135
15962,AM,2005,0.346,0.192,0.186,4.0,5.0,6.0,-0.683,-0.139,-0.066,0.0,5.0,5.0,2085.719,315.380
15929,AO,2005,0.176,0.092,0.060,5.0,6.0,4.0,-1.323,-1.106,-0.885,4.0,2.0,-2.0,7375.750,1860.841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6656,XK,2022,0.618,0.463,0.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2273,YE,2022,0.123,0.045,0.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,ZA,2022,0.692,0.581,0.430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9242,ZM,2022,0.518,0.433,0.352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9365,ZW,2022,0.285,0.186,0.215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [436]:
all_indicators = all_indicators.groupby(['Country', 'Year']).mean()

In [437]:
all_indicators

              v2x_polyarchy  v2x_libdem  v2x_partipdem  e_fh_cl  e_fh_pr  \
Country Year
AE      2005          0.020       0.069          0.017      6.0      6.0
        2006          0.024       0.071          0.017      5.0      6.0
        2007          0.069       0.079          0.022      5.0      6.0
        2008          0.070       0.080          0.022      5.0      6.0
        2009          0.070       0.080          0.022      5.0      6.0
...                     ...         ...            ...      ...      ...
ZW      2018          0.305       0.214          0.243      5.0      5.0
        2019          0.293       0.201          0.234      5.0      5.0
        2020          0.293       0.196          0.222      5.0      6.0
        2021          0.291       0.194          0.221      5.0      6.0
        2022          0.285       0.186          0.215      NaN      NaN

              e_fh_rol  e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  \
Country Year
AE      2005       4.0       0.991       0.705       0.875      8.0      0.0
        2006       4.0       0.886       0.937       0.923      8.0      0.0
        2007       3.0       1.006       0.917       0.975      8.0      0.0
        2008       4.0       1.071       0.868       0.696      8.0      0.0
        2009       4.0       0.906       0.987       0.919      8.0      0.0
...                ...         ...         ...         ...      ...      ...
ZW      2018       2.0      -1.228      -1.262      -0.723      1.0      5.0
        2019       2.0      -1.273      -1.267      -0.960      NaN      NaN
        2020       2.0      -1.289      -1.300      -1.072      NaN      NaN
        2021       NaN      -1.258      -1.243      -1.027      NaN      NaN
        2022       NaN         NaN         NaN         NaN      NaN      NaN

              e_p_polity      e_gdp     e_pop
Country Year
AE      2005        -8.0  44675.582   502.176
        2006        -8.0  49070.524   576.779
        2007        -8.0  51953.349   658.203
        2008        -8.0  53685.703   747.211
        2009        -8.0  51878.656   822.599
...                  ...        ...       ...
ZW      2018         4.0   4857.211  1564.405
        2019         NaN   4870.709  1566.385
        2020         NaN        NaN       NaN
        2021         NaN        NaN       NaN
        2022         NaN        NaN       NaN

[3180 rows x 14 columns]

In [438]:
all_indicators.reset_index (inplace = True)

In [439]:
all_indicators = all_indicators.sort_values(["Year", "Country"])

In [440]:
all_indicators = all_indicators[all_indicators["Year"] <= 2021]

In [441]:
loan_debt_data.reset_index(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)

In [442]:
all_indicators = all_indicators[all_indicators["Country"].isin(loan_debt_data["Country"])]

In [443]:
loan_debt_data = loan_debt_data.sort_values(["Year", "Country"])

In [444]:
all_indicators.set_index(["Country", "Year"], inplace = True)

In [445]:
loan_debt_data.set_index(["Country", "Year"], inplace = True)

In [446]:
loan_debt_data = pd.concat([loan_debt_data, all_indicators], axis = 1, join = "outer")

In [447]:

loan_debt_data

              Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                                    NaN
AF      2005                             206.356007
AG      2005                              92.614383
AL      2005                              58.199553
AM      2005                              20.467167
...                                             ...
KP      2018                                    NaN
        2019                                    NaN
SO      2019                                    NaN
        2020                                    NaN
KP      2021                                    NaN

              General Govt Debt (Percentage of GDP)  Grant  Loan  Vague  \
Country Year
AE      2005                               4.481497    0.0   0.0    0.0
AF      2005                                    NaN    1.0   0.0    0.0
AG      2005                                    NaN    1.0   1.0    0.0
AL      2005                              58.203359    1.0   0.0    0.0
AM      2005                                    NaN    0.0   0.0    0.0
...                                             ...    ...   ...    ...
KP      2018                                    NaN    NaN   NaN    NaN
        2019                                    NaN    NaN   NaN    NaN
SO      2019                                    NaN    NaN   NaN    NaN
        2020                                    NaN    NaN   NaN    NaN
KP      2021                                    NaN    NaN   NaN    NaN

              Commercial  Development  Mixed  Representational  \
Country Year
AE      2005         0.0          0.0    0.0               0.0
AF      2005         0.0          1.0    0.0               0.0
AG      2005         0.0          2.0    0.0               0.0
AL      2005         0.0          1.0    0.0               0.0
AM      2005         0.0          0.0    0.0               0.0
...                  ...          ...    ...               ...
KP      2018         NaN          NaN    NaN               NaN
        2019         NaN          NaN    NaN               NaN
SO      2019         NaN          NaN    NaN               NaN
        2020         NaN          NaN    NaN               NaN
KP      2021         NaN          NaN    NaN               NaN

              ACTION RELATING TO DEBT  ...  e_fh_pr  e_fh_rol  e_wbgi_cce  \
Country Year                           ...
AE      2005                      0.0  ...      6.0       4.0       0.991
AF      2005                      0.0  ...      5.0       4.0      -1.447
AG      2005                      0.0  ...      NaN       NaN         NaN
AL      2005                      0.0  ...      3.0      10.0      -0.813
AM      2005                      0.0  ...      5.0       6.0      -0.683
...                               ...  ...      ...       ...         ...
KP      2018                      NaN  ...      7.0       0.0      -1.571
        2019                      NaN  ...      7.0       0.0      -1.594
SO      2019                      NaN  ...      7.0       0.0      -1.709
        2020                      NaN  ...      7.0       0.0      -1.671
KP      2021                      NaN  ...      7.0       NaN      -1.605

              e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  e_p_polity      e_gdp  \
Country Year
AE      2005       0.705       0.875      8.0      0.0        -8.0  44675.582
AF      2005      -1.217      -2.068    -66.0    -66.0       -66.0   2912.684
AG      2005         NaN         NaN      NaN      NaN         NaN        NaN
AL      2005      -0.705      -0.505      0.0      9.0         9.0   2140.925
AM      2005      -0.139      -0.066      0.0      5.0         5.0   2085.719
...                  ...         ...      ...      ...         ...        ...
KP      2018      -1.573      -0.348     10.0      0.0       -10.0   4867.297
        2019      -1.398      -0.318      NaN      NaN         NaN   4873.972
SO      2019      -2.251      -2.387      NaN      NaN         NaN   2710.709
        2020      -2.109      -2.577      NaN      NaN         NaN        NaN
KP      2021      -1.557      -0.453      NaN      NaN         NaN        NaN

                 e_pop
Country Year
AE      2005   502.176
AF      2005  2746.122
AG      2005       NaN
AL      2005   321.135
AM      2005   315.380
...                ...
KP      2018  2712.980
        2019  2717.578
SO      2019  1581.318
        2020       NaN
KP      2021       NaN

[3274 rows x 131 columns]

In [448]:
loan_debt_data["gdp_per_cap"] = loan_debt_data["e_gdp"] / loan_debt_data["e_pop"]

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\4010968969.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data["gdp_per_cap"] = loan_debt_data["e_gdp"] / loan_debt_data["e_pop"]

In [449]:
loan_debt_data

              Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                                    NaN
AF      2005                             206.356007
AG      2005                              92.614383
AL      2005                              58.199553
AM      2005                              20.467167
...                                             ...
KP      2018                                    NaN
        2019                                    NaN
SO      2019                                    NaN
        2020                                    NaN
KP      2021                                    NaN

              General Govt Debt (Percentage of GDP)  Grant  Loan  Vague  \
Country Year
AE      2005                               4.481497    0.0   0.0    0.0
AF      2005                                    NaN    1.0   0.0    0.0
AG      2005                                    NaN    1.0   1.0    0.0
AL      2005                              58.203359    1.0   0.0    0.0
AM      2005                                    NaN    0.0   0.0    0.0
...                                             ...    ...   ...    ...
KP      2018                                    NaN    NaN   NaN    NaN
        2019                                    NaN    NaN   NaN    NaN
SO      2019                                    NaN    NaN   NaN    NaN
        2020                                    NaN    NaN   NaN    NaN
KP      2021                                    NaN    NaN   NaN    NaN

              Commercial  Development  Mixed  Representational  \
Country Year
AE      2005         0.0          0.0    0.0               0.0
AF      2005         0.0          1.0    0.0               0.0
AG      2005         0.0          2.0    0.0               0.0
AL      2005         0.0          1.0    0.0               0.0
AM      2005         0.0          0.0    0.0               0.0
...                  ...          ...    ...               ...
KP      2018         NaN          NaN    NaN               NaN
        2019         NaN          NaN    NaN               NaN
SO      2019         NaN          NaN    NaN               NaN
        2020         NaN          NaN    NaN               NaN
KP      2021         NaN          NaN    NaN               NaN

              ACTION RELATING TO DEBT  ...  e_fh_rol  e_wbgi_cce  e_wbgi_gee  \
Country Year                           ...
AE      2005                      0.0  ...       4.0       0.991       0.705
AF      2005                      0.0  ...       4.0      -1.447      -1.217
AG      2005                      0.0  ...       NaN         NaN         NaN
AL      2005                      0.0  ...      10.0      -0.813      -0.705
AM      2005                      0.0  ...       6.0      -0.683      -0.139
...                               ...  ...       ...         ...         ...
KP      2018                      NaN  ...       0.0      -1.571      -1.573
        2019                      NaN  ...       0.0      -1.594      -1.398
SO      2019                      NaN  ...       0.0      -1.709      -2.251
        2020                      NaN  ...       0.0      -1.671      -2.109
KP      2021                      NaN  ...       NaN      -1.605      -1.557

              e_wbgi_pve  e_autoc  e_democ  e_p_polity      e_gdp     e_pop  \
Country Year
AE      2005       0.875      8.0      0.0        -8.0  44675.582   502.176
AF      2005      -2.068    -66.0    -66.0       -66.0   2912.684  2746.122
AG      2005         NaN      NaN      NaN         NaN        NaN       NaN
AL      2005      -0.505      0.0      9.0         9.0   2140.925   321.135
AM      2005      -0.066      0.0      5.0         5.0   2085.719   315.380
...                  ...      ...      ...         ...        ...       ...
KP      2018      -0.348     10.0      0.0       -10.0   4867.297  2712.980
        2019      -0.318      NaN      NaN         NaN   4873.972  2717.578
SO      2019      -2.387      NaN      NaN         NaN   2710.709  1581.318
        2020      -2.577      NaN      NaN         NaN        NaN       NaN
KP      2021      -0.453      NaN      NaN         NaN        NaN       NaN

              gdp_per_cap
Country Year
AE      2005    88.963993
AF      2005     1.060654
AG      2005          NaN
AL      2005     6.666745
AM      2005     6.613352
...                   ...
KP      2018     1.794078
        2019     1.793498
SO      2019     1.714209
        2020          NaN
KP      2021          NaN

[3274 rows x 132 columns]

In [450]:
loan_debt_data

              Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                                    NaN
AF      2005                             206.356007
AG      2005                              92.614383
AL      2005                              58.199553
AM      2005                              20.467167
...                                             ...
KP      2018                                    NaN
        2019                                    NaN
SO      2019                                    NaN
        2020                                    NaN
KP      2021                                    NaN

              General Govt Debt (Percentage of GDP)  Grant  Loan  Vague  \
Country Year
AE      2005                               4.481497    0.0   0.0    0.0
AF      2005                                    NaN    1.0   0.0    0.0
AG      2005                                    NaN    1.0   1.0    0.0
AL      2005                              58.203359    1.0   0.0    0.0
AM      2005                                    NaN    0.0   0.0    0.0
...                                             ...    ...   ...    ...
KP      2018                                    NaN    NaN   NaN    NaN
        2019                                    NaN    NaN   NaN    NaN
SO      2019                                    NaN    NaN   NaN    NaN
        2020                                    NaN    NaN   NaN    NaN
KP      2021                                    NaN    NaN   NaN    NaN

              Commercial  Development  Mixed  Representational  \
Country Year
AE      2005         0.0          0.0    0.0               0.0
AF      2005         0.0          1.0    0.0               0.0
AG      2005         0.0          2.0    0.0               0.0
AL      2005         0.0          1.0    0.0               0.0
AM      2005         0.0          0.0    0.0               0.0
...                  ...          ...    ...               ...
KP      2018         NaN          NaN    NaN               NaN
        2019         NaN          NaN    NaN               NaN
SO      2019         NaN          NaN    NaN               NaN
        2020         NaN          NaN    NaN               NaN
KP      2021         NaN          NaN    NaN               NaN

              ACTION RELATING TO DEBT  ...  e_fh_rol  e_wbgi_cce  e_wbgi_gee  \
Country Year                           ...
AE      2005                      0.0  ...       4.0       0.991       0.705
AF      2005                      0.0  ...       4.0      -1.447      -1.217
AG      2005                      0.0  ...       NaN         NaN         NaN
AL      2005                      0.0  ...      10.0      -0.813      -0.705
AM      2005                      0.0  ...       6.0      -0.683      -0.139
...                               ...  ...       ...         ...         ...
KP      2018                      NaN  ...       0.0      -1.571      -1.573
        2019                      NaN  ...       0.0      -1.594      -1.398
SO      2019                      NaN  ...       0.0      -1.709      -2.251
        2020                      NaN  ...       0.0      -1.671      -2.109
KP      2021                      NaN  ...       NaN      -1.605      -1.557

              e_wbgi_pve  e_autoc  e_democ  e_p_polity      e_gdp     e_pop  \
Country Year
AE      2005       0.875      8.0      0.0        -8.0  44675.582   502.176
AF      2005      -2.068    -66.0    -66.0       -66.0   2912.684  2746.122
AG      2005         NaN      NaN      NaN         NaN        NaN       NaN
AL      2005      -0.505      0.0      9.0         9.0   2140.925   321.135
AM      2005      -0.066      0.0      5.0         5.0   2085.719   315.380
...                  ...      ...      ...         ...        ...       ...
KP      2018      -0.348     10.0      0.0       -10.0   4867.297  2712.980
        2019      -0.318      NaN      NaN         NaN   4873.972  2717.578
SO      2019      -2.387      NaN      NaN         NaN   2710.709  1581.318
        2020      -2.577      NaN      NaN         NaN        NaN       NaN
KP      2021      -0.453      NaN      NaN         NaN        NaN       NaN

              gdp_per_cap
Country Year
AE      2005    88.963993
AF      2005     1.060654
AG      2005          NaN
AL      2005     6.666745
AM      2005     6.613352
...                   ...
KP      2018     1.794078
        2019     1.793498
SO      2019     1.714209
        2020          NaN
KP      2021          NaN

[3274 rows x 132 columns]

In [451]:
cpi_data = pd.read_csv("Data/CPI2023_GlobalResultsTrends.csv")

In [452]:
cpi_data

,ISO3,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012
0,AFG,20.0,24.0,16.0,19.0,16.0,16.0,15.0,15.0,11.0,12.0,8.0,8.0
1,ALB,37.0,36.0,35.0,36.0,35.0,36.0,38.0,39.0,36.0,33.0,31.0,33.0
2,DZA,36.0,33.0,33.0,36.0,35.0,35.0,33.0,34.0,36.0,36.0,36.0,34.0
3,AGO,33.0,33.0,29.0,27.0,26.0,19.0,19.0,18.0,15.0,19.0,23.0,22.0
4,ARG,37.0,38.0,38.0,42.0,45.0,40.0,39.0,36.0,32.0,34.0,34.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,VEN,13.0,14.0,14.0,15.0,16.0,18.0,18.0,17.0,17.0,19.0,20.0,19.0
177,VNM,41.0,42.0,39.0,36.0,37.0,33.0,35.0,33.0,31.0,31.0,31.0,31.0
178,YEM,16.0,16.0,16.0,15.0,15.0,14.0,16.0,14.0,18.0,19.0,18.0,23.0
179,ZMB,37.0,33.0,33.0,33.0,34.0,35.0,37.0,38.0,38.0,38.0,38.0,37.0
180,ZWE,24.0,23.0,23.0,24.0,24.0,22.0,22.0,22.0,21.0,21.0,21.0,20.0

In [453]:
cpi_data = pd.melt(cpi_data, id_vars = "ISO3", var_name = "Year", value_name = "CPI")

In [454]:
cpi_data

     ISO3  Year   CPI
0     AFG  2023  20.0
1     ALB  2023  37.0
2     DZA  2023  36.0
3     AGO  2023  33.0
4     ARG  2023  37.0
...   ...   ...   ...
2167  VEN  2012  19.0
2168  VNM  2012  31.0
2169  YEM  2012  23.0
2170  ZMB  2012  37.0
2171  ZWE  2012  20.0

[2172 rows x 3 columns]

In [455]:
cpi_data = cpi_data.rename({"ISO3": "Country"}, axis = 1)

In [456]:
cpi_data = cpi_data.replace(alpha_3_to_alpha_2)

In [457]:
cpi_data

     Country  Year   CPI
0         AF  2023  20.0
1         AL  2023  37.0
2         DZ  2023  36.0
3         AO  2023  33.0
4         AR  2023  37.0
...      ...   ...   ...
2167      VE  2012  19.0
2168      VN  2012  31.0
2169      YE  2012  23.0
2170      ZM  2012  37.0
2171      ZW  2012  20.0

[2172 rows x 3 columns]

In [458]:
cpi_data = cpi_data.sort_values(["Year", "Country"])

In [459]:
cpi_data["Year"] = pd.to_numeric(cpi_data["Year"])

In [460]:
cpi_data = cpi_data[cpi_data["Year"] <= 2021]

In [461]:
cpi_data = cpi_data[cpi_data["Country"].isin(loan_debt_data.index.get_level_values(0))]

In [462]:
cpi_data.set_index(["Country", "Year"], inplace = True)

In [463]:
cpi_data

               CPI
Country Year
AE      2012  68.0
AF      2012   8.0
AL      2012  33.0
AM      2012  34.0
AO      2012  22.0
...            ...
VU      2021  45.0
YE      2021  16.0
ZA      2021  44.0
ZM      2021  33.0
ZW      2021  23.0

[1800 rows x 1 columns]

In [464]:
loan_debt_data = pd.concat([loan_debt_data, cpi_data], axis = 1, join = "outer")

In [465]:
loan_debt_data

              Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                                    NaN
AF      2005                             206.356007
AG      2005                              92.614383
AL      2005                              58.199553
AM      2005                              20.467167
...                                             ...
KP      2018                                    NaN
        2019                                    NaN
SO      2019                                    NaN
        2020                                    NaN
KP      2021                                    NaN

              General Govt Debt (Percentage of GDP)  Grant  Loan  Vague  \
Country Year
AE      2005                               4.481497    0.0   0.0    0.0
AF      2005                                    NaN    1.0   0.0    0.0
AG      2005                                    NaN    1.0   1.0    0.0
AL      2005                              58.203359    1.0   0.0    0.0
AM      2005                                    NaN    0.0   0.0    0.0
...                                             ...    ...   ...    ...
KP      2018                                    NaN    NaN   NaN    NaN
        2019                                    NaN    NaN   NaN    NaN
SO      2019                                    NaN    NaN   NaN    NaN
        2020                                    NaN    NaN   NaN    NaN
KP      2021                                    NaN    NaN   NaN    NaN

              Commercial  Development  Mixed  Representational  \
Country Year
AE      2005         0.0          0.0    0.0               0.0
AF      2005         0.0          1.0    0.0               0.0
AG      2005         0.0          2.0    0.0               0.0
AL      2005         0.0          1.0    0.0               0.0
AM      2005         0.0          0.0    0.0               0.0
...                  ...          ...    ...               ...
KP      2018         NaN          NaN    NaN               NaN
        2019         NaN          NaN    NaN               NaN
SO      2019         NaN          NaN    NaN               NaN
        2020         NaN          NaN    NaN               NaN
KP      2021         NaN          NaN    NaN               NaN

              ACTION RELATING TO DEBT  ...  e_wbgi_cce  e_wbgi_gee  \
Country Year                           ...
AE      2005                      0.0  ...       0.991       0.705
AF      2005                      0.0  ...      -1.447      -1.217
AG      2005                      0.0  ...         NaN         NaN
AL      2005                      0.0  ...      -0.813      -0.705
AM      2005                      0.0  ...      -0.683      -0.139
...                               ...  ...         ...         ...
KP      2018                      NaN  ...      -1.571      -1.573
        2019                      NaN  ...      -1.594      -1.398
SO      2019                      NaN  ...      -1.709      -2.251
        2020                      NaN  ...      -1.671      -2.109
KP      2021                      NaN  ...      -1.605      -1.557

              e_wbgi_pve  e_autoc  e_democ  e_p_polity      e_gdp     e_pop  \
Country Year
AE      2005       0.875      8.0      0.0        -8.0  44675.582   502.176
AF      2005      -2.068    -66.0    -66.0       -66.0   2912.684  2746.122
AG      2005         NaN      NaN      NaN         NaN        NaN       NaN
AL      2005      -0.505      0.0      9.0         9.0   2140.925   321.135
AM      2005      -0.066      0.0      5.0         5.0   2085.719   315.380
...                  ...      ...      ...         ...        ...       ...
KP      2018      -0.348     10.0      0.0       -10.0   4867.297  2712.980
        2019      -0.318      NaN      NaN         NaN   4873.972  2717.578
SO      2019      -2.387      NaN      NaN         NaN   2710.709  1581.318
        2020      -2.577      NaN      NaN         NaN        NaN       NaN
KP      2021      -0.453      NaN      NaN         NaN        NaN       NaN

              gdp_per_cap   CPI
Country Year
AE      2005    88.963993   NaN
AF      2005     1.060654   NaN
AG      2005          NaN   NaN
AL      2005     6.666745   NaN
AM      2005     6.613352   NaN
...                   ...   ...
KP      2018     1.794078  14.0
        2019     1.793498  17.0
SO      2019     1.714209   9.0
        2020          NaN  12.0
KP      2021          NaN  16.0

[3274 rows x 133 columns]

In [466]:
peaceful = pd.read_csv("Data/peaceful.csv")

In [467]:
peaceful = peaceful.drop(["sub_event_type","Unnamed: 3"], axis = 1)

In [468]:
peaceful = peaceful.rename({"country": "Country", "year": "Year"}, axis = 1)

In [469]:
peaceful = peaceful.groupby(["Country", "Year"]).size().reset_index(name = "Peaceful Count")

In [470]:
peaceful = peaceful.replace(name_to_alpha_2)

In [471]:
peaceful = peaceful.sort_values(["Year", "Country"])

In [472]:
peaceful = peaceful[peaceful["Country"].isin(loan_debt_data.index.get_level_values(0))]

In [473]:
peaceful.set_index(["Country", "Year"], inplace = True)

In [474]:
intervention = pd.read_csv("Data/intervention.csv")

In [475]:
intervention

       year             sub_event_type     country
0      2020  Protest with intervention      Turkey
1      2020  Protest with intervention     Nigeria
2      2020  Protest with intervention     Morocco
3      2020  Protest with intervention       China
4      2020  Protest with intervention     Denmark
...     ...                        ...         ...
21361  2010  Protest with intervention    Ethiopia
21362  2010  Protest with intervention  Bangladesh
21363  2010  Protest with intervention       Egypt
21364  2010  Protest with intervention       Egypt
21365  2010  Protest with intervention  Bangladesh

[21366 rows x 3 columns]

In [476]:
intervention.drop(["sub_event_type"], axis = 1, inplace = True)

In [477]:
intervention

       year     country
0      2020      Turkey
1      2020     Nigeria
2      2020     Morocco
3      2020       China
4      2020     Denmark
...     ...         ...
21361  2010    Ethiopia
21362  2010  Bangladesh
21363  2010       Egypt
21364  2010       Egypt
21365  2010  Bangladesh

[21366 rows x 2 columns]

In [478]:
intervention.rename({"country": "Country", "year": "Year"}, axis = 1, inplace = True)

In [479]:
intervention = intervention.groupby(["Country", "Year"]).size().reset_index(name = "Intervention Count")

In [480]:
intervention = intervention.replace(name_to_alpha_2)

In [481]:
intervention.sort_values(["Year", "Country"], inplace = True)

In [482]:
intervention = intervention[intervention["Country"].isin(loan_debt_data.index.get_level_values(0))]

In [483]:
intervention.set_index(["Country", "Year"], inplace = True)

In [484]:
excessive = pd.read_csv("Data/excessive.csv")

In [485]:
excessive.drop(["sub_event_type"], axis = 1, inplace = True)

In [486]:
excessive.rename({"country": "Country", "year": "Year"}, axis = 1, inplace = True)

In [487]:
excessive = excessive.groupby(["Country", "Year"]).size().reset_index(name = "Excessive Count")

In [488]:
excessive = excessive.replace(name_to_alpha_2)

In [489]:
excessive.sort_values(["Year", "Country"], inplace = True)

In [490]:
excessive = excessive[excessive["Country"].isin(loan_debt_data.index.get_level_values(0))]

In [491]:
excessive.set_index(["Country", "Year"], inplace = True)

In [492]:
loan_debt_data = pd.concat([loan_debt_data, peaceful, intervention, excessive], axis = 1, join = "outer")

In [493]:
loan_debt_data

              Central Govt Debt (Percentage of GDP)  \
Country Year
AE      2005                                    NaN
AF      2005                             206.356007
AG      2005                              92.614383
AL      2005                              58.199553
AM      2005                              20.467167
...                                             ...
KP      2018                                    NaN
        2019                                    NaN
SO      2019                                    NaN
        2020                                    NaN
KP      2021                                    NaN

              General Govt Debt (Percentage of GDP)  Grant  Loan  Vague  \
Country Year
AE      2005                               4.481497    0.0   0.0    0.0
AF      2005                                    NaN    1.0   0.0    0.0
AG      2005                                    NaN    1.0   1.0    0.0
AL      2005                              58.203359    1.0   0.0    0.0
AM      2005                                    NaN    0.0   0.0    0.0
...                                             ...    ...   ...    ...
KP      2018                                    NaN    NaN   NaN    NaN
        2019                                    NaN    NaN   NaN    NaN
SO      2019                                    NaN    NaN   NaN    NaN
        2020                                    NaN    NaN   NaN    NaN
KP      2021                                    NaN    NaN   NaN    NaN

              Commercial  Development  Mixed  Representational  \
Country Year
AE      2005         0.0          0.0    0.0               0.0
AF      2005         0.0          1.0    0.0               0.0
AG      2005         0.0          2.0    0.0               0.0
AL      2005         0.0          1.0    0.0               0.0
AM      2005         0.0          0.0    0.0               0.0
...                  ...          ...    ...               ...
KP      2018         NaN          NaN    NaN               NaN
        2019         NaN          NaN    NaN               NaN
SO      2019         NaN          NaN    NaN               NaN
        2020         NaN          NaN    NaN               NaN
KP      2021         NaN          NaN    NaN               NaN

              ACTION RELATING TO DEBT  ...  e_autoc  e_democ  e_p_polity  \
Country Year                           ...
AE      2005                      0.0  ...      8.0      0.0        -8.0
AF      2005                      0.0  ...    -66.0    -66.0       -66.0
AG      2005                      0.0  ...      NaN      NaN         NaN
AL      2005                      0.0  ...      0.0      9.0         9.0
AM      2005                      0.0  ...      0.0      5.0         5.0
...                               ...  ...      ...      ...         ...
KP      2018                      NaN  ...     10.0      0.0       -10.0
        2019                      NaN  ...      NaN      NaN         NaN
SO      2019                      NaN  ...      NaN      NaN         NaN
        2020                      NaN  ...      NaN      NaN         NaN
KP      2021                      NaN  ...      NaN      NaN         NaN

                  e_gdp     e_pop  gdp_per_cap   CPI  Peaceful Count  \
Country Year
AE      2005  44675.582   502.176    88.963993   NaN             NaN
AF      2005   2912.684  2746.122     1.060654   NaN             NaN
AG      2005        NaN       NaN          NaN   NaN             NaN
AL      2005   2140.925   321.135     6.666745   NaN             NaN
AM      2005   2085.719   315.380     6.613352   NaN             NaN
...                 ...       ...          ...   ...             ...
KP      2018   4867.297  2712.980     1.794078  14.0             NaN
        2019   4873.972  2717.578     1.793498  17.0             NaN
SO      2019   2710.709  1581.318     1.714209   9.0            70.0
        2020        NaN       NaN          NaN  12.0            99.0
KP      2021        NaN       NaN          NaN  16.0             NaN

              Intervention Count  Excessive Count
Country Year
AE      2005                 NaN              NaN
AF      2005                 NaN              NaN
AG      2005                 NaN              NaN
AL      2005                 NaN              NaN
AM      2005                 NaN              NaN
...                          ...              ...
KP      2018                 NaN              NaN
        2019                 NaN              NaN
SO      2019                 3.0              5.0
        2020                 9.0             11.0
KP      2021                 NaN              NaN

[3274 rows x 136 columns]

In [494]:
loan_debt_data.reset_index(inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)
C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\3624301744.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.reset_index(inplace = True)

In [495]:
loan_debt_data = loan_debt_data.sort_values(["Year", "Country"])

In [496]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,e_autoc,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count
0,AE,2005,NaN,4.481497,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,0.0,-8.0,44675.582,502.176,88.963993,NaN,NaN,NaN,NaN
1,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,-66.0,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,NaN,NaN,NaN
2,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,9.0,9.0,2140.925,321.135,6.666745,NaN,NaN,NaN,NaN
4,AM,2005,20.467167,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,5.0,2085.719,315.380,6.613352,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,WS,2021,46.300071,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3251,YE,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN
3252,ZA,2021,68.978427,NaN,3.0,1.0,0.0,1.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN
3253,ZM,2021,110.789739,NaN,4.0,1.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,33.0,NaN,NaN,NaN
3254,ZW,2021,59.806567,NaN,7.0,2.0,0.0,0.0,9.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN

In [497]:
loan_debt_data["Total Count"] = loan_debt_data["Peaceful Count"] + loan_debt_data["Intervention Count"] + loan_debt_data["Excessive Count"]

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\598874205.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data["Total Count"] = loan_debt_data["Peaceful Count"] + loan_debt_data["Intervention Count"] + loan_debt_data["Excessive Count"]

In [498]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count,Total Count
0,AE,2005,NaN,4.481497,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-8.0,44675.582,502.176,88.963993,NaN,NaN,NaN,NaN,NaN
1,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,NaN,NaN,NaN,NaN
2,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,...,9.0,9.0,2140.925,321.135,6.666745,NaN,NaN,NaN,NaN,NaN
4,AM,2005,20.467167,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,2085.719,315.380,6.613352,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,WS,2021,46.300071,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3251,YE,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN
3252,ZA,2021,68.978427,NaN,3.0,1.0,0.0,1.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN
3253,ZM,2021,110.789739,NaN,4.0,1.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN
3254,ZW,2021,59.806567,NaN,7.0,2.0,0.0,0.0,9.0,0.0,...,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN

In [499]:
loan_debt_data[["Peaceful Count", "Intervention Count", "Excessive Count", "Total Count"]] = loan_debt_data[["Peaceful Count", "Intervention Count", "Excessive Count", "Total Count"]].fillna(0)

In [500]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count,Total Count
0,AE,2005,NaN,4.481497,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-8.0,44675.582,502.176,88.963993,NaN,0.0,0.0,0.0,0.0
1,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,0.0,0.0,0.0,0.0
2,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,...,9.0,9.0,2140.925,321.135,6.666745,NaN,0.0,0.0,0.0,0.0
4,AM,2005,20.467167,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,2085.719,315.380,6.613352,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,WS,2021,46.300071,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3251,YE,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,16.0,0.0,0.0,0.0,0.0
3252,ZA,2021,68.978427,NaN,3.0,1.0,0.0,1.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,44.0,0.0,0.0,0.0,0.0
3253,ZM,2021,110.789739,NaN,4.0,1.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0
3254,ZW,2021,59.806567,NaN,7.0,2.0,0.0,0.0,9.0,0.0,...,NaN,NaN,NaN,NaN,NaN,23.0,0.0,0.0,0.0,0.0

In [501]:
countries = np.unique(loan_debt_data["Country"])

In [502]:
loan_debt_data = loan_debt_data[~loan_debt_data["Country"].isin(["CK", "NU"])]

In [503]:
loan_debt_data

,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,Mixed,...,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count,Total Count
0,AE,2005,NaN,4.481497,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-8.0,44675.582,502.176,88.963993,NaN,0.0,0.0,0.0,0.0
1,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,0.0,0.0,0.0,0.0
2,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,0.0,...,9.0,9.0,2140.925,321.135,6.666745,NaN,0.0,0.0,0.0,0.0
4,AM,2005,20.467167,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,2085.719,315.380,6.613352,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,WS,2021,46.300071,NaN,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3251,YE,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,16.0,0.0,0.0,0.0,0.0
3252,ZA,2021,68.978427,NaN,3.0,1.0,0.0,1.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,44.0,0.0,0.0,0.0,0.0
3253,ZM,2021,110.789739,NaN,4.0,1.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0
3254,ZW,2021,59.806567,NaN,7.0,2.0,0.0,0.0,9.0,0.0,...,NaN,NaN,NaN,NaN,NaN,23.0,0.0,0.0,0.0,0.0

In [504]:
country_id_dict = {country: (i + 1) for i, country in enumerate(np.unique(loan_debt_data["Country"]))}

In [505]:
Country_id = loan_debt_data["Country"].apply(lambda x: country_id_dict[x])

In [506]:
Country_id

0         1
1         2
2         3
3         4
4         5
       ...
3250    188
3251    189
3252    190
3253    191
3254    192
Name: Country, Length: 3264, dtype: int64

In [507]:
loan_debt_data.insert(0, "Country_ID", Country_id)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\2380573496.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.insert(0, "Country_ID", Country_id)

In [508]:
loan_debt_data

,Country_ID,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,Development,...,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count,Total Count
0,1,AE,2005,NaN,4.481497,0.0,0.0,0.0,0.0,0.0,...,0.0,-8.0,44675.582,502.176,88.963993,NaN,0.0,0.0,0.0,0.0
1,2,AF,2005,206.356007,NaN,1.0,0.0,0.0,0.0,1.0,...,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,0.0,0.0,0.0,0.0
2,3,AG,2005,92.614383,NaN,1.0,1.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4,AL,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,1.0,...,9.0,9.0,2140.925,321.135,6.666745,NaN,0.0,0.0,0.0,0.0
4,5,AM,2005,20.467167,NaN,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,2085.719,315.380,6.613352,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,188,WS,2021,46.300071,NaN,1.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3251,189,YE,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,16.0,0.0,0.0,0.0,0.0
3252,190,ZA,2021,68.978427,NaN,3.0,1.0,0.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,44.0,0.0,0.0,0.0,0.0
3253,191,ZM,2021,110.789739,NaN,4.0,1.0,0.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0
3254,192,ZW,2021,59.806567,NaN,7.0,2.0,0.0,0.0,9.0,...,NaN,NaN,NaN,NaN,NaN,23.0,0.0,0.0,0.0,0.0

In [509]:
country_code = loan_debt_data["Country"].apply(lambda x: alpha_2_to_alpha_3[x])
loan_debt_data.insert(1, "Country_Code", country_code)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\2087051124.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  loan_debt_data.insert(1, "Country_Code", country_code)

In [510]:
loan_debt_data.replace(alpha_2_to_name, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10976\2540161076.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_debt_data.replace(alpha_2_to_name, inplace = True)

In [511]:
loan_debt_data

,Country_ID,Country_Code,Country,Year,Central Govt Debt (Percentage of GDP),General Govt Debt (Percentage of GDP),Grant,Loan,Vague,Commercial,...,e_democ,e_p_polity,e_gdp,e_pop,gdp_per_cap,CPI,Peaceful Count,Intervention Count,Excessive Count,Total Count
0,1,ARE,United Arab Emirates,2005,NaN,4.481497,0.0,0.0,0.0,0.0,...,0.0,-8.0,44675.582,502.176,88.963993,NaN,0.0,0.0,0.0,0.0
1,2,AFG,Afghanistan,2005,206.356007,NaN,1.0,0.0,0.0,0.0,...,-66.0,-66.0,2912.684,2746.122,1.060654,NaN,0.0,0.0,0.0,0.0
2,3,ATG,Antigua and Barbuda,2005,92.614383,NaN,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,4,ALB,Albania,2005,58.199553,58.203359,1.0,0.0,0.0,0.0,...,9.0,9.0,2140.925,321.135,6.666745,NaN,0.0,0.0,0.0,0.0
4,5,ARM,Armenia,2005,20.467167,NaN,0.0,0.0,0.0,0.0,...,5.0,5.0,2085.719,315.380,6.613352,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,188,WSM,Samoa,2021,46.300071,NaN,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3251,189,YEM,Yemen,2021,85.083023,85.083023,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,16.0,0.0,0.0,0.0,0.0
3252,190,ZAF,South Africa,2021,68.978427,NaN,3.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,44.0,0.0,0.0,0.0,0.0
3253,191,ZMB,Zambia,2021,110.789739,NaN,4.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,33.0,0.0,0.0,0.0,0.0
3254,192,ZWE,Zimbabwe,2021,59.806567,NaN,7.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,23.0,0.0,0.0,0.0,0.0

In [512]:
types = loan_debt_data.dtypes
types = pd.DataFrame(types)
types.reset_index(inplace = True)
types = types.rename({"index": "Column", 0: "Type"}, axis = 1)
types = types.astype(str)
#gdp per cap is float on my end

In [513]:
loan_debt_data.to_csv("loan_debt_data.csv", index = False)

In [514]:
#add iso3 instead of iso2, bump up countryid by one (no zero), check for strings in the columns (gdp per cap), add direct receiving agencies type (Recipient gov age, recipient ngo, private sector (convert joint venture into chinese joint venture)), add total sum and average value for amount recieived, add non chinese financer (yeses)